return {
	armhaca = {
		blocking = false,
		builddistance = 136,
		builder = true,
		buildpic = "ARMCSA.DDS",
		buildtime = 12000,
		canfly = true,
		canmove = true,
		cansubmerge = true,
		collide = true,
		cruisealtitude = 50,
		energycost = 7800,
		energymake = 20,
		energystorage = 75,
		explodeas = "smallexplosiongeneric-builder",
		footprintx = 2,
		footprintz = 2,
		health = 405,
		hoverattack = true,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.07,
		maxdec = 0.4275,
		maxslope = 10,
		maxwaterdepth = 255,
		metalcost = 150,
		objectname = "Units/ARMCSA.s3o",
		script = "Units/ARMCSA.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd-builder",
		sightdistance = 364,
		speed = 192,
		terraformspeed = 300,
		turninplaceanglelimit = 360,
		turnrate = 240,
		workertime = 75,
		buildoptions = {
				[1] = "armafus",
				[2] = "armckfus",
				[3] = "armageo",
				[4] = "armgmm",
				[5] = "armmoho",
				[6] = "armmmkr",
				[7] = "armuwadves",
				[8] = "armuwadvms",
				[9] = "armfort",
				[10] = "armtarg",
				[11] = "armgate",
				[12] = "armamb",
				[13] = "armpb",
				[14] = "armanni",
				[15] = "armflak",
				[16] = "armmercury",
				[17] = "armemp",
				[18] = "armamd",
				[19] = "armsilo",
				[20] = "armbrtha",
				[21] = "armvulc",
				[22] = "armdf",
				[23] = "armaap",
				[24] = "armhaap",
			},
		customparams = {
			model_author = "Flaka",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmSeaplanes",
			unitgroup = "builder",
		},
		sfxtypes = {
			crashexplosiongenerators = {
				[1] = "crashing-small",
				[2] = "crashing-small",
				[3] = "crashing-small2",
				[4] = "crashing-small3",
				[5] = "crashing-small3",
			},
			pieceexplosiongenerators = {
				[1] = "airdeathceg2-builder",
				[2] = "airdeathceg3-builder",
				[3] = "airdeathceg4-builder",
			},
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "seapsel1",
			},
		},
	},
}
