-- sky_enterance

return {
  ["sky_enterance"] = {
     smokecloud_fast = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1, --1
      ground             = true,
      underwater         = 0,
      water              = true,
      properties = {
        airdrag            = 0.98,
        colormap           = [[0 0 0 0.01           0.9 0.9 0.9 0.4 		                0 0 0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 360,
        emitvector         = [[0,1,0]],
        gravity            = [[0 , 0.0012, 0]],
        numparticles       = 35,
        particlelife       = 80,
        particlelifespread = 140,
        particlesize       = 50,
        particlesizespread = 25,
        particlespeed      = [[3 i-0.75]],
        particlespeedspread = 2.2,
        pos                = [[-13 r13,-13 r13,-13 r13]],
        sizegrowth         = 1,
        sizemod            = 1.0,
        texture            = [[smoke_puff]],
      },
    },
     glow = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[0.55 0.6 0.9 0.007    0.55 0.7 1 0.007              0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[0, 0, 0]],
        gravity            = [[0, 0.00, 0]],
        numparticles       = 1,
        particlelife       = 160,
        particlelifespread = 0,
        particlesize       = 5,
        particlesizespread = 10,
        particlespeed      = 1,
        particlespeedspread = 0,
        pos                = [[0, 2, 0]],
        sizegrowth         = 13.0,
        sizemod            = 1.0,
        texture            = [[flare1]],
      },
    },
      skysparkle = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 30,
      ground             = true,
      water              = false,
      properties = {
        delay              = [[0 i2]],
        explosiongenerator = [[custom:sky_sparkle]],
        pos                = [[-120 r240, -120 r240,-120 r240]],
      },
    },
     skysparkle1_delay = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = false,
      properties = {
        delay              = 61,
        explosiongenerator = [[custom:sky_sparkle_spawner]],
        pos                = [[0,0,0]],
      },
    },
     glow_again = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = false,
      properties = {
        delay              = [[30]],
        explosiongenerator = [[custom:2nd_glow]],
        pos                = [[0,0,0]],
      },
    },
  },
   ["sky_sparkle_spawner"] = {  
    skysparkle1 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 13,
      ground             = true,
      water              = false,
      properties = {
        delay              = [[0 i4]],
        explosiongenerator = [[custom:sky_sparkle1]],
        pos                = [[0,0,0]],
      },
     },
    },
     ["sky_sparkle"] = {
     unit_sparkles = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
      water              = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0 0 0 0	0.5 0.5 0.5 0.2	  0.8 0.8 0.8 0.4	  0.3 0.3 0.3 0.2	  0.1 0.1 0.1 0.1	  0 0 0 0.01]],
        directional        = true,
        emitrot            = [[0 r360]],
        emitrotspread      = 270,
        emitvector         = [[0, -1, 0]],
        gravity            = [[0,0,0]],
        numparticles       = 1,
        particlelife       = 6,
        particlelifespread = 8,
        particlesize       = 30,
        particlesizespread = 22,
        particlespeed      = 2,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 1.25,
        sizemod            = -1.0,
        texture            = [[lightningball2]],
      },
    },
   },
     ["sky_sparkle1"] = {
     unit_sparkles = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
      water              = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0 0 0 0	0.5 0.5 0.5 0.02	  0.8 0.8 0.8 0.04	  0.3 0.3 0.3 0.02	  0.1 0.1 0.1 0.01	  0 0 0 0.01]],
        directional        = true,
        emitrot            = [[0 r360]],
        emitrotspread      = 270,
        emitvector         = [[0, -1, 0]],
        gravity            = [[0,0,0]],
        numparticles       = 1,
        particlelife       = 6,
        particlelifespread = 8,
        particlesize       = 65,
        particlesizespread = 22,
        particlespeed      = 2,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 1.25,
        sizemod            = -1.0,
        texture            = [[lightring]],
      },
    },
        unit_sparkles2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
      water              = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0 0 0 0	0.5 0.5 0.5 0.02	  0.8 0.8 0.8 0.04	  0.3 0.3 0.3 0.02	  0.1 0.1 0.1 0.01	  0 0 0 0.01]],
        directional        = true,
        emitrot            = [[0 r360]],
        emitrotspread      = 270,
        emitvector         = [[0, -1, 0]],
        gravity            = [[0,0,0]],
        numparticles       = 1,
        particlelife       = 6,
        particlelifespread = 8,
        particlesize       = 40,
        particlesizespread = 22,
        particlespeed      = 2,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 1.25,
        sizemod            = -1.0,
        texture            = [[lightning]],
      },
    },
},
   ["2nd_glow"] = {
      glow1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[0.55 0.6 0.9 0.007    0.55 0.7 1 0.007              0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[0, 0, 0]],
        gravity            = [[0, 0.00, 0]],
        numparticles       = 1,
        particlelife       = 200,
        particlelifespread = 0,
        particlesize       = 5,
        particlesizespread = 4,
        particlespeed      = 1,
        particlespeedspread = 0,
        pos                = [[0, 2, 0]],
        sizegrowth         = 4.0,
        sizemod            = 1.0,
        texture            = [[flare1]],
      },
    },
   },
}

