return {
	cordesolator = {
		activatewhenbuilt = true,
		buildangle = 8192,
		buildpic = "cordesolator.DDS",
		buildtime = 140000,
		canmanualfire = true,
		canmove = true,
		collisionvolumeoffsets = "0 1 4",
		collisionvolumescales = "20 45 100",
		collisionvolumetype = "box",
		corpse = "DEAD",
		energycost = 95000,
		explodeas = "nukeSub",
		firestate = 2,
		footprintx = 7,
		footprintz = 7,
		health = 2600,
		idleautoheal = 7,
		idletime = 1800,
		maxacc = 0.03,
		maxdec = 0.05,
		maxslope = 10,
		maxwaterdepth = 9999,
		metalcost = 9000,
		minwaterdepth = 20,
		movementclass = "UBOAT4",
		nochase = "ALL",
		objectname = "Units/CORDESOLATOR.s3o",
		radardistance = 50,
		script = "Units/cordesolator.cob",
		seismicsignature = 0,
		selfdestructas = "nukeBuildingSelfd",
		sightdistance = 450,
		sonardistance = 1100,
		speed = 45,
		turninplace = true,
		turninplaceanglelimit = 90,
		turnrate = 300,
		upright = true,
		waterline = 40,
		customparams = {
			maxrange = "720",
			model_author = "Hornet",
			normaltex = "unittextures/cor_normal.dds",
			removewait = true,
			subfolder = "CorShips/T2",
			techlevel = 2,
			unitgroup = "nuke",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "0 1 4",
				collisionvolumescales = "40 40 100",
				collisionvolumetype = "Box",
				damage = 1362,
				energy = 0,
				featuredead = "HEAP",
				footprintx = 6,
				footprintz = 6,
				height = 4,
				hitdensity = 100,
				metal = 375,
				object = "Units/cordesolator_dead.s3o",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 4032,
				energy = 0,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 187,
				object = "Units/cor2X2A.s3o",
				reclaimable = true,
				resurrectable = 0,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[0] = "custom:subbubbles",
				[1] = "custom:subwake",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servroc1",
			},
			select = {
				[1] = "servroc1",
			},
		},
		weapondefs = {
			crblmssl = {
				areaofeffect = 1920,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "NUKETRAIL",
				collideenemy = false,
				collidefeature = false,
				collidefriendly = false,
				commandfire = true,
				craterareaofeffect = 1920,
				craterboost = 2.4,
				cratermult = 1.2,
				edgeeffectiveness = 0.45,
				energypershot = 187500,
				explosiongenerator = "custom:newnukecor",
				firestarter = 100,
				flighttime = 400,
				impulsefactor = 0.5,
				metalpershot = 1500,
				model = "cortronmissile.s3o",
				name = "Intercontinental thermonuclear ballistic missile",
				range = 72000,
				reloadtime = 30,
				smokecolor = 0.85,
				smokeperiod = 10,
				smokesize = 28,
				smoketime = 130,
				smoketrail = true,
				smoketrailcastshadow = true,
				soundhit = "nukecor",
				soundhitwet = "nukewater",
				soundhitwetvolume = 56,
				soundstart = "nukelaunch",
				soundstartvolume = 20,
				stockpile = true,
				stockpiletime = 210,
				targetable = 1,
				texture1 = "null",
				texture2 = "railguntrail",
				texture3 = "null",
				tolerance = 4000,
				turnrate = 5500,
				waterweapon = true,
				weaponacceleration = 100,
				weapontimer = 5.5,
				weapontype = "StarburstLauncher",
				weaponvelocity = 1600,
				customparams = {
					place_target_on_ground = "true",
					scavforcecommandfire = true,
					stockpilelimit = 10,
				},
				damage = {
					commanders = 2500,
					default = 11500,
				},
			},
			nuclear_launch = {
				areaofeffect = 0,
				avoidfeature = false,
				avoidfriendly = false,
				commandfire = true,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0,
				impulsefactor = 0,
				metalpershot = 0,
				name = "Nuclear Launch",
				range = 0,
				reloadtime = 30,
				soundhit = "nukelaunchalarm",
				soundhitvolume = 50,
				tolerance = 10000,
				turnrate = 10000,
				weaponacceleration = 101,
				weapontimer = 0.1,
				weapontype = "Cannon",
				weaponvelocity = 100,
				customparams = {
					scavforcecommandfire = true,
				},
				damage = {
					default = 0,
				},
			},
			waterballon = {
				areaofeffect = 16,
				avoidfeature = false,
				avoidfriendly = false,
				burnblow = true,
				cegtag = "torpedotrail-small",
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-large-uw",
				impulsefactor = 0.123,
				model = "torpedo.s3o",
				name = "Torpedo launcher",
				noselfdamage = true,
				range = 750,
				reloadtime = 8,
				soundhit = "xplodep1",
				soundhitvolume = 22,
				soundstart = "torpedo1",
				startvelocity = 150,
				tolerance = 8000,
				tracks = true,
				turnrate = 2550,
				turret = true,
				waterweapon = true,
				weaponacceleration = 20,
				weapontimer = 3,
				weapontype = "TorpedoLauncher",
				weaponvelocity = 280,
				damage = {
					commanders = 350,
					default = 850,
					subs = 510,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "HOVER NOTSHIP",
				def = "waterballon",
				maindir = "0 0 1",
				maxangledif = 40,
				onlytargetcategory = "NOTHOVER",
			},
			[2] = {
				def = "CRBLMSSL",
				onlytargetcategory = "NOTSUB",
			},
			[3] = {
				def = "NUCLEAR_LAUNCH",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
