return {
	corhacs = {
		builddistance = 250,
		builder = true,
		buildpic = "CORMLS.DDS",
		buildtime = 49600,
		canmove = true,
		collisionvolumeoffsets = "0 -5 0",
		collisionvolumescales = "28 20 42",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 23600,
		explodeas = "mediumexplosiongeneric",
		floater = true,
		footprintx = 3,
		footprintz = 3,
		health = 2600,
		idleautoheal = 5,
		idletime = 1800,
		mass = 2700,
		maxacc = 0.03446,
		maxdec = 0.03446,
		metalcost = 1180,
		minwaterdepth = 15,
		movementclass = "BOAT3",
		movestate = 0,
		objectname = "Units/CORMLS.s3o",
		script = "Units/CORMLS.cob",
		seismicsignature = 0,
		selfdestructas = "mediumexplosiongenericSelfd",
		sightdistance = 300,
		speed = 55,
		terraformspeed = 2000,
		turninplace = true,
		turninplaceanglelimit = 90,
		turnrate = 393,
		waterline = 0,
		workertime = 700,
		buildoptions = {
			[1] = "coruwfus",
			[2] = "coruwmmm",
			[3] = "coruwmme",
			[4] = "coruwadves",
			[5] = "coruwadvms",
			[7] = "corhasy",
			[8] = "corasy",
			[10] = "corfatf",
			[11] = "coratl",
			[12] = "corenaa",
			[13] = "corfdoom",
			[14] = "coruwageo",
			[15] = "corjugg",
			[16] = "corkorg",
			[17] = "corafus",
			[18] = "cortide",
			[19] = "corscreamer",
			[20] = "corvipe",
			[21] = "corfdrag",
			[22] = "corgate",
			[23] = "corsd",
			[29] = "corlab",
			[30] = "corap",
			[31] = "corvp",
			[32] = "corsy",
			[33] = "corint",
			[34] = "corsilo",
			[35] = "corbuzz",
			[36] = "corgantuw"
		},
		customparams = {
			minesweeper = 600,
			model_author = "Beherith",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "CorShips/T2",
			techlevel = 3,
			unitgroup = "buildert2",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-0.0500030517578 -0.0636029345703 -0.0",
				collisionvolumescales = "33.75 14.0462341309 88.0440979004",
				collisionvolumetype = "Box",
				damage = 1726,
				featuredead = "HEAP",
				footprintx = 4,
				footprintz = 4,
				height = 20,
				metal = 100,
				object = "Units/cormls_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "85.0 14.0 6.0",
				collisionvolumetype = "cylY",
				damage = 4032,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 50,
				object = "Units/cor4X4A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:waterwake-small",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			repair = "repair2",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "shcormov",
			},
			select = {
				[1] = "shcorsel",
			},
		},
	},
}
