return {
	corssub = {
		activatewhenbuilt = true,
		buildpic = "CORSSUB.DDS",
		buildtime = 24750,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "52 25 60",
		collisionvolumetype = "box",
		corpse = "DEAD",
		energycost = 29000,
		explodeas = "largeexplosiongeneric-uw",
		footprintx = 4,
		footprintz = 4,
		health = 3900,
		idleautoheal = 15,
		idletime = 900,
		maxacc = 0.018,
		maxdec = 0.018,
		metalcost = 1900,
		minwaterdepth = 20,
		movementclass = "UBOAT4",
		movestate = 0,
		nochasecategory = "VTOL",
		objectname = "Units/CORSSUB.s3o",
		script = "Units/CORSSUB.cob",
		seismicsignature = 0,
		selfdestructas = "largeexplosiongenericSelfd-uw",
		sightdistance = 570,
		sonardistance = 400,
		speed = 39,
		stealth = true,
		turninplace = true,
		turninplaceanglelimit = 90,
		turnrate = 320,
		upright = true,
		waterline = 80,
		customparams = {
			model_author = "Beherith",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "CorShips/T2",
			techlevel = 2,
			unitgroup = "sub",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "-6.04158782959 -4.50195312496e-06 -0.0",
				collisionvolumescales = "39.0926055908 13.0902709961 63.9697265625",
				collisionvolumetype = "Box",
				damage = 2200,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 1050,
				object = "Units/corssub_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 4400,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 525,
				object = "Units/cor2X2A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[0] = "custom:subbubbles",
				[1] = "custom:subwake",
				[2] = "custom:subtorpfire-medium",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "sucormov",
			},
			select = {
				[1] = "sucorsel",
			},
		},
		weapondefs = {
			armserp_weapon = {
				areaofeffect = 160,
				avoidfeature = false,
				avoidfriendly = false,
				burnblow = true,
				cegtag = "torpedotrail-large",
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-large-uw",
				impulsefactor = 0.123,
				model = "coradvtorpedo.s3o",
				name = "AdvTorpedo",
				noselfdamage = true,
				range = 850,
				reloadtime = 8,
				soundhit = "xplodep1",
				soundhitvolume = 22,
				soundstart = "torpedo1",
				startvelocity = 150,
				tolerance = 8000,
				tracks = true,
				turnrate = 1500,
				turret = true,
				waterweapon = true,
				weaponacceleration = 25,
				weapontimer = 4,
				weapontype = "TorpedoLauncher",
				weaponvelocity = 220,
				damage = {
					commanders = 750,
					default = 1650,
					subs = 1110,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "HOVER NOTSHIP",
				def = "ARMSERP_WEAPON",
				maindir = "0 0.2 1",
				maxangledif = 80,
				onlytargetcategory = "NOTHOVER",
			},
		},
	},
}
