return {
	armsd = {
		activatewhenbuilt = true,
		buildangle = 4096,
		energycost = 7100,
		metalcost = 710,
		buildpic = "ARMSD.DDS",
		buildtime = 11900,
		canrepeat = false,
		category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
		collisionvolumeoffsets = "0 -6 0",
		collisionvolumescales = "75 23 75",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energyupkeep = 125,
		explodeas = "mediumBuildingexplosiongeneric",
		footprintx = 4,
		footprintz = 4,
		idleautoheal = 5,
		idletime = 1800,
		levelground = false,
		health = 2650,
		maxslope = 10,
		maxwaterdepth = 0,
		objectname = "Units/ARMSD.s3o",
		onoffable = true,
		script = "Units/ARMSD.cob",
		seismicdistance = 2000,
		seismicsignature = 0,
		selfdestructas = "mediumBuildingExplosionGenericSelfd",
		sightdistance = 240,
		yardmap = "oooooooooooooooo",
		customparams = {
			usebuildinggrounddecal = true,
			buildinggrounddecaltype = "decals/armsd_aoplane.dds",
			buildinggrounddecalsizey = 6,
			buildinggrounddecalsizex = 6,
			buildinggrounddecaldecayspeed = 30,
			unitgroup = 'util',
			model_author = "Beherith",
			normaltex = "unittextures/Arm_normal.dds",
			removestop = true,
			removewait = true,
			subfolder = "armbuildings/landutil",
			techlevel = 2,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "1.95468139648 -4.13748790283 4.81853485107",
				collisionvolumescales = "63.6464233398 24.2004241943 64.3273773193",
				collisionvolumetype = "Box",
				damage = 1440,
				featuredead = "HEAP",
				footprintx = 4,
				footprintz = 4,
				height = 15,
				metal = 566,
				object = "Units/armsd_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "85.0 14.0 6.0",
				collisionvolumetype = "cylY",
				damage = 720,
				footprintx = 4,
				footprintz = 4,
				height = 4,
				metal = 227,
				object = "Units/arm4X4A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			activate = "cmd-on",
			canceldestruct = "cancel2",
			deactivate = "cmd-off",
			underattack = "warning1",
			working = "cmd-on",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "targsel1",
			},
		},
	},
}
