return {
	legadvaabot = {
		airsightdistance = 850,
		buildpic = "legadvaabot.DDS",
		buildtime = 11270,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "20 40 20",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 6650,
		explodeas = "smallexplosiongeneric-phib",
		footprintx = 2,
		footprintz = 2,
		health = 1200,
		maxacc = 0.138,
		maxdec = 0.6486,
		metalcost = 750,
		movementclass = "ABOT3",
		movestate = 0,
		nochasecategory = "NOTAIR",
		objectname = "Units/legadvaabot.s3o",
		script = "Units/legadvaabot.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd-phib",
		sightdistance = 390,
		speed = 34.5,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 0.759,
		turnrate = 1048.79993,
		upright = true,
		customparams = {
			model_author = "Johnathan Crimson",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/Bots/T2 Bots",
			techlevel = 2,
			unitgroup = "aa",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "37 19 30",
				collisionvolumetype = "Box",
				damage = 1548,
				featuredead = "HEAP",
				footprintx = 4,
				footprintz = 4,
				height = 15,
				metal = 395,
				object = "Units/legadvaabot_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "85.0 14.0 6.0",
				collisionvolumetype = "cylY",
				damage = 774,
				footprintx = 4,
				footprintz = 4,
				height = 4,
				metal = 158,
				object = "Units/cor4X4A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-small-aa",
				[2] = "custom:barrelshot-flak",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbcormov",
			},
			select = {
				[1] = "kbcorsel",
			},
		},
		weapondefs = {
			leg_t2_microflak_mobile = {
				accuracy = 1000,
				areaofeffect = 35,
                burst = 3,
				burstrate = 0.02,
				avoidfeature = false,
				burnblow = true,
				canattackground = false,
				cegtag = "flaktrailaamg",
				craterareaofeffect = 35,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = 1,
				collidefriendly = false,
				edgeeffectiveness = 1,
				explosiongenerator = "custom:flakshard",
				gravityaffected = "true",
				impulsefactor = 0,
				name = "Rotary Microflak Cannon",
				noselfdamage = true,
				range = 650,
				reloadtime = 0.237,
				size = 0,
				sizedecay = 0.08,
				soundhit = "flakhit",
				soundhitwet = "splsmed",
				soundstart = "flakfire",
				stages = 0,
				turret = true,
				weapontimer = 1,
				weapontype = "Cannon",
				weaponvelocity = 1900,
				customparams = {
					norangering = 1,
					preaim_range = 1050,
				},
				damage = {
					vtol = 40,
				},
				rgbcolor = {
					[1] = 1,
					[2] = 0.33,
					[3] = 0.7,
				},
			},
			aa_railgun = {
				areaofeffect = 16,
				avoidfeature = true,
				burnblow = true,
				cegtag = "railgun",
				collisionsize = 0.7,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.12,
				edgeeffectiveness = 0.85,
				explosiongenerator = "custom:plasmahit-sparkonly",
				firestarter = 0,
				hardstop = true,
				impactonly = true,
				impulsefactor = 1,
				intensity = 0.8,
				name = "Light Anti-Air Railgun",
				noexplode = true,
				noselfdamage = true,
				ownerExpAccWeight = 4.0,
				proximitypriority = 1,
				range = 1050,
				reloadtime = 4,
				rgbcolor = "0.94 0.4 0.94",
				soundhit = "mavgun3",
				soundhitwet = "splshbig",
				soundstart = "lancefire",
				soundstartvolume = 25,
				thickness = 2,
				tolerance = 6000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 3214,
				customparams = {
					overpenetrate = true,
				},
				damage = {
					--commanders = 100,
					default = 1,
					vtol = 225,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "LIGHTAIRSCOUT",
				burstcontrolwhenoutofarc = 2,
				def = "leg_t2_microflak_mobile",
				fastautoretargeting = true,
				onlytargetcategory = "VTOL",
			},
			[2] = {
				badtargetcategory = "LIGHTAIRSCOUT",
				def = "aa_railgun",
				onlytargetcategory = "VTOL",
				slaveto = 1,
			},
		},
	},
}
