return {
	chip = {
		acceleration = 0,
		brakerate = 0,
		buildcostenergy = 200,
		buildcostmetal = 10,
		buildpic = "",
		buildtime = 255,
		canattack = false,
		canrepeat = false,
		category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "12 1.7 12",
		collisionvolumetype = "CylY",
		crushresistance = 2500,
		description = "Chip",
		footprintx = 1,
		footprintz = 1,
		hidedamage = true,
		idleautoheal = 0,
		levelground = false,
		maxdamage = 5000000,
		maxslope = 64,
		maxwaterdepth = 250,
		name = "Chip",
		objectname = "chip_r.s3o",
		repairable = false,
		script = "",
		seismicsignature = 0,
		sightdistance = 1,
		usebuildinggrounddecal = false,
		yardmap = "f",
        blocking = false,
        stealth = true,
        sonarStealth = true,
        capturable = false,
	},
}
