return {
	dice = {
		blocking = true,
		buildcostenergy = 0,
		buildcostmetal = 0,
		buildtime = 255,
		canattack = false,
		canmove = true,
		canrepeat = false,
		capturable = false,
		category = "OBJECT",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "14 14 14",
		collisionvolumetype = "Box",
		crushresistance = 2500,
		description = "Dice",
		explodeas = "blank",
		footprintx = 1,
		footprintz = 1,
		hidedamage = true,
		idleautoheal = 0,
		mass = 50,
		maxdamage = 500000,
		maxslope = 64,
		maxvelocity = 1,
		maxwaterdepth = 0,
		movementclass = "CRITTERH",
		name = "Dice",
		objectname = "dice.s3o",
		reclaimable = false,
		repairable = false,
		script = "dice.lua",
		seismicsignature = 0,
		selfdestructas = "blank",
		sightdistance = 0,
		sonarstealth = true,
		stealth = true,
		usebuildinggrounddecal = false,
		yardmap = "f",
		customparams = {
			nohealthbars = true,
			subfolder = "other",
		},
	},
}
