return {
	legsrailt4 = {
		maxacc = 0.04,
		maxdec = 0.150,
		energycost = 300000,
		metalcost = 15000,
		buildpic = "LEGSRAIL.DDS",
		buildtime = 300000,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "99 88 99",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		explodeas = "explosiont3",
		footprintx = 5,
		footprintz = 5,
		idleautoheal = 5,
		idletime = 1800,
		health = 40000,
		maxslope = 17,
		speed = 21.0,
		maxwaterdepth = 0,
		movementclass = "EPICALLTERRAIN",
		mygravity = 10000,
		nochasecategory = "VTOL",
		objectname = "Units/scavboss/LEGSRAILT4.s3o",
		script = "Units/scavboss/LEGSRAILT4.cob",
		seismicsignature = 0,
		usepiececollisionvolumes = 0,
		selfdestructas = "explosiont3xl",
		sightdistance = 1200,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1,
		turnrate = 100,
		customparams = {
			unitgroup = 'weapon',
			model_author = "Tharsis",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/gantry",
			techlevel = 3,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-3.37104034424 -1.05229058838 1.8899307251",
				collisionvolumescales = "83 55 73",
				collisionvolumetype = "Box",
				damage = 3000,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 40,
				metal = 7500,
				object = "Units/scavboss/legsrailt4_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "85.0 14.0 6.0",
				collisionvolumetype = "cylY",
				damage = 3015,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 3750,
				object = "Units/arm3X3D.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:rocketflare",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbarmmov",
			},
			select = {
				[1] = "kbarmsel",
			},
		},
		weapondefs = {
			railgunt2 = {
				areaofeffect = 16,
				avoidfeature = false,
				burnblow = true,
				cegtag = "ministarfire",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.02,
				edgeeffectiveness = 0.85,
				energypershot = 3000,
				explosiongenerator = "custom:starfire-explosion",
				fallOffRate = 0.2,
				firestarter = 0,
				hardstop = true,
				impactonly = true,
				impulsefactor = 1,
				intensity = 0.8,
				name = "Railgun",
				noexplode = true,
				noselfdamage = true,
				ownerExpAccWeight = 4.0,
				proximitypriority = 1,
				range = 1600,
				reloadtime = 4,
				rgbcolor = "0.74 0.64 0.94",
				soundhit = "mavgun3",
				soundhitwet = "splshbig",
				soundstart = "railgunxl",
				soundstartvolume = 50,
				stockpile = true,
				stockpiletime = 12,
				thickness = 4,
				tolerance = 6000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 3180,
				customparams = {
				overpenetrate = true,
				stockpilelimit = 3,
				},
				damage = {
					commanders = 1000,
					default = 6000,
				},
			},
		},
		weapons = {
			[1] = {
				def = "RAILGUNT2",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
