return {
	coruwmme = {
		activatewhenbuilt = true,
		buildangle = 32768,
		buildingmask = 0,
		buildpic = "CORUWMME.DDS",
		buildtime = 14100,
		canrepeat = false,
		corpse = "DEAD",
		damagemodifier = 0.5,
		energycost = 8100,
		energyupkeep = 20,
		explodeas = "mediumBuildingexplosiongeneric-uw",
		extractsmetal = 0.004,
		footprintx = 4,
		footprintz = 4,
		health = 3900,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0,
		maxdec = 0,
		maxslope = 30,
		metalcost = 640,
		metalstorage = 600,
		minwaterdepth = 15,
		objectname = "Units/CORUWMME.s3o",
		onoffable = true,
		script = "Units/CORUWMME.cob",
		seismicsignature = 0,
		selfdestructas = "largeBuildingExplosionGenericSelfd-uw",
		sightdistance = 169,
		yardmap = "h cbbbbbbc bssssssb bsssossb bsobbssb bssbbosb bssosssb bssssssb cbbbbbbc",
		customparams = {
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 7.7,
			buildinggrounddecalsizey = 7.7,
			buildinggrounddecaltype = "decals/coruwmme_aoplane.dds",
			cvbuildable = true,
			metal_extractor = 4,
			model_author = "Mr Bob",
			normaltex = "unittextures/cor_normal.dds",
			removestop = true,
			removewait = true,
			subfolder = "CorBuildings/SeaEconomy",
			techlevel = 2,
			unitgroup = "metal",
			usebuildinggrounddecal = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0.0 -4.8856736084 -0.0",
				collisionvolumescales = "80.0 29.6428527832 80.0",
				collisionvolumetype = "Box",
				damage = 1243,
				featuredead = "HEAP",
				footprintx = 5,
				footprintz = 5,
				height = 150,
				metal = 550,
				object = "Units/coruwmme_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 622,
				footprintx = 5,
				footprintz = 5,
				height = 5,
				metal = 220,
				object = "Units/cor5X5C.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			activate = "waterex2",
			canceldestruct = "cancel2",
			deactivate = "waterex2",
			underattack = "warning1",
			working = "waterex2",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "waterex2",
			},
		},
	},
}
