return {
	hat_viking_teamcolored = {
		acceleration = 0,
		blocking = false,
		brakerate = 0,
		buildcostenergy = 10000,
		buildcostmetal = 1000,
		buildpic = "ARMSTONE.PNG",
		buildtime = 10000,
		canattack = false,
		canrepeat = false,
		capturable = true,
		cantbetransported = false,
		category = "OBJECT",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "0.1 0.1 0.1",
		collisionvolumetype = "CylY",
		crushresistance = 2500,
		description = "A fierce Viking helmet",
		footprintx = 1,
		footprintz = 1,
		hidedamage = true,
    icontype = "blank",
		idleautoheal = 100000, --so it doesnt die
		mass = 1,
		maxdamage = 5000000,
		maxslope = 64,
		maxwaterdepth = 1000,
		movementclass = "NANO",
		name = "Viking Helmet",
		objectname = "hats/hat_viking_teamcolored.s3o",
		reclaimable = false,
		repairable = false,
		script = "blank.cob", --"hats/hat.cob",
		seismicsignature = 0,
		sightdistance = 1,
		sonarstealth = true,
		stealth = true,
		upright = false,
		customparams = {
			model_author = "Beherith",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "other/hats",
		},
	},
}
