return {
	T1 = {
		-- Bots
		"armada_pawn",
		"armada_rocketeer",
		"armada_mace",
		"armada_crossbow",
		"armada_centurion",
		"armada_lazarus",
		"cortex_grunt",
		"cortex_graverobber",
		"cortex_thug",
		"cortex_aggravator",
		"cortex_trasher",
		"legkark",
		"leggob",
		"legbal",
		"legcen",

		-- Vehicles
		"armada_blitz",
		"armada_stout",
		"armada_shellshocker",
		"armada_whistler",
		"armada_pincer",
		"armada_janus",
		"cortex_incisor",
		"cortex_lasher",
		"cortex_wolverine",
		"cortex_pounder",
		"cortex_brute",
		"legrail",
		"leggat",

		-- Hovercraft
		"armada_seeker",
		"armada_possum",
		"armada_sweeper",
		"armada_crocodile",
		"cortex_goon",
		"cortex_mangonel",
		"cortex_birdeater",
		"cortex_cayman",

		-- Air
		"armada_stormbringer",
		"armada_falcon",
		"cortex_whirlwind",
		"cortex_shuriken",
		"cortex_valiant",

		-- Sea
		"armada_skater",
		"armada_dolphin",
		"armada_grimreaper",
		"armada_ellysaw",
		"armada_eel",
		"armada_pincer",
		"cortex_herring",
		"cortex_supporter",
		"cortex_deathcavalry",
		"cortex_riptide",
		"cortex_orca",
		"cortex_garpike",
	},

	T2 = {
		-- Bots
		"armada_lazarus",
		"armada_tumbleweed",
		"armada_webber",
		"armada_recluse",
		"armada_sprinter",
		"armada_amphibiousbot",
		"armada_hound",
		"armada_welder",
		"armada_ghost",
		"armada_archangel",
		"armada_sharpshooter",
		"armada_gunslinger",
		"cortex_graverobber",
		"cortex_bedbug",
		"cortex_fiend",
		"cortex_twitcher",
		"cortex_sheldon",
		"cortex_duck",
		"cortex_skuttle",
		"cortex_spectre",
		"cortex_sumo",
		"cortex_manticore",
		"cortex_termite",
		"cortex_commando",
		"legbart",
		"legshot",
		"legsrail",
		"leginfestor",
		"legstr",

		-- Vehicles
		"armada_gremlin",
		"armada_mauser",
		"armada_jaguar",
		"armada_shredder",
		"armada_turtle",
		"armada_ambassador",
		"armada_bull",
		"cortex_forge",
		"cortex_quaker",
		"cortex_fury",
		"cortex_alligator",
		"cortex_tiger",
		"cortex_lasertiger",
		"cortex_negotiator",
		"cortex_banisher",
		"cortex_poisonarrow",
		"legmrv",
		"legsco",

		-- Hovercraft
		"cortex_halberd",
		"legfloat",

		-- Air
		"armada_tsunami",
		"armada_banshee",
		"armada_roughneck",
		"armada_sabre",
		"armada_cyclone",
		"cortex_dambuster",
		"cortex_bat",
		"cortex_cutlass",

		-- Sea
		"armada_corsair",
		--"armada_bermuda",
		"armada_voyager",
		"armada_barracuda",
		"armada_dragonslayer",
		"armada_paladin",
		--"armada_haven",
		"armada_serpent",
		"armada_longbow",
		"armada_turtle",
		"cortex_oppressor",
		--"cortex_phantasm",
		"cortex_pathfinder",
		"cortex_predator",
		"cortex_arrowstorm",
		"cortex_buccaneer",
		--"cortex_oasis",
		"cortex_kraken",
		"cortex_messenger",
		"cortex_alligator",

		-- Hovercraft
		"cortex_halberd",
	},

	T3 = {
		-- Heavy T2s
		"cortex_tzar",
		"cortex_mammoth",
		"armada_fatboy",
		"armada_starlight",
		"cortex_tremor",
		"cortex_arbiter",
		"leginc",
		"leginf",

		-- Bots
		"armada_marauder",
		"armada_vanguard",
		"armada_razorback",
		"cortex_shiva",
		"cortex_karganeth",
		"cortex_catapult",
		"legpede",

		-- Vehicles
		"legkeres",
		"armada_thor_scav",

		-- Hovercraft
		"armada_lunkhead",
		"cortex_cataphract",
		"armada_recluset4",
		"armada_lunchbox",
		"armada_meatball",
		"armada_assimilator",

		-- Air
		"armada_highwind",
		"armada_tsunami",
		"armada_hornet",
		"armada_stiletto",
		"armada_liche",
		"armada_blizzard",
		"cortex_dambuster",
		"cortex_nighthawk",
		"cortex_hailstorm",
		"cortex_wasp",
		"cortex_dragonold",

		-- Sea
		"armada_dreadnought",
		"armada_epoch",
		"cortex_despot",
		"cortex_blackhydra",
		"cortex_basiliskship",
		"armada_epicdolphin",
		"armada_epicellysaw",
		"armada_epicskater",

		-- Hovercraft
		"armada_lunkhead",
		"cortex_cataphract",
	},

	T4 = {
		"cortex_juggernaut",
		"cortex_behemoth",
		"armada_titan",
		"armada_thor",
		"leegmech",

		-- Superboss
		"armada_epicpawn",
		"armada_ratte",
		"armada_epictumbleweed",
		"armada_flyingepoch",
		"cortex_flyingblackhydra",
		"cortex_epicdragon",
		"cortex_demon",
		"cortex_epickarganeth",
		"cortex_epictzar",
		"cortex_epicgrunt",

		-- Air
		"cortex_epicdragon",
		"armada_flyingepoch",
		"cortex_flyingblackhydra",
		"armada_epicstormbringer",

		-- Sea
		"armada_epoch",
		"cortex_blackhydra",
		"cortex_epicdragon",
		"armada_flyingepoch",
		"cortex_flyingblackhydra",
		"armada_epictumbleweed",
		"cortex_juggernaut",
		"armada_titan",
		"armada_epicserpent",
		"cortex_epicsupporter",
	},
}
