
site_name: Docs


theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  search: true
  features:
    - quick-links
    - navigation
    - search
    - toc
    - fullscreen
    - bookmarks
    - tabs
    - code
    - edit-on-github
    - language-selector
    - code
    - cover
    - footer
    - social-share
    - theme-switcher
nav:
  - Home: index.md
  
  - Types:
    - class PlayMusicAction : types/PlayMusicAction.md
    
  
  
  - Modules:
    - play_music : modules/play_music.md
    
  
  
extra:
  footer: ""
