return {
	corcan = {
		buildpic = "CORCAN.DDS",
		buildtime = 11700,
		canmove = true,
		collisionvolumeoffsets = "0 0 -2",
		collisionvolumescales = "32 34 30",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 9300,
		explodeas = "mediumexplosiongeneric",
		footprintx = 2,
		footprintz = 2,
		health = 5400,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.138,
		maxdec = 0.6486,
		maxslope = 14,
		maxwaterdepth = 21,
		metalcost = 560,
		movementclass = "BOT3",
		nochasecategory = "VTOL",
		objectname = "Units/CORCAN.s3o",
		script = "Units/corcan.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 350,
		speed = 37.5,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 0.825,
		turnrate = 1115.5,
		upright = true,
		customparams = {
			model_author = "FireStorm",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "CorBots/T2",
			techlevel = 2,
			unitgroup = "weapon",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0.220962524414 -3.57609763184 -0.162803649902",
				collisionvolumescales = "39.2589111328 21.1636047363 24.3341522217",
				collisionvolumetype = "Box",
				damage = 3500,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 339,
				object = "Units/corcan_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 2500,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 136,
				object = "Units/cor2X2F.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbcormov",
			},
			select = {
				[1] = "kbcorsel",
			},
		},
		weapondefs = {
			canhvylaserroar = {
				areaofeffect = 0,
				impactonly = 1,
				name = "Laserroar",
				noselfdamage = true,
				soundhitdry = "laserroar",
				soundhitdryvolume = 16,
				weapontype = "Cannon",
				customparams = {
					noexplosionlight = 1,
				},
				damage = {
					default = 0,
				},
			},
			cor_canlaser = {
				areaofeffect = 8,
				avoidfeature = false,
				beamtime = 0.16,
				beamttl = 2.4,
				corethickness = 0.21,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				energypershot = 45,
				explosiongenerator = "custom:laserhit-medium-green",
				firestarter = 90,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 5.5,
				name = "HighEnergyLaser",
				noselfdamage = true,
				range = 275,
				reloadtime = 0.8,
				rgbcolor = "0.027 0.40 0.027",
				rgbcolor2 = "0.9 1 0.9",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "lasrhvy3",
				soundtrigger = 1,
				thickness = 4,
				tolerance = 10000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 700,
				damage = {
					default = 275,
					vtol = 25,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "COR_CANLASER",
				onlytargetcategory = "NOTSUB",
			},
			[2] = {
				def = "CANHVYLASERROAR",
			},
		},
	},
}
