return {
	corhack = {
		builddistance = 136,
		builder = true,
		buildpic = "CORFAST.DDS",
		buildtime = 6500,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "22 47 19",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 3800,
		energymake = 15,
		energystorage = 100,
		explodeas = "smallbuilder",
		footprintx = 2,
		footprintz = 2,
		health = 830,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.23,
		maxdec = 1.725,
		maxslope = 17,
		maxwaterdepth = 22,
		metalcost = 210,
		movementclass = "BOT3",
		objectname = "Units/CORFAST.s3o",
		script = "Units/CORFAST.cob",
		seismicsignature = 0,
		selfdestructas = "smallbuilderSelfd",
		sightdistance = 520,
		speed = 90,
		terraformspeed = 750,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.98,
		turnrate = 1391.5,
		upright = true,
		workertime = 125,
		buildoptions = {
			[1] = "coradvsol",
			[2] = "corexp",
			[3] = "cormaw",
			[4] = "corhllt",
			[5] = "corpun",
			[6] = "cormadsam",
			[7] = "corerad",
			[8] = "corjuno",
			[9] = "corfus",
			[10] = "corarad",
			[11] = "corshroud",
			[12] = "corsd",
			[13] = "corlab",
			[14] = "corhalab",
			[15] = "coralab",
			[16] = "cormkr"
		},
		customparams = {
			model_author = "Beherith",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "CorBots/T2",
			techlevel = 2,
			unitgroup = "buildert2",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "2.70434570313 -0.526537158203 -1.280418396",
				collisionvolumescales = "37.4086914063 20.6713256836 39.1832122803",
				collisionvolumetype = "Box",
				damage = 600,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 125,
				object = "Units/corfast_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 500,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 50,
				object = "Units/cor2X2D.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2-builder",
				[2] = "deathceg3-builder",
				[3] = "deathceg4-builder",
			},
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			capture = "capture2",
			repair = "repair2",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbcormov",
			},
			select = {
				[1] = "kbcorsel",
			},
		},
	},
}
