return {
	armfatf = {
		activatewhenbuilt = true,
		buildangle = 16400,
		buildpic = "ARMFATF.DDS",
		buildtime = 9880,
		canrepeat = false,
		collisionvolumeoffsets = "0 -10 0",
		collisionvolumescales = "52 44 52",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 7300,
		energyupkeep = 150,
		explodeas = "largeBuildingExplosionGeneric",
		footprintx = 4,
		footprintz = 4,
		health = 1610,
		idleautoheal = 5,
		idletime = 1800,
		istargetingupgrade = true,
		maxacc = 0,
		maxdec = 0,
		maxslope = 10,
		metalcost = 800,
		minwaterdepth = 30,
		objectname = "Units/ARMFATF.s3o",
		onoffable = true,
		script = "Units/ARMFATF.cob",
		seismicsignature = 0,
		selfdestructas = "largeBuildingExplosionGenericSelfd",
		sightdistance = 273,
		waterline = 3,
		yardmap = "wwwwwwwwwwwwwwww",
		customparams = {
			model_author = "Cremuss",
			normaltex = "unittextures/Arm_normal.dds",
			removestop = true,
			removewait = true,
			subfolder = "ArmBuildings/SeaUtil",
			techlevel = 2,
			unitgroup = "util",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "1.36531829834 -6.85653535156 1.18824005127",
				collisionvolumescales = "59.4412994385 29.0925292969 58.6490936279",
				collisionvolumetype = "Box",
				damage = 871,
				featuredead = "HEAP",
				footprintx = 4,
				footprintz = 4,
				height = 20,
				metal = 467,
				object = "Units/armfatf_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "85.0 14.0 6.0",
				collisionvolumetype = "cylY",
				damage = 436,
				footprintx = 4,
				footprintz = 4,
				height = 4,
				metal = 187,
				object = "Units/arm4X4A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			activate = "cmd-on",
			canceldestruct = "cancel2",
			deactivate = "cmd-off",
			underattack = "warning1",
			working = "cmd-on",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "targsel1",
			},
		},
	},
}
