return {
	leganavycruiser = {
		activatewhenbuilt = true,
		buildangle = 16384,
		buildpic = "CORCRUS.DDS",
		buildtime = 17000,
		canmove = true,
		collisionvolumeoffsets = "0 -14 0",
		collisionvolumescales = "34 34 115",
		collisionvolumetype = "box",
		corpse = "DEAD",
		energycost = 12000,
		explodeas = "largeexplosiongeneric",
		floater = true,
		footprintx = 5,
		footprintz = 5,
		health = 6200,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.02649,
		maxdec = 0.02649,
		metalcost = 1000,
		minwaterdepth = 30,
		movementclass = "BOAT5",
		nochasecategory = "VTOL",
		objectname = "Units/leganavycruiser.s3o",
		script = "Units/leganavycruiser.cob",
		seismicsignature = 0,
		selfdestructas = "largeexplosiongenericSelfd",
		sightdistance = 600,
		sonardistance = 375,
		speed = 54,
		turninplace = true,
		turninplaceanglelimit = 90,
		turnrate = 265.5,
		waterline = 0,
		customparams = {
			model_author = "ZephyrSkies",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/Ships/T2",
			techlevel = 2,
			unitgroup = "weaponsub",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "0.0 2.11181640619e-05 7.62939453125e-06",
				collisionvolumescales = "44.054901123 24.9370422363 110.273605347",
				collisionvolumetype = "Box",
				damage = 5578,
				featuredead = "HEAP",
				footprintx = 5,
				footprintz = 5,
				height = 4,
				metal = 500,
				object = "Units/corcrus_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 4032,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 250,
				object = "Units/cor2X2A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:waterwake-medium",
				[2] = "custom:bowsplash-medium",
				[3] = "custom:barrelshot-small",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "shcormov",
			},
			select = {
				[1] = "shcorsel",
			},
		},
		weapondefs = {
			advanced_shotgun = {
				accuracy = 7,
				areaofeffect = 16,
				avoidfeature = false,
				projectiles = 10,
				burnblow = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.015,
				edgeeffectiveness = 0.85,
				explosiongenerator = "custom:plasmahit-sparkonly",
				fallOffRate = 0.2,
				firestarter = 0,
				impulsefactor = 1.5,
				intensity = 0.8,
				name = "Dual Heavy Assault Kinetic Shotgun",
				noselfdamage = true,
				ownerExpAccWeight = 4.0,
				proximitypriority = 10,
				range = 420,
				reloadtime = 1.2,
				rgbcolor = "1 0.95 0.4",
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "kroggie2xs",
				soundstartvolume = 3,
				sprayangle = 1900,
				thickness = 0.6,
				tolerance = 6000,
                firetolerance = 6000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 969,
				damage = {
					default = 50,
					vtol = 25,
				},
			},
			standard_minigun = {
				accuracy = 2,
				areaofeffect = 16,
				avoidfeature = false,
				burst = 6,
				burstrate = 0.066,
				burnblow = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.038,
				edgeeffectiveness = 0.85,
				explosiongenerator = "custom:plasmahit-sparkonly",
				fallOffRate = 0.2,
				firestarter = 0,
				impulsefactor = 1.5,
				intensity = 0.8,
				name = "Dual Rotary Machine Guns",
				noselfdamage = true,
				ownerExpAccWeight = 4.0,
				proximitypriority = 1,
				range = 600,
				reloadtime = 0.4,
				rgbcolor = "1 0.95 0.4",
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "mgun6heavy",
				soundstartvolume = 4.5,
				soundtrigger = true,
				sprayangle = 650,
				texture1 = "shot",
				texture2 = "empty",
				thickness = 3.0,
				tolerance = 3000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 1100,
				damage = {
					default = 10,
					vtol = 10,
				},
			},
			mg_guns = {
				accuracy = 7,
				areaofeffect = 32,
				avoidfeature = false,
				burst = 6,
				burstrate = 0.066,
				burnblow = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.07,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:plasmahit-sparkonly",
				fallOffRate = 0.2,
				firestarter = 0,
				impulsefactor = 1.5,
				intensity = 0.8,
				name = "Twin Rapid-fire Machine Guns",
				noselfdamage = true,
				ownerExpAccWeight = 4.0,
				proximitypriority = 1,
				range = 450,
				reloadtime = 0.4,
				rgbcolor = "1 0.95 0.4",
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "mgun12",
				soundstartvolume = 6.0,
				soundtrigger = true,
				sprayangle = 1024,
				texture1 = "shot",
				texture2 = "empty",
				thickness = 4.5,
				tolerance = 16000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 958,
				damage = {
					default = 24,
				},
			},
			advdepthcharge = {
				areaofeffect = 32,
				avoidfeature = false,
				avoidfriendly = false,
				burnblow = true,
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.95,
				explosiongenerator = "custom:genericshellexplosion-medium-uw",
				impulsefactor = 0.123,
				model = "legbasictorpedo.s3o",
				name = "Medium depthcharge launcher",
				noselfdamage = true,
				range = 450,
				reloadtime = 1.8,
				soundhit = "xplodep2",
				soundstart = "torpedo1",
				startvelocity = 150,
				tolerance = 32767,
				tracks = true,
				turnrate = 9800,
				turret = true,
				waterweapon = true,
				weaponacceleration = 25,
				weapontimer = 10,
				weapontype = "TorpedoLauncher",
				weaponvelocity = 225,
				damage = {
					default = 225,
				},
			},
		},
		weapons = {
			[1] = {
				def = "mg_guns",
				onlytargetcategory = "SURFACE",
				burstControlWhenOutOfArc = 2,
			},
			[2] = {
				badtargetcategory = "NOTSUB",
				def = "advdepthcharge",
				maindir = "0 0 1",
				maxangledif = 300,
				onlytargetcategory = "CANBEUW UNDERWATER",
			},
			-- [3] = {
			-- 	def = "ADVDEPTHCHARGE",
			-- 	onlytargetcategory = "CANBEUW UNDERWATER",
			-- },
		},
	},
}
