return {
	armanac = {
		buildpic = "ARMANAC.DDS",
		buildtime = 3000,
		canmove = true,
		collisionvolumeoffsets = "0 -2 0",
		collisionvolumescales = "40 19 40",
		collisionvolumetype = "Cyly",
		corpse = "DEAD",
		energycost = 2400,
		explodeas = "mediumexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		health = 1530,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.05333,
		maxdec = 0.05333,
		maxslope = 16,
		maxwaterdepth = 0,
		metalcost = 270,
		movementclass = "HOVER3",
		nochasecategory = "VTOL",
		objectname = "Units/ARMANAC.s3o",
		script = "Units/ARMANAC.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 509,
		speed = 69.99,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.6698,
		turnrate = 525,
		usepiececollisionvolumes = 1,
		customparams = {
			model_author = "Beherith",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmHovercraft",
			unitgroup = "weapon",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "0 -2 0",
				collisionvolumescales = "40 19 40",
				collisionvolumetype = "Cyly",
				damage = 826,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				metal = 175,
				object = "Units/armanac_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 413,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 70,
				object = "Units/arm3X3D.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-small",
				[2] = "custom:waterwake-small-hover",
				[3] = "custom:bowsplash-small-hover",
				[4] = "custom:hover-wake-small",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "hovt1canok",
			},
			select = {
				[1] = "hovt1cansel",
			},
		},
		weapondefs = {
			armanac_weapon = {
				areaofeffect = 32,
				avoidfeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-small",
				gravityaffected = "true",
				impulsefactor = 0.123,
				name = "Medium g2g plasma cannon",
				noselfdamage = true,
				range = 370,
				reloadtime = 1.4,
				soundhit = "xplosml3",
				soundhitwet = "splshbig",
				soundstart = "canlite3",
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 260,
				damage = {
					default = 98,
					vtol = 29,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "ARMANAC_WEAPON",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
