return {
	leganavaladvgeo = {
		acceleration = 0,
		activatewhenbuilt = true,
		brakerate = 0,
		buildangle = 0,
		buildcostenergy = 27000,
		buildcostmetal = 1500,
		buildpic = "leganavaladvgeo.DDS",
		buildtime = 32000,
		canrepeat = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "106 60 106",
		collisionvolumetype = "cylY",
		energymake = 1250,
		energystorage = 12000,
		explodeas = "customfusionexplo",
		footprintx = 5,
		footprintz = 5,
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 4150,
		maxslope = 20,
		maxwaterdepth = 99999,
		minwaterdepth = 6,
		objectname = "Units/leganavaladvgeo.s3o",
		script = "Units/leganavaladvgeo.cob",
		seismicsignature = 0,
		selfdestructas = "advgeo",
		sightdistance = 273,
		yardmap = "h cbgybsyybc bsbssbbssb ysbsbssbbg ybsssbsssy sbsbsssbsb bsbsssbsbs ysssbsssby gbbssbsbsy bssbbssbsb cbyysbygbc",
		customparams = {
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 8,
			buildinggrounddecalsizey = 8,
			buildinggrounddecaltype = "decals/corageo_aoplane.dds",
			cvbuildable = true,
			geothermal = 1,
			model_author = "Tharsis, ZephyrSkies",
			normaltex = "unittextures/leg_normal.dds",
			removestop = true,
			removewait = true,
			subfolder = "Legion/SeaEconomy/T2",
			techlevel = 2,
			unitgroup = "energy",
			usebuildinggrounddecal = true,
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:geobubbles",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "geothrm2",
			},
		},
	},
}
