return {
	corstorm = {
		buildpic = "CORSTORM.DDS",
		buildtime = 1950,
		canmove = true,
		collisionvolumeoffsets = "0 0 -2",
		collisionvolumescales = "22 28 22",
		collisionvolumetype = "cylY",
		corpse = "DEAD",
		energycost = 1150,
		explodeas = "smallexplosiongeneric",
		footprintx = 2,
		footprintz = 2,
		health = 740,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.1242,
		maxdec = 0.6486,
		maxslope = 14,
		maxwaterdepth = 21,
		metalcost = 110,
		movementclass = "BOT2",
		movestate = 0,
		nochasecategory = "VTOL",
		objectname = "Units/CORSTORM.s3o",
		script = "Units/CORSTORM.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 344.5,
		speed = 47.7,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.089,
		turnrate = 1268.44995,
		upright = true,
		customparams = {
			model_author = "Mr Bob",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "CorBots",
			unitgroup = "weapon",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "20 18 30",
				collisionvolumetype = "box",
				damage = 402,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 55,
				object = "Units/corstorm_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 251,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 22,
				object = "Units/cor2X2C.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:rocketflare",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg2",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbcormov",
			},
			select = {
				[1] = "kbcorsel",
			},
		},
		weapondefs = {
			cor_bot_rocket = {
				areaofeffect = 48,
				avoidfeature = false,
				castshadow = true,
				cegtag = "missiletrailsmall-simple",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-small",
				firestarter = 70,
				impulsefactor = 0.123,
				intensity = 1,
				metalpershot = 0,
				model = "cormissile2.s3o",
				name = "Rockets",
				noselfdamage = true,
				range = 475,
				reloadtime = 3.8,
				smokecolor = 1,
				smokeperiod = 11,
				smokesize = 3.3,
				smoketime = 28,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "xplosml2",
				soundhitwet = "splshbig",
				soundstart = "rocklit1",
				startvelocity = 190,
				texture1 = "null",
				texture2 = "smoketraildark",
				turret = true,
				weaponacceleration = 120,
				weapontimer = 2,
				weapontype = "MissileLauncher",
				weaponvelocity = 190,
				customparams = {
					overrange_distance = 547,
					projectile_destruction_method = "descend",
				},
				damage = {
					default = 157,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "COR_BOT_ROCKET",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
