return {
	corsonar = {
		activatewhenbuilt = true,
		buildangle = 8192,
		buildpic = "CORSONAR.DDS",
		buildtime = 900,
		canattack = false,
		canrepeat = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "30 33 30",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 450,
		explodeas = "smallBuildingexplosiongeneric-uw",
		footprintx = 2,
		footprintz = 2,
		health = 58,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0,
		maxdec = 0,
		maxslope = 10,
		metalcost = 20,
		minwaterdepth = 10,
		objectname = "Units/CORSONAR.s3o",
		onoffable = false,
		script = "Units/CORSONAR.cob",
		seismicsignature = 0,
		selfdestructas = "smallBuildingExplosionGenericSelfd-uw",
		sightdistance = 485,
		sonardistance = 1200,
		yardmap = "oooo",
		customparams = {
			model_author = "Mr Bob",
			normaltex = "unittextures/cor_normal.dds",
			removestop = true,
			removewait = true,
			subfolder = "CorBuildings/SeaUtil",
			unitgroup = "util",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "-0.230186462402 -5.31005859372e-06 -1.15662384033",
				collisionvolumescales = "32.5395965576 31.6859893799 26.2655792236",
				collisionvolumetype = "Box",
				damage = 31,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 13,
				object = "Units/corsonar_dead.s3o",
				reclaimable = true,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
			},
		},
		sounds = {
			activate = "radar1",
			canceldestruct = "cancel2",
			deactivate = "sonarde2",
			underattack = "warning1",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "sonar2",
			},
		},
	},
}
