return {
	legkark = {
		maxacc = 0.095,
		maxdec = 0.8211,
		energycost = 2600,
		metalcost = 330,
		buildpic = "LEGKARK.DDS",
		buildtime = 4400,
		canmove = true,
		collisionvolumeoffsets = "0 -1 0",
		collisionvolumescales = "30 34 30",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		damagemodifier = 0.5,
		explodeas = "smallExplosionGeneric",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 5,
		idletime = 1800,
		health = 1725,
		maxslope = 17,
		mass = 210, -- Testing: this unit has resistance to impulse 
		speed = 42.0,
		maxwaterdepth = 12,
		movementclass = "BOT2",
		name = "Karkinos",
		nochasecategory = "VTOL",
		objectname = "Units/LEGKARK.s3o",
		script = "Units/LEGKARK.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 400,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 0.99,
		turnrate = 900,
		upright = true,
		customparams = {
			unitgroup = 'weapon',
			model_author = "Tharsis",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/Bots",
			weapon1turretx = 200,
			weapon1turrety = 200,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-3.1 1.1 -1.5",
				collisionvolumescales = "33.3 20.0 35.5",
				collisionvolumetype = "Box",
				damage = 880,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 161,
				object = "Units/legkark_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 490,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 64,
				object = "Units/arm2X2A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-small-impulse",
				[2] = "custom:selfrepair-sparks",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg2",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbarmmov",
			},
			select = {
				[1] = "kbarmsel",
			},
		},
		weapondefs = {
			heat_ray = {
				areaofeffect = 8,
				avoidfeature = false,
				beamtime = 0.5,
				corethickness = 0.23,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:laserhit-small",
				firestarter = 30,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 5,
				leadlimit = 0,
				name = "Light g2g Heat Ray",
				noselfdamage = true,
				range = 360,
				reloadtime = 2,
				rgbcolor = "1 0.55 0",
				rgbcolor2 = "0.9 1.0 0.5",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "heliosfire",
				soundtrigger = 1,
				thickness = 2.0,
				tolerance = 10000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 950,
				damage = {
					default = 160,
					vtol = 25,
				},
			},
			legion_shotgun = {
				accuracy = 7,
				areaofeffect = 16,
				avoidfeature = false,
				projectiles = 5,
				burnblow = false,
				burst = 2,
				burstrate = 0.4,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = nil,
				duration = 0.015,
				edgeeffectiveness = 0.85,
				explosiongenerator = "custom:plasmahit-sparkonly",
				fallOffRate = 0.2,
				firestarter = 0,
				impulsefactor = 2.246,
				intensity = 1.0,
				name = "Dual-Feed Medium Shotgun",
				noselfdamage = true,
				ownerExpAccWeight = 4.0,
				proximitypriority = 1,
				range = 241,
				reloadtime = 2,
				rgbcolor = "1 0.95 0.4",
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "kroggie2xs",
				soundstartvolume = 3,
				sprayangle = 1680,
				texture1 = "shot",
				texture2 = "empty",
				thickness = 2.0,
				tolerance = 6000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 800,
				damage = {
					default = 20,
					vtol = 6,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "HEAT_RAY",
				onlytargetcategory = "NOTSUB",
			},
			[2] = {
				badtargetcategory = "VTOL",
				def = "LEGION_SHOTGUN",
				onlytargetcategory = "SURFACE VTOL",
			},
		},
	},
}
