-- nukedatbewm-roost

return {
  ["nukedatbewm-roost"] = {
    alwaysvisible      = true,
    groundflash = {
      air                = true,
      ground             = true,
	  water				 = true,
	  underwater		 = true,
      alwaysvisible      = true,
      flashalpha         = 0.5,
      flashsize          = 2000,
      ground             = true,
      ttl                = 300,
      water              = true,
      color = {
        [1]  = 1,
        [2]  = 0.69999998807907,
        [3]  = 0.30000001192093,
      },
    },
    poof02 = {
      air                = true,
      ground             = true,
	  water				 = true,
	  underwater		 = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap           = [[0.8 0.6 0 0.01 0.4 0.4 0.4 0.01  0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.5, 0]],
        numparticles       = 128,
        particlelife       = 150,
        particlelifespread = 150,
        particlesize       = 50,
        particlesizespread = 1,
        particlespeed      = 104,
        particlespeedspread = 32,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 1.0,
        texture            = [[bigexplosmoke-chickens]],
        useairlos          = false,
      },
    },
    poof04 = {
      air                = true,
      ground             = true,
	  water				 = true,
	  underwater		 = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap           = [[0.8 0.6 0 0.01 0.4 0.4 0.4 0.01  0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.2, 0]],
        numparticles       = 20,
        particlelife       = 150,
        particlelifespread = 150,
        particlesize       = 50,
        particlesizespread = 1,
        particlespeed      = 20,
        particlespeedspread = 32,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 1.0,
        texture            = [[bigexplosmoke-chickens]],
        useairlos          = false,
      },
    },
    pop1 = {
      air                = true,
      ground             = true,
	  water				 = true,
	  underwater		 = true,
      alwaysvisible      = true,
      class              = [[heatcloud]],
      count              = 2,
      properties = {
        alwaysvisible      = true,
        heat               = 10,
        heatfalloff        = 0.4,
        maxheat            = 10,
        pos                = [[r-10 r10, 0, r-10 r10]],
        size               = 1,
        sizegrowth         = 50,
        speed              = [[0, 0, 0]],
        texture            = [[bigexplosmoke-chickens]],
      },
    },
    pop2 = {
      air                = true,
      ground             = true,
	  water				 = true,
	  underwater		 = true,
      alwaysvisible      = true,
      class              = [[heatcloud]],
      count              = 10,
      properties = {
        alwaysvisible      = true,
        heat               = 10,
        heatfalloff        = 0.6,
        maxheat            = 15,
        pos                = [[r-150 r150, 0, r-300 r150]],
        size               = 1,
        sizegrowth         = 40,
        speed              = [[0, 0, 0]],
        texture            = [[bigexplosmoke-chickens]],
      },
    },
  },

}

