-- AUTO-GENERATED by tools/mapgen/build_archetypes.py from a scan of
-- 202 real BAR maps. Do not edit by hand; re-run the builder instead.
-- Each archetype: weight = share of real maps; ranges are p20..p80 of
-- the maps in that bucket, with gradient mapped to the hilliness slider.
return {
  symmetryWeights = {
    rot90 = 0.036,
    rot180 = 0.709,
    mirrorz = 0.118,
    mirrorx = 0.136,
  },
  sizeWeights = {
    [8] = 0.03,
    [10] = 0.025,
    [12] = 0.119,
    [14] = 0.089,
    [16] = 0.203,
    [18] = 0.069,
    [20] = 0.183,
    [22] = 0.01,
    [24] = 0.173,
    [26] = 0.005,
    [28] = 0.02,
    [30] = 0.025,
    [32] = 0.05,
  },
  archetypes = {
    {
      name = "Open Plains", weight = 0.153, count = 31,
      hilliness = { 0.284, 0.424 }, roughness = { 0.35, 0.7 }, featureScale = { 0.4, 0.7 },
      jaggedness = { 0.35, 0.65 }, waterLevel = { 0, 0.03 }, islandness = { 0, 0.04 },
    },
    {
      name = "Rolling Hills", weight = 0.134, count = 27,
      hilliness = { 0.481, 0.587 }, roughness = { 0.35, 0.7 }, featureScale = { 0.4, 0.7 },
      jaggedness = { 0.35, 0.65 }, waterLevel = { 0, 0.042 }, islandness = { 0, 0.052 },
    },
    {
      name = "Highlands", weight = 0.163, count = 33,
      hilliness = { 0.681, 0.787 }, roughness = { 0.35, 0.7 }, featureScale = { 0.4, 0.7 },
      jaggedness = { 0.35, 0.65 }, waterLevel = { 0, 0.054 }, islandness = { 0, 0.04 },
    },
    {
      name = "Mountain Pass", weight = 0.074, count = 15,
      hilliness = { 0.847, 1 }, roughness = { 0.35, 0.7 }, featureScale = { 0.4, 0.7 },
      jaggedness = { 0.35, 0.65 }, waterLevel = { 0, 0.085 }, islandness = { 0, 0.05 },
    },
    {
      name = "Lakes & Rivers", weight = 0.144, count = 29,
      hilliness = { 0.556, 0.815 }, roughness = { 0.35, 0.7 }, featureScale = { 0.4, 0.7 },
      jaggedness = { 0.35, 0.65 }, waterLevel = { 0.157, 0.427 }, islandness = { 0.069, 0.284 },
    },
    {
      name = "Coastal", weight = 0.173, count = 35,
      hilliness = { 0.56, 1 }, roughness = { 0.35, 0.7 }, featureScale = { 0.4, 0.7 },
      jaggedness = { 0.35, 0.65 }, waterLevel = { 0.265, 0.395 }, islandness = { 0.483, 1 },
    },
    {
      name = "Island Skirmish", weight = 0.158, count = 32,
      hilliness = { 0.508, 1 }, roughness = { 0.35, 0.7 }, featureScale = { 0.4, 0.7 },
      jaggedness = { 0.35, 0.65 }, waterLevel = { 0.437, 0.642 }, islandness = { 0.87, 1 },
    },
  },
}
