return {
	armcomlvl5	= {
		maxacc = 0.18,
		activatewhenbuilt = true,
		autoheal = 5,
		maxdec = 1.125,
		energycost = 26000,
		metalcost = 2700,
		builddistance = 177,
		builder = true,
		buildpic = "ARMCOM.DDS",
		buildtime = 111600,
		cancapture = true,
		cancloak = true,
		canselfrepair = true,
		canmanualfire = true,
		canmove = true,
		capturespeed = 1800,
		category = "ALL WEAPON NOTSUB COMMANDER NOTSHIP NOTAIR NOTHOVER SURFACE CANBEUW EMPABLE",
		cloakcost = 25,
		cloakcostmoving = 250,
		collisionvolumeoffsets = "0 3 0",
		collisionvolumescales = "28 52 28",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energymake = 250,
		energystorage = 500,
		explodeas = "commanderExplosion",
		footprintx = 2,
		footprintz = 2,
		hidedamage = true,
    	holdsteady = true,
		idleautoheal = 20,
		idletime = 900,
		sightemitheight = 40,
		mass = 4900,
		health = 9300,
		maxslope = 20,
		speed = 51,
		maxwaterdepth = 35,
		metalmake = 20,
		metalstorage = 500,
		mincloakdistance = 50,
		movementclass = "COMMANDERBOT",
		nochasecategory = "ALL",
		objectname = "Units/ARMCOM"..(Spring.GetModOptions().xmas and '-XMAS' or '')..".s3o",
		pushresistant = true,
		radardistance = 1200,
		radaremitheight = 40,
		reclaimable = false,
   		releaseheld  = true,
		script = "Units/ARMCOM_lus.lua",
		seismicsignature = 0,
		selfdestructas = "commanderexplosion",
		selfdestructcountdown = 5,
		showplayername = true,
		sightdistance = 600,
		sonardistance = 600,
		stealth = true,
		terraformspeed = 1500,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0.825,
		turnrate = 1148,
		upright = true,
		workertime = 408,
		buildoptions = {
			[1] = "armmex",
			[2] = "armsolar",
			[3] = "armwin",
			[4] = "armadvsol",
			[5] = "armmakr",
			[6] = "armgeo",
			[7] = "armamex",
			[8] = "armtide",
			[9] = "armestor",
			[10] = "armmstor",
			[11] = "armfmkr",
			[12] = "armlab",
			[13] = "armvp",
			[14] = "armap",
			[15] = "armeyes",
			[16] = "armrad",
			[17] = "armmine1",
			[18] = "armmine2",
			[19] = "armmine3",
			[20] = "armdrag",
			[21] = "armjamt",
			[22] = "armclaw",
			[23] = "armllt",
			[24] = "armbeamer",
			[25] = "armhlt",
			[26] = "armtl",
			[27] = "armguard",
			[28] = "armrl",
			[29] = "armferret",
			[30] = "armcir",
			[31] = "armfrock",
			[32] = "armjuno",
			[33] = "armuwgeo",
			[34] = "armuwms",
			[35] = "armuwes",
			[36] = "armdl",
			[37] = "armsy",
			[38] = "armnanotc",
			[39] = "armnanotcplat",
			[40] = "armfdrag",
			[41] = "armfrt",
			[42] = "armfrad",
			-- Experimental:
			[43] = "armhp",
			[44] = "armfhp",
		},
		customparams = {
			unitgroup = 'builder',
			area_mex_def = "armmex",
			iscommander = true,
			--energyconv_capacity = 70,
			--energyconv_efficiency = 1/70,
			model_author = "FireStorm",
			normaltex = "unittextures/Arm_normal.dds",
			paralyzemultiplier = 0.025,
			subfolder = "",
			evolution_announcement = "Armada commanders have upgraded to level 6",
			evolution_announcement_size = 18.5,
			evolution_target = "armcomlvl6",
			evolution_condition = "timer",
			evolution_timer = 210,
			combatradius = 500,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "35 12 54",
				collisionvolumetype = "CylY",
				damage = 10000,
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 1250,
				object = "Units/armcom_dead.s3o",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35 12 54",
				collisionvolumetype = "cylY",
				damage = 5000,
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 500,
				object = "Units/arm2X2F.s3o",
				reclaimable = true,
				resurrectable = 0,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:com_sea_laser_bubbles",
				[2] = "custom:barrelshot-medium",
				[3] = "custom:footstep-medium",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg4",
			},
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			capture = "capture1",
			cloak = "kloak1",
			repair = "repair1",
			uncloak = "kloak1un",
			underattack = "warning2",
			unitcomplete = "armcomsel",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "armcom1",
				[2] = "armcom2",
				[3] = "armcom3",
				[4] = "armcom4",
			},
			select = {
				[1] = "armcomsel",
			},
		},
		weapondefs = {
			armcomlaser = {
				areaofeffect = 48,
				avoidfeature = false,
				beamttl = 3.5,
				burst = 1,
				burstrate = 0.03333,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 2,
				edgeeffectiveness = 0.15,
				energypershot = 0,
				explosiongenerator = "custom:genericshellexplosion-large-lightning-thor",
				fallOffRate = 0.5,
				firestarter = 50,
				hardStop = false,
				impactonly = 1,
				impulseboost = 0,
				impulsefactor = 0,
				intensity = 28,
				name = "Heavy Lighting Cannon",
				noselfdamage = true,
				range = 425,
				reloadtime = 5,
				rgbcolor = "1 .5 1",
				soundhit = "lasrfir2",
				soundhitwet = "sizzle",
				soundstart = "lghthvy1",
				soundtrigger = true,
				targetmoveerror = 0,
				thickness = 3,
				turret = true,
				weapontype = "LightningCannon",
				weaponvelocity = 400,
				customparams = {
					spark_ceg = "genericshellexplosion-splash-large-lightning",
					spark_forkdamage = "0.1", --old value = "0.5",
					spark_maxunits = "18", --old value = "12",
					spark_range = "200", --old value = "175",
				},
				damage = {
					default = 6000,
				},
			},
			armcomsealaser = {
				areaofeffect = 48,
				avoidfeature = false,
				beamttl = 3.5,
				burst = 1,
				burstrate = 0.03333,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 2,
				edgeeffectiveness = 0.15,
				energypershot = 0,
				explosiongenerator = "custom:genericshellexplosion-large-lightning-thor",
				fallOffRate = 0.5,
				firestarter = 50,
				hardStop = false,
				impactonly = 1,
				impulseboost = 0,
				impulsefactor = 0,
				intensity = 28,
				name = "Heavy Lighting Cannon",
				noselfdamage = true,
				range = 425,
				reloadtime = 5,
				rgbcolor = "1 .5 1",
				soundhit = "lasrfir2",
				soundhitwet = "sizzle",
				soundstart = "lghthvy1",
				soundtrigger = true,
				targetmoveerror = 0,
				thickness = 3,
				turret = true,
				waterweapon = true,
				weapontype = "LightningCannon",
				weaponvelocity = 400,
				customparams = {
					spark_ceg = "genericshellexplosion-splash-large-lightning",
					spark_forkdamage = "0.1", --old value = "0.5",
					spark_maxunits = "18", --old value = "12",
					spark_range = "200", --old value = "175",
				},
				damage = {
					default = 6000,
				},
			},
			disintegrator = {
				areaofeffect = 36,
				avoidfeature = false,
				avoidfriendly = false,
				avoidground = false,
				bouncerebound = 0,
				cegtag = "dgunprojectile",
				commandfire = true,
				craterboost = 0,
				cratermult = 0.15,
				edgeeffectiveness = 0.15,
				energypershot = 500,
				explosiongenerator = "custom:expldgun",
				firestarter = 100,
				firesubmersed = false,
				groundbounce = true,
				impulseboost = 0,
				impulsefactor = 0,
				name = "Disintegrator",
				noexplode = true,
				noselfdamage = true,
				range = 250,
				reloadtime = 0.9,
				soundhit = "xplomas2",
				soundhitwet = "sizzlexs",
				soundstart = "disigun1",
				soundhitvolume = 36,
				soundstartvolume = 96,
				soundtrigger = true,
				tolerance = 20000,
				turret = true,
				waterweapon = true,
				weapontimer = 4.2,
				weapontype = "DGun",
				weaponvelocity = 300,
				damage = {
					commanders = 0,
					default = 99999,
					scavboss = 1000,
				},
			},
			repulsor1 = {
				avoidfeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				name = "Plasma repulsor",
				range = 50,
				soundhitwet = "sizzle",
				weapontype = "Shield",
				damage = {
					default = 100,
				},
				shield = {
					alpha = 0.25,
					energyupkeep = 0,
					force = 2.5,
					intercepttype = 479,
					power = 1000,
					powerregen = 20,
					powerregenenergy = 0,
					radius = 30,
					repulser = false,
					smart = true,
					startingpower = 1000,
					visible = false,
					visiblehitframes = 0,
					badcolor = {
						[1] = 1,
						[2] = 0.2,
						[3] = 0.2,
						[4] = 0.25,
					},
					goodcolor = {
						[1] = 0.2,
						[2] = 1,
						[3] = 0.2,
						[4] = 0.2,
					},
				},
			},
		},
		weapons = {
			[1] = {
				def = "ARMCOMLASER",
				onlytargetcategory = "NOTSUB",
				fastautoretargeting = true,
			},
			[2] = {
				badtargetcategory = "VTOL",
				def = "ARMCOMSEALASER",
				onlytargetcategory = "NOTAIR"
			},
			[3] = {
				def = "DISINTEGRATOR",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
