return {
	armada_constructionseaplane = {
		maxacc = 0.07,
		blocking = false,
		maxdec = 0.4275,
		energycost = 7800,
		metalcost = 150,
		builddistance = 136,
		builder = true,
		buildpic = "armada_constructionseaplane.DDS",
		buildtime = 12000,
		canfly = true,
		canmove = true,
		cansubmerge = true,
		category = "ALL NOTLAND MOBILE NOTSUB VTOL NOWEAPON NOTSHIP NOTHOVER",
		collide = true,
		cruisealtitude = 50,
		energymake = 20,
		energystorage = 75,
		explodeas = "smallexplosiongeneric-builder",
		footprintx = 2,
		footprintz = 2,
		hoverattack = true,
		idleautoheal = 5,
		idletime = 1800,
		health = 405,
		maxslope = 10,
		speed = 192.0,
		maxwaterdepth = 255,
		objectname = "Units/armada_constructionseaplane.s3o",
		script = "Units/armada_constructionseaplane.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd-builder",
		sightdistance = 364,
		terraformspeed = 300,
		turninplaceanglelimit = 360,
		turnrate = 240,
		workertime = 75,
		buildoptions = {
			[1] = "armada_solarcollector",
			[2] = "armada_advancedsolarcollector",
			[3] = "armada_windturbine",
			[4] = "armada_geothermalpowerplant",
			[5] = "armada_metalstorage",
			[6] = "armada_energystorage",
			[7] = "armada_metalextractor",
			[8] = "armada_twilight",
			[9] = "armada_energyconverter",
			[10] = "armada_botlab",
			[11] = "armada_vehicleplant",
			[12] = "armada_aircraftplant",
			[13] = "armada_hovercraftplatform",
			[14] = "armada_constructionturret",
			[15] = "armada_navalconstructionturret",
			[16] = "armada_beholder",
			[17] = "armada_radartower",
			[18] = "armada_dragonsteeth",
			[19] = "armada_dragonsclaw",
			[20] = "armada_sentry",
			[21] = "armada_beamer",
			[22] = "armada_overwatch",
			[23] = "armada_gauntlet",
			[24] = "armada_nettle",
			[25] = "armada_ferret",
			[26] = "armada_chainsaw",
			[27] = "armada_anemone",
			[28] = "armada_sneakypete",
			[29] = "armada_juno",
			[30] = "armada_navalhovercraftplatform",
			[31] = "armada_shipyard",
			[32] = "armada_amphibiouscomplex",
			[33] = "armada_seaplaneplatform",
			[34] = "armada_tidalgenerator",
			--[35] = "armada_navalmetalextractor",
			[36] = "armada_navalenergyconverter",
			[37] = "armada_navalmetalstorage",
			[38] = "armada_navalenergystorage",
			[39] = "armada_sharksteeth",
			[40] = "armada_navalradarsonar",
			[41] = "armada_manta",
			[42] = "armada_navalnettle",
			[43] = "armada_harpoon",
			[44] = "armada_geothermalpowerplant",
			[45] = "armasp",
			[46] = "armada_airrepairpad",
		},
		customparams = {
			unitgroup = 'builder',
			area_mex_def = "armada_navalmetalextractor",
			model_author = "Flaka",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "armada_seaplanes",
		},
		sfxtypes = {
			crashexplosiongenerators = {
				[1] = "crashing-small",
				[2] = "crashing-small",
				[3] = "crashing-small2",
				[4] = "crashing-small3",
				[5] = "crashing-small3",
			},
			pieceexplosiongenerators = {
				[1] = "airdeathceg2-builder",
				[2] = "airdeathceg3-builder",
				[3] = "airdeathceg4-builder",
			},
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "seapsel1",
			},
		},
	},
}
