return {
	bigbug_death = {
		areaofeffect = 38,
		craterboost = 0,
		cratermult = 0,
		explosiongenerator = "custom:raptorunitexplosion-huge-red",
		impulsefactor = 0.4,
		name = "bigbug_death",
		range = 450,
		reloadtime = 3.6,
		soundhit = "bigbugdie",
		soundhitvolume = 8.5,
		turret = 1,
		weaponvelocity = 250,
		damage = {
			default = 0.001,
		},
	},
	bigbug_death_acid = {
		areaofeffect = 150,
		craterboost = 0,
		cratermult = 0,
		explosiongenerator = "custom:acid-explosion-xl",
		impulsefactor = 0.4,
		name = "bigbug_death",
		range = 450,
		reloadtime = 3.6,
		soundhit = "bigbugdie",
		soundhitvolume = 6.5,
		turret = 1,
		weaponvelocity = 250,
		damage = {
			default = 0,
		},
	},
}
