local Capture = VFS.Include("modules/waves/lib/capture.lua")

describe("wave capture", function()
	local policy = Capture.Policy({})

	it("takes every default from an empty policy, and an override where given", function()
		assert.are.equal(0.99, policy.convertAt)
		assert.are.equal(7, policy.period)
		assert.are.equal(0.5, Capture.Policy({ convertAt = 0.5 }).convertAt)
	end)

	it("tougher units resist, and anger speeds the bite", function()
		local weak = Capture.Rate(policy, 100, 100, 100, 100)
		local tough = Capture.Rate(policy, 10000, 10000, 10000, 100)
		assert.is_true(tough < weak)
		assert.is_true(Capture.Rate(policy, 100, 100, 100, 50) < weak)
	end)

	it("damage makes a unit go much faster, up to the cap", function()
		local whole = Capture.Rate(policy, 5000, 5000, 5000, 100)
		local half = Capture.Rate(policy, 2500, 5000, 5000, 100)
		assert.is_true(half > whole)
		assert.are.equal(policy.maxProgressPerTick, Capture.Rate(policy, 1, 5000, 5000, 100))
	end)

	it("converts at the line and hands the new owner a bar below full", function()
		local converts, level = Capture.Step(policy, 0.5, 0.1)
		assert.is_false(converts)
		assert.are.equal(0.6, level)
		converts, level = Capture.Step(policy, 0.95, 0.1)
		assert.is_true(converts)
		assert.are.equal(0.95, level)
	end)

	it("beats on its own phase and walks a share of the roster per beat", function()
		assert.is_nil(Capture.PassOf(policy, 7))
		local first = Capture.PassOf(policy, 9)
		local second = Capture.PassOf(policy, 16)
		assert.is_not_nil(first)
		assert.are_not.equal(first, second)
		assert.are.equal(first, Capture.PassOf(policy, 9 + 7 * 4))
	end)
end)
