return {
	legmlv = {
		activatewhenbuilt = true,
		builddistance = 96,
		builder = true,
		buildpic = "legmlv.DDS",
		buildtime = 3640,
		canassist = false,
		canmove = true,
		canreclaim = false,
		canrepair = true,
		canrestore = false,
		collisionvolumeoffsets = "0 2 0",
		collisionvolumescales = "19 15 29",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 900,
		explodeas = "smallexplosiongeneric",
		footprintx = 2,
		footprintz = 2,
		health = 210,
		idleautoheal = 5,
		idletime = 1800,
		leavetracks = true,
		mass = 1500,
		maxacc = 0.06681,
		maxdec = 0.1327,
		maxslope = 16,
		maxwaterdepth = 0,
		metalcost = 52,
		movementclass = "TANK2",
		nochasecategory = "VTOL",
		objectname = "Units/legmlv.s3o",
		radardistancejam = 64,
		script = "Units/legmlv.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 450,
		speed = 69,
		stealth = true,
		terraformspeed = 120,
		trackoffset = 12,
		trackstrength = 5,
		tracktype = "corwidetracks",
		trackwidth = 17,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.62228,
		turnrate = 580,
		workertime = 40,
		buildoptions = {
			[1] = "legmine1",
			[2] = "legmine2",
			[3] = "legmine3",
			[4] = "legdrag",
			[5] = "legeyes",
		},
		customparams = {
			minesweeper = 450,
			model_author = "Tharsis",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/Vehicles",
			unitgroup = "builder",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 -1 0",
				collisionvolumescales = "22 10 25",
				collisionvolumetype = "Box",
				damage = 133,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 37,
				object = "Units/legmlv_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 60,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 15,
				object = "Units/cor3X3F.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
			},
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			capture = "capture1",
			repair = "repair2",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vcormove",
			},
			select = {
				[1] = "vcorsel",
			},
		},
		weapondefs = {
			minesweep = {
				areaofeffect = 48,
				avoidfeature = false,
				collidefriendly = false,
				craterareaofeffect = 48,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.4,
				explosiongenerator = "custom:MINESWEEP",
				firetolerance = 3000,
				name = "Seismic charge",
				noselfdamage = true,
				range = 220,
				reloadtime = 3,
				rgbcolor = "0.2 0.6 0.2",
				tolerance = 3000,
				turret = true,
				weapontimer = 0.1,
				weapontype = "Cannon",
				weaponvelocity = 275,
				damage = {
					default = 15,
				},
			},
		},
		weapons = {
			[1] = {
				def = "MINESWEEP",
				onlytargetcategory = "MINE",
			},
		},
	},
}
