return {
	armaap = {
		activatewhenbuilt = true,
		builder = true,
		buildpic = "ARMAAP.DDS",
		buildtime = 20900,
		canmove = true,
		collisionvolumeoffsets = "0 4 0",
		collisionvolumescales = "144 70 144",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 29000,
		energystorage = 200,
		explodeas = "largeBuildingExplosionGeneric",
		footprintx = 9,
		footprintz = 9,
		health = 3750,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0,
		maxdec = 0,
		maxslope = 15,
		maxwaterdepth = 0,
		metalcost = 3200,
		metalstorage = 200,
		objectname = "Units/ARMAAP.s3o",
		radardistance = 1000,
		radaremitheight = 50,
		script = "Units/ARMAAP.cob",
		seismicsignature = 0,
		selfdestructas = "largeBuildingExplosionGenericSelfd",
		sightdistance = 312,
		terraformspeed = 1000,
		workertime = 200,
		yardmap = "ooooooooo ooooooooo ooooooooo ooooooooo ooooooooo ooooooooo ooooooooo ooooooooo ooooooooo",
		buildoptions = {
			[1] = "armaca",
			[2] = "armbrawl",
			[3] = "armpnix",
			[4] = "armlance",
			[5] = "armhawk",
			[6] = "armawac",
			[7] = "armdfly",
			[8] = "armblade",
			[9] = "armstil",
			[10] = "armliche",
		},
		customparams = {
			airfactory = true,
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 12,
			buildinggrounddecalsizey = 12,
			buildinggrounddecaltype = "decals/armaap_aoplane.dds",
			model_author = "Cremuss, Tharsis",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmBuildings/LandFactories",
			techlevel = 2,
			unitgroup = "buildert2",
			usebuildinggrounddecal = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 -17 -23",
				collisionvolumescales = "106 40 48",
				collisionvolumetype = "Box",
				damage = 2016,
				featuredead = "HEAP",
				footprintx = 7,
				footprintz = 6,
				height = 20,
				metal = 1953,
				object = "Units/armaap_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 1008,
				footprintx = 6,
				footprintz = 6,
				height = 4,
				metal = 977,
				object = "Units/arm6X6A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:YellowLight",
				[2] = "custom:radarpulse_t1_slow",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			unitcomplete = "untdone",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "pairactv",
			},
		},
	},
}
