return {
	armhavp = {
		builder = true,
		buildpic = "ARMHAVP.DDS",
		buildtime = 61400,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "180 120 166",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 51000,
		energystorage = 1400,
		explodeas = "hugeBuildingexplosiongeneric",
		footprintx = 12,
		footprintz = 12,
		health = 16000,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0,
		maxdec = 0,
		maxslope = 10,
		maxwaterdepth = 0,
		metalcost = 8000,
		metalstorage = 800,
		objectname = "Units/ARMHAVP.s3o",
		script = "Units/ARMAMSUB.cob",
		seismicsignature = 0,
		selfdestructas = "hugeBuildingExplosionGenericSelfd",
		sightdistance = 273,
		terraformspeed = 3000,
		workertime = 600,
		yardmap = "oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo eeeeeeeeeeee eeeeeeeeeeee eeeeeeeeeeee eeeeeeeeeeee eeeeeeeeeeee eeeeeeeeeeee",
		buildoptions = {
			[1] = "armhacv",
			[2] = "armbull",
			[3] = "armmerl",
			[4] = "armmanni",
			[5] = "armyork",
			[6] = "armseer",
			[7] = "armjam",
			[8] = "armthor",
			[9] = "armlun"
		},
		customparams = {
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 19,
			buildinggrounddecalsizey = 19,
			buildinggrounddecaltype = "decals/armamsub_aoplane.dds",
			model_author = "Cremuss",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmBuildings/LandFactories",
			techlevel = 3,
			unitgroup = "buildert3",
			usebuildinggrounddecal = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "125 75 145",
				collisionvolumetype = "Box",
				damage = 8640,
				featuredead = "HEAP",
				footprintx = 9,
				footprintz = 9,
				height = 20,
				metal = 4807,
				object = "Units/armamsub_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 4320,
				footprintx = 9,
				footprintz = 9,
				height = 4,
				metal = 1923,
				object = "Units/arm7X7D.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			unitcomplete = "untdone",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "pvehactv",
			},
		},
	},
}
