return {
	legamcluster = {
		maxacc = 0.0315,
		maxdec = 0.063,
		energycost = 5300,
		metalcost = 305,
		buildpic = "LEGAMCLUSTER.DDS",
		buildtime = 6500,
		canmove = true,
		category = "ALL TANK MOBILE WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
		collisionvolumeoffsets = "0 0 -2",
		collisionvolumescales = "36 20 38",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		explodeas = "mediumExplosionGeneric",
		footprintx = 3,
		footprintz = 3,
		idleautoheal = 5,
		idletime = 1800,
		leavetracks = true,
		health = 1000,
		maxslope = 12,
		speed = 59,
		maxwaterdepth = 0,
		movementclass = "TANK3",
		movestate = 0,
		nochasecategory = "VTOL",
		objectname = "Units/LEGAMCLUSTER.s3o",
		script = "Units/LEGAMCLUSTER.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 300,
		trackoffset = -8,
		trackstrength = 8,
		tracktype = "armbull_tracks",
		trackwidth = 40,
		turninplace = true,
		--usepiececollisionvolumes = 1,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.15,
		turnrate = 270,
		customparams = {
			unitgroup = 'weapon',
			basename = "base",
			canareaattack = 1,
			firingceg = "barrelshot-medium",
			kickback = "-6",
			model_author = "ZephyrSkies",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/Vehicles",
			techlevel = 2,
			weapon1turretx = 35,
			weapon1turrety = 35,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 -2",
				collisionvolumescales = "36 20 38",
				collisionvolumetype = "Box",
				damage = 500,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				metal = 165,
				object = "Units/armmart_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 400,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 82,
				object = "Units/arm2X2E.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-medium",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "tarmmove",
			},
			select = {
				[1] = "tarmsel",
			},
		},
		weapondefs = {
			arm_artillery = {
				accuracy = 500,
				areaofeffect = 130,
				avoidfeature = false,
				cegtag = "starfire_arty",
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.4,
				explosiongenerator = "custom:ministarfire-explosion",
				gravityaffected = "true",
				impulseboost = 0.123,
				impulsefactor = 0.5,
				name = "Long-range g2g plasma cannon",
				noselfdamage = true,
				range = 770,
				reloadtime = 4.28,
				rgbcolor = "0.7 0.7 1.0 1.0 1.0 1.0 1.0 1.0",
				soundhit = "xplomed4",
				soundhitwet = "splsmed",
				soundstart = "cannhvy2",
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 355.28159,
				customparams = {
					cluster = true,
					bouncing = true,
					number = 3,
				},
				damage = {
					default = 130,
					subs = 34,
					vtol = 22,
				},
			},
			cluster_munition = {
				areaofeffect = 130,
				avoidfeature = false,
				cegtag = "ministarfire",
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.3,
				explosiongenerator = "custom:ministarfire-explosion",
				gravityaffected = "true",
				impulseboost = 0.123,
				impulsefactor = 0.5,
				name = "Cluster Munitions",
				noselfdamage = true,
				range = 180,
				rgbcolor = "0.7 0.7 1.0 1.0 1.0 1.0 1.0 1.0",
				soundhit = "xplomed4",
				soundhitwet = "splsmed",
				soundstart = "cannhvy2",
				weapontype = "Cannon",
				weaponvelocity = 450,
				damage = {
					default = 87,
					lboats = 87,
					subs = 20,
					vtol = 20,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "NOTLAND",
				def = "ARM_ARTILLERY",
				maindir = "0 0 1",
				maxangledif = 180,
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
