return {
	legaskirmtank = {
		maxacc = 0.05,
		maxdec = 0.1,
		energycost = 6800,
		metalcost = 450,
		buildpic = "LEGASKIRMTANK.DDS",
		buildtime = 8000,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "30 30 34", ---not respected used collisionvolumes.lua
		collisionvolumetype = "BOX",
		corpse = "DEAD",
		explodeas = "largeexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		idleautoheal = 5,
		idletime = 1800,
		leavetracks = true,
		health = 2500,--3900,
		maxslope = 12,
		speed = 65,--90,
		maxwaterdepth = 15,
		movementclass = "MTANK3",
		nochasecategory = "VTOL",
		objectname = "Units/LEGASKIRMTANK.s3o",
		script = "Units/LEGASKIRMTANK_clean.cob",
		seismicsignature = 0,
		selfdestructas = "largeExplosionGenericSelfd",
		sightdistance = 440,
		trackoffset = 4,
		trackstrength = 10,
		tracktype = "armbull_tracks",
		trackwidth = 44,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.72656,
		turnrate = 450,
		customparams = {
			unitgroup = 'weapon',
			basename = "base",
			firingceg = "barrelshot-medium",
			kickback = "-2.4",
			model_author = "ZephyrSkies",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/Vehicles/T2 Vehicles",
			techlevel = 2,
			weapon1turretx = 65,
			weapon1turrety = 105,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-0.291641235352 0.00484669189453 0.383178710938",
				collisionvolumescales = "43.0491943359 23.8300933838 46.0147399902",
				collisionvolumetype = "Box",
				damage = 3000,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				metal = 225,
				object = "Units/legaskirmtank_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 2000,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 105,
				object = "Units/arm3X3F.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-medium",
				[2] = "custom:dust_cloud_dirt_light",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "tarmmove",
			},
			select = {
				[1] = "tarmsel",
			},
		},
		weapondefs = {
			legmgplasma = {
				burstrate = 0.2,
				burst = 3,
				sprayangle = 600,
                --accuracy = 100,
				areaofeffect = 64,
				avoidfeature = false,
				burnblow = true,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-small-t2",
				firestarter = 100,
				fireTolerance = 7000,
				tolerance = 7000,
				gravityaffected = "true",
				predictboost = 0.5,
				impulsefactor = 0.123,
				name = "Heavy Rotary Plasma Cannon",
				noselfdamage = true,
				range = 600,
				reloadtime = 2,
				size = 2,
				soundhit = "xplosml3",
				soundhitwet = "splshbig",
				soundstart = "corraid",
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 360,
				damage = {
					default = 70,
					vtol = 20,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "LEGMGPLASMA",
				onlytargetcategory = "SURFACE",
				fastautoretargeting = true,
				burstControlWhenOutOfArc = 2,
			},
			-- [2] = {
			-- 	badtargetcategory = "VTOL",
			-- 	def = "HEATRAY",
			-- 	maindir = "-1 0 1",
			-- 	maxangledif = 270,
			-- 	onlytargetcategory = "SURFACE",
			-- },
			-- [3] = {
			-- 	badtargetcategory = "VTOL",
			-- 	def = "HEATRAY",
			-- 	maindir = "1 0 1",
			-- 	maxangledif = 270,
			-- 	onlytargetcategory = "SURFACE",
			-- },
		},
	},
}
