return {
	legvflak = {
		airsightdistance = 900,
		buildpic = "legvflak.DDS",
		buildtime = 15130,
		canmove = true,
		collisionvolumeoffsets = "0 -2 0",
		collisionvolumescales = "32 22 50",
		collisionvolumetype = "BOX",
		corpse = "DEAD",
		energycost = 10500,
		explodeas = "mediumExplosionGeneric",
		footprintx = 3,
		footprintz = 3,
		health = 2700,
		leavetracks = true,
		maxacc = 0.05823,
		maxdec = 0.11647,
		maxslope = 14,
		maxwaterdepth = 12,
		metalcost = 470,
		movementclass = "TANK3",
		movestate = 0,
		nochasecategory = "NOTAIR",
		objectname = "Units/legvflak.s3o",
		script = "Units/legvflak.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 338,
		speed = 70,
		trackoffset = -5,
		trackstrength = 5,
		tracktype = "armcroc_tracks",
		trackwidth = 41,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.6335,
		turnrate = 591.79999,
		customparams = {
			model_author = "Tharsis",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/Vehicles/T2 Vehicles",
			techlevel = 2,
			unitgroup = "aa",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0.2 -7 1.5",
				collisionvolumescales = "32.4 21.8 34.3",
				collisionvolumetype = "Box",
				damage = 2000,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 288,
				object = "Units/legvflak_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 1500,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 115,
				object = "Units/cor2X2A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-flak",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "tcormove",
			},
			select = {
				[1] = "tcorsel",
			},
		},
		weapondefs = {
			leg_t2_microflak_mobile = {
				accuracy = 1000,
				areaofeffect = 35,
                burst = 3,
				burstrate = 0.02,
				avoidfeature = false,
				burnblow = true,
				canattackground = false,
				cegtag = "flaktrailaamg",
				craterareaofeffect = 35,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = 1,
				collidefriendly = false,
				edgeeffectiveness = 1,
				explosiongenerator = "custom:flakshard",
				gravityaffected = "true",
				impulsefactor = 0,
				name = "Dual Rotary Microflak Cannons",
				noselfdamage = true,
				range = 800,
				reloadtime = 0.166,
				size = 0,
				sizedecay = 0.08,
				soundhit = "flakhit",
				soundhitwet = "splsmed",
				soundstart = "flakfire",
				stages = 0,
				turret = true,
				weapontimer = 1,
				weapontype = "Cannon",
				weaponvelocity = 1900,
				damage = {
					vtol = 40,
				},
				rgbcolor = {
					[1] = 1,
					[2] = 0.33,
					[3] = 0.7,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "LIGHTAIRSCOUT",
				burstcontrolwhenoutofarc = 2,
				def = "leg_t2_microflak_mobile",
				fastautoretargeting = true,
				onlytargetcategory = "VTOL",
			},
		},
	},
}
