return {
	armada_advancedconstructionaircraft = {
		maxacc = 0.07,
		blocking = false,
		maxdec = 0.4275,
		energycost = 12000,
		metalcost = 340,
		builddistance = 136,
		builder = true,
		buildpic = "armada_advancedconstructionaircraft.DDS",
		buildtime = 17750,
		canfly = true,
		canmove = true,
		category = "ALL NOTLAND MOBILE NOTSUB VTOL NOWEAPON NOTSHIP NOTHOVER",
		collide = true,
		cruisealtitude = 80,
		energystorage = 50,
		energymake = 10,
		explodeas = "smallExplosionGeneric-builder",
		footprintx = 2,
		footprintz = 2,
		hoverattack = true,
		idleautoheal = 5,
		idletime = 1800,
		health = 200,
		maxslope = 10,
		speed = 192.0,
		maxwaterdepth = 0,
		objectname = "Units/armada_advancedconstructionaircraft.s3o",
		radardistance = 50,
		script = "Units/armada_advancedconstructionaircraft.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd-builder",
		sightdistance = 383.5,
		terraformspeed = 650,
		turninplaceanglelimit = 360,
		turnrate = 240,
		workertime = 100,
		buildoptions = {
			"armada_fusionreactor",
			"armada_advancedfusionreactor",
			"armada_cloakablefusionreactor",
			"armada_advancedgeothermalpowerplant",
			"armada_advancedgeothermalpowerplant",
			"armada_prude",
			"armada_advancedmetalextractor",
			"armada_advancedenergyconverter",
			"armada_hardenedenergystorage",
			"armada_hardenedmetalstorage",
			"armada_advancedradartower",
			"armada_veil",
			"armada_fortificationwall",
			"armada_airrepairpad",
			"armada_airrepairpad",
			"armada_pinpointer",
			"armada_tracer",
			"armada_keeper",
			"armada_rattlesnake",
			"armada_pitbull",
			"armada_pulsar",
			"armada_arbalest",
			"armada_mercury",
			"armada_paralyzer",
			"armada_citadel",
			"armada_armageddon",
			"armada_basilica",
			"armada_ragnarok",
			"armada_decoyfusionreactor",
			"armada_aircraftplant",
			"armada_advancedaircraftplant",
			"armada_seaplaneplatform",
			"armada_experimentalgantry",
		},
		customparams = {
			unitgroup = 'buildert2',
			area_mex_def = "armada_advancedmetalextractor",
			model_author = "FireStorm",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "armada_aircraft/t2",
			techlevel = 2,
		},
		sfxtypes = {
			crashexplosiongenerators = {
				[1] = "crashing-small",
				[2] = "crashing-small",
				[3] = "crashing-small2",
				[4] = "crashing-small3",
				[5] = "crashing-small3",
			},
			pieceexplosiongenerators = {
				[1] = "airdeathceg3-builder",
				[2] = "airdeathceg4-builder",
				[3] = "airdeathceg2-builder",
			},
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolarmv",
			},
			select = {
				[1] = "vtolarac",
			},
		},
	},
}
