return {
	corfhp = {
		builder = true,
		buildpic = "CORFHP.DDS",
		buildtime = 11000,
		canmove = true,
		collisionvolumeoffsets = "0 5 0",
		collisionvolumescales = "96 32 96",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 3000,
		energystorage = 200,
		explodeas = "largeBuildingexplosiongeneric",
		footprintx = 6,
		footprintz = 6,
		health = 3750,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0,
		maxdec = 0,
		metalcost = 900,
		metalstorage = 200,
		minwaterdepth = 5,
		objectname = "Units/CORFHP.s3o",
		script = "Units/CORFHP.cob",
		seismicsignature = 0,
		selfdestructas = "largeBuildingExplosionGenericSelfd",
		sightdistance = 312,
		terraformspeed = 1000,
		waterline = 4,
		workertime = 100,
		yardmap = "weeeew weeeew weeeew weeeew weeeew weeeew",
		buildoptions = {
			[1] = "corch",
			[2] = "corsh",
			[3] = "corsnap",
			[4] = "corah",
			[5] = "cormh",
			[6] = "corhal",
		},
		customparams = {
			model_author = "Mr Bob",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "CorBuildings/SeaFactories",
			unitgroup = "builder",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "120 26 108",
				collisionvolumetype = "Box",
				damage = 2014,
				footprintx = 8,
				footprintz = 7,
				height = 20,
				metal = 715,
				object = "Units/corfhp_dead.s3o",
				reclaimable = true,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			build = "hoverok2",
			canceldestruct = "cancel2",
			underattack = "warning1",
			unitcomplete = "untdone",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "hoversl2",
			},
		},
	},
}
