return {
	corplat = {
		activatewhenbuilt = true,
		builder = true,
		buildpic = "CORPLAT.DDS",
		buildtime = 11800,
		canmove = true,
		category = "SURFACE UNDERWATER",
		corpse = "DEAD",
		energycost = 5500,
		energystorage = 200,
		explodeas = "largeBuildingexplosiongeneric",
		footprintx = 6,
		footprintz = 6,
		health = 2200,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0,
		maxdec = 0,
		metalcost = 1400,
		minwaterdepth = 30,
		objectname = "Units/CORPLAT.s3o",
		script = "Units/CORPLAT.cob",
		seismicsignature = 0,
		selfdestructas = "largeBuildingExplosionGenericSelfd",
		sightdistance = 169,
		sonardistance = 800,
		terraformspeed = 1000,
		waterline = 43,
		workertime = 200,
		yardmap = "wwwwww weeeew weeeew weeeew weeeew wwwwww",
		buildoptions = {
			[1] = "corcsa",
			[2] = "corcut",
			[3] = "corsb",
			[4] = "corseap",
			[5] = "corsfig",
			[6] = "corhunt",
		},
		customparams = {
			airfactory = true,
			model_author = "Mr Bob",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "CorBuildings/SeaFactories",
			unitgroup = "builder",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "2.5 0.0 -0.0",
				collisionvolumescales = "117.5 41.25 112.5",
				collisionvolumetype = "Box",
				damage = 1200,
				footprintx = 7,
				footprintz = 7,
				height = 20,
				metal = 930,
				object = "Units/corplat_dead.s3o",
				reclaimable = true,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			build = "seaplok2",
			canceldestruct = "cancel2",
			underattack = "warning1",
			unitcomplete = "untdone",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "seaplsl2",
			},
		},
	},
}
