return {
	legbunk = {
		maxacc = 0.253,
		maxdec = 0.8211,
		energycost = 30000,
		metalcost = 1800,
		buildpic = "ARMRAZ.DDS",
		buildtime = 26100,
		canmove = true,
		category = "BOT MOBILE WEAPON ALL NOTSUB NOTAIR NOTHOVER SURFACE EMPABLE",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "55 80 55",
		collisionvolumetype = "CYLY",
		corpse = "DEAD",
		explodeas = "explosiont3",
		footprintx = 3,
		footprintz = 3,
		idleautoheal = 5,
		idletime = 1800,
		mass = 200000,
		health = 10000,
		maxslope = 15,
		speed = 82.0,
		maxwaterdepth = 22,
		movementclass = "HBOT4",
		objectname = "Units/legbunk.s3o",
		script = "Units/legbunk.cob",
		seismicsignature = 0,
		selfdestructas = "explosiont3xl",
		sightdistance = 450,
		strafetoattack = true,
		turninplace = true,
		turninplaceanglelimit = 135,
		turninplacespeedlimit = 1.8,
		turnrate = 768.20001,
		upright = true,
		customparams = {
			unitgroup = 'weapon',
			model_author = "Johanthan Crimson",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "leggantry",
			maxrange = "40",
			techlevel = 3,
			weapon1turretx = 200,
			weapon1turrety = 200,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "61.6002807617 54.8114776611 71.5794219971",
				collisionvolumetype = "Box",
				damage = 1500,
				featuredead = "HEAP",
				footprintx = 4,
				footprintz = 4,
				height = 20,
				metal = 2325,
				object = "Units/arm3X3B.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 2000,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 930,
				object = "Units/arm3X3B.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "mavbok1",
			},
			select = {
				[1] = "mavbsel1",
			},
		},
		weapondefs = {
			piledriver = {
				areaofeffect = 65,
				avoidfeature = false,
				bouncerebound = 0,
				cegtag = "gausscannonprojectile",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:burnblackbig",
				firestarter = 100,
				firesubmersed = true,
				gravityaffected = false,
				impulseboost = 10,
				impulsefactor = 1,
				intensity = 4,
				name = "AP CQC Piledriver",
				noexplode = true,
				noselfdamage = true,
				range = 150,
				reloadtime = 4,
				rgbcolor = "1 0.8 0.17",
				size = 0,
				soundhit = "xplomed2",
				soundhitwet = "sizzlexs",
				soundstart = "packolau",
				soundhitvolume = 32,
				soundtrigger = true,
				turret = true,
				waterweapon = true,
				weapontype = "Cannon",
				weaponvelocity = 2000,
				damage = {
					default = 2000,},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "GROUNDSCOUT",
				def = "PILEDRIVER",
				onlytargetcategory = "SURFACE",
				fastautoretargeting = true,
			},
		},
	},
}
