return {
	legelrpcmech = {
		activatewhenbuilt = false,
		buildpic = "LEGELRPCMECH.DDS",
		buildtime = 125000,
		canmove = true,
		cantbetransported = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "110 70 110",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 150000,
		explodeas = "explosiont3",
		footprintx = 7,
		footprintz = 7,
		health = 17000,
		idleautoheal = 5,
		idletime = 1800,
		mass = 4300,
		maxacc = 0.02645,
		maxdec = 0.345,
		maxslope = 17,
		maxwaterdepth = 0,
		metalcost = 11000,
		movementclass = "HBOT7",
		movestate = 0,
		nochasecategory = "VTOL",
		objectname = "Units/LEGELRPCMECH.s3o",
		script = "Units/LEGELRPCMECH.cob",
		seismicsignature = 0,
		selfdestructas = "explosiont3xl",
		sightdistance = 625,
		speed = 25,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 0.726,
		turnrate = 265.64999,
		customparams = {
			model_author = "ZephyrSkies (Model), Phill-Art (Concept Art)",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/T3",
			techlevel = 3,
			unitgroup = "weapon",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "130 60 100",
				collisionvolumetype = "Box",
				damage = 8500,
				featuredead = "HEAP",
				footprintx = 6,
				footprintz = 6,
				height = 20,
				metal = 5500,
				object = "Units/legelrpcmech_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "85.0 14.0 6.0",
				collisionvolumetype = "cylY",
				damage = 4250,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 2250,
				object = "Units/arm4X4D.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-huge",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbarmmov",
			},
			select = {
				[1] = "kbarmsel",
			},
		},
		weapondefs = {
			shocker_high = {
				accuracy = 300,
				sprayangle = 300,
				areaofeffect = 150,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "starfire-small",
				collidefriendly = false,
				craterareaofeffect = 116,
				craterboost = 0.1,
				cratermult = 0.1,
				burst = 4,
				burstrate = 0.06,
				edgeeffectiveness = 0.15,
				energypershot = 5000,
				explosiongenerator = "custom:starfire-explosion",
				gravityaffected = "true",
				heightboostfactor = 8,
				impulsefactor = 0.5,
				leadbonus = 0,
				model = "legbomb.s3o",
				name = "Long-Range g2g Heavy Cluster Plasma Cannon",
				noselfdamage = true,
				range = 3100,
				reloadtime = 12,
				soundhit = "lrpcexplo",
				soundhitwet = "splshbig",
				soundstart = "lrpcshot3",
				soundhitvolume = 38,
				soundstartvolume = 24,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 1000,
				customparams = {
					cluster_def = 'cluster_munition',
					cluster_number = 4,
				},
				damage = {
					default = 500,
					shields = 250,
					subs = 100,
				},
			},
			cluster_munition = {
				areaofeffect = 100,
				avoidfeature = false,
				cegtag = "ministarfire",
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.3,
				explosiongenerator = "custom:ministarfire-explosion",
				gravityaffected = "true",
				impulsefactor = 0.5,
				name = "Plasma Burst",
				noselfdamage = true,
				maxvelocity = 720,
				range = 160,
				rgbcolor = "0.7 0.7 1.0",
				soundhit = "xplomed2",
				soundhitwet = "splsmed",
				soundstart = "cannhvy5",
				weapontype = "Cannon",
				reloadtime = 11,
				damage = {
					default = 100,
					lboats = 200,
					subs = 50,
					vtol = 50,
				},
			},
			shocker_low = {
				accuracy = 300,
				sprayangle = 300,
				areaofeffect = 150,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "starfire-small",
				collidefriendly = false,
				craterareaofeffect = 116,
				craterboost = 0.1,
				cratermult = 0.1,
				burst = 4,
				burstrate = 0.06,
				edgeeffectiveness = 0.15,
				energypershot = 6000,
				explosiongenerator = "custom:starfire-explosion",
				gravityaffected = "true",
				heightboostfactor = 8,
				impulsefactor = 0.5,
				leadbonus = 0,
				model = "legbomb.s3o",
				name = "Long-Range g2g Heavy Cluster Plasma Cannon",
				noselfdamage = true,
				range = 3100,
				reloadtime = 12,
				soundhit = "lrpcexplo",
				soundhitwet = "splshbig",
				soundstart = "lrpcshot3",
				soundhitvolume = 38,
				soundstartvolume = 24,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 1000,
				customparams = {
					cluster_def = 'cluster_munition',
					cluster_number = 4,
				},
				damage = {
					default = 500,
					shields = 250,
					subs = 100,
				},
			},
			-- smart_trajectory_dummy = {
			-- 	areaofeffect = 192,
			-- 	avoidfeature = false,
			-- 	avoidfriendly = true,
			-- 	avoidneutral = true,
			-- 	cegtag = "arty-huge",
			-- 	collidefriendly = false,
			-- 	craterareaofeffect = 192,
			-- 	craterboost = 0,
			-- 	cratermult = 0,
			-- 	edgeeffectiveness = 0.65,
			-- 	explosiongenerator = "custom:genericshellexplosion-huge",
			-- 	firetolerance = 5000,
			-- 	gravityaffected = "true",
			-- 	heightboostfactor = 2.8,
			-- 	impulsefactor = 0.5,
			-- 	name = "Smart Trajectory System",
			-- 	noselfdamage = true,
			-- 	predictboost = 0.25,
			-- 	range = 1450,
			-- 	reloadtime = 8,
			-- 	soundhit = "xplomed2",
			-- 	soundhitwet = "splslrg",
			-- 	soundstart = "cannhvy5",
			-- 	targetborder = 1,
			-- 	turret = true,
			-- 	weapontype = "Cannon",
			-- 	weaponvelocity = 500,
			-- 	damage = {
			-- 		default = 0,
			-- 	},
			-- 	customparams = {
			-- 		exclude_preaim = true,
			-- 		smart_trajectory_checker = true,
			-- 	}
			-- },
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL GROUNDSCOUT",
				def = "SHOCKER_LOW",
				-- maindir = "0 0 1",
				-- maxangledif = 180,
				onlytargetcategory = "SURFACE",
			},
			-- [2] = {
			-- 	badtargetcategory = "VTOL GROUNDSCOUT",
			-- 	def = "SHOCKER_HIGH",
			-- 	-- maindir = "0 0 1",
			-- 	-- maxangledif = 180,
			-- 	onlytargetcategory = "SURFACE",
			-- },
			-- [3] = {
			-- 	badtargetcategory = "VTOL GROUNDSCOUT",
			-- 	def = "smart_trajectory_dummy",
			-- 	onlytargetcategory = "SURFACE",
			-- },
		},
	},
}
