return {
	legjav = {
		buildpic = "legjav.DDS",
		buildtime = 32000,
		canmove = true,
		cantbetransported = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "50 72 50",
		collisionvolumetype = "CYLY",
		corpse = "DEAD",
		energycost = 21000,
		explodeas = "explosiont3med",
		footprintx = 5,
		footprintz = 5,
		health = 7200,
		idleautoheal = 16,
		idletime = 1800,
		mass = 1200,
		maxacc = 0.1750,
		maxdec = 0.7500,
		maxslope = 17,
		maxwaterdepth = 32,
		metalcost = 1200,
		movementclass = "HABOT5",
		nochasecategory = "VTOL",
		objectname = "Units/legjav.s3o",
		script = "Units/legjav.cob",
		seismicsignature = 0,
		selfdestructas = "explosiont3",
		sightdistance = 455,
		speed = 65.0,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.98,
		turnrate = 600,
		upright = true,
		customparams = {
			maxrange = "450",
			model_author = "Tharsis",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/T3",
			techlevel = 3,
			unitgroup = "weapon",
			weapon1turretx = 90,
			weapon1turrety = 150,
			continuous_aim_time = 0.02,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 -2 0",
				collisionvolumescales = "54 24 54",
				collisionvolumetype = "Box",
				damage = 2400,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				metal = 860,
				object = "Units/legjav_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "40 40 40",
				collisionvolumetype = "Sphere",
				damage = 1200,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 280,
				object = "Units/arm3X3F.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-tiny",
				[2] = "custom:subbubbles",
				[3] = "custom:footstep-medium",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "mavbok1",
			},
			select = {
				[1] = "mavbsel1",
			},
		},
		weapondefs = {
			mg_guns = {
				accuracy = 7,
				areaofeffect = 32,
				avoidfeature = false,
				burst = 12,
				burstrate = 0.033,
				burnblow = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.05,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:plasmahit-sparkonly",
				fallOffRate = 0.2,
				firestarter = 0,
				impulsefactor = 1.5,
				intensity = 0.8,
				name = "Twin Rapid-fire Machine Guns",
				noselfdamage = true,
				ownerExpAccWeight = 4.0,
				proximitypriority = 1,
				range = 450,
				reloadtime = 0.4,
				rgbcolor = "1 0.95 0.4",
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "mgun12",
				soundstartvolume = 6.0,
				soundtrigger = true,
				sprayangle = 1024,
				texture1 = "shot",
				texture2 = "empty",
				thickness = 3.0,
				tolerance = 16000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 958,
				damage = {
					default = 12,
				},
			},
			aa_gun = {
				accuracy = 100,
				areaofeffect = 16,
				avoidfeature = false,
				burst = 6,
				burstrate = 0.075,
				burnblow = false,
				canattackground = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.05,
				edgeeffectiveness = 0.85,
				explosiongenerator = "custom:plasmahit-sparkonly",
				fallOffRate = 0.2,
				firestarter = 0,
				firetolerance = 12000,
				impulsefactor = 1.5,
				intensity = 0.8,
				name = "Light AA Rotary Gun",
				noselfdamage = true,
				ownerExpAccWeight = 4.0,
				predictboost = 0.5,
				proximitypriority = 1,
				range = 700,
				reloadtime = 0.4,
				rgbcolor = "1 0.33 0.7",
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "minigun3",
				soundstartvolume = 3,
				sprayangle = 900,
				texture1 = "shot",
				texture2 = "empty",
				thickness = 3.0,
				tolerance = 12000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 950,
				damage = {
					default = 0,
					vtol = 10,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				burstcontrolwhenoutofarc = 2,
				def = "mg_guns",
				fastautoretargeting = true,
				onlytargetcategory = "SURFACE",
			},
			[2] = {
				def = "aa_gun",
				onlytargetcategory = "VTOL",
			},
		},
	},
}
