return {
	armscab = {
		buildpic = "ARMSCAB.DDS",
		buildtime = 40000,
		canattack = false,
		canmove = true,
		collisionvolumeoffsets = "0 3 -1",
		collisionvolumescales = "43 23 49",
		collisionvolumetype = "box",
		corpse = "DEAD",
		damagemodifier = 0.5,
		energycost = 30000,
		explodeas = "largeexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		health = 870,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.03663,
		maxdec = 0.07326,
		maxslope = 10,
		maxwaterdepth = 0,
		metalcost = 1150,
		movementclass = "TBOT3",
		movestate = 0,
		noautofire = true,
		nochasecategory = "ALL",
		objectname = "Units/ARMSCAB.s3o",
		radardistance = 50,
		script = "Units/ARMSCAB.cob",
		seismicsignature = 0,
		selfdestructas = "largeExplosionGenericSelfd",
		sightdistance = 450,
		speed = 51,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.122,
		turnrate = 473,
		customparams = {
			model_author = "FireStorm",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmBots/T2",
			techlevel = 2,
			unitgroup = "antinuke",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0.0 -0.208756103516 6.21000671387",
				collisionvolumescales = "55.2154541016 21.362487793 50.6700134277",
				collisionvolumetype = "Box",
				damage = 600,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				metal = 934,
				object = "Units/armscab_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 500,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 374,
				object = "Units/arm3X3D.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbarmmov",
			},
			select = {
				[1] = "kbarmsel",
			},
		},
		weapondefs = {
			armscab_weapon = {
				areaofeffect = 420,
				avoidfeature = false,
				avoidfriendly = false,
				burnblow = true,
				cegtag = "antimissiletrail",
				collidefriendly = false,
				coverage = 1400,
				craterareaofeffect = 420,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				energypershot = 6500,
				explosiongenerator = "custom:antinuke",
				firestarter = 100,
				flighttime = 20,
				impulsefactor = 0.123,
				interceptor = 1,
				metalpershot = 150,
				model = "fmdmissile.s3o",
				name = "ICBM intercepting missile launcher",
				noselfdamage = true,
				range = 72000,
				reloadtime = 2,
				smokecolor = 0.7,
				smokeperiod = 9,
				smokesize = 27,
				smoketime = 110,
				smoketrail = true,
				smoketrailcastshadow = true,
				soundhit = "xplomed4",
				soundhitwet = "splslrg",
				soundstart = "antinukelaunch",
				stockpile = true,
				stockpiletime = 90,
				texture1 = "bluenovaexplo",
				texture2 = "smoketrailbar",
				texture3 = "null",
				tolerance = 7000,
				tracks = true,
				turnrate = 10000,
				weaponacceleration = 150,
				weapontimer = 2,
				weapontype = "StarburstLauncher",
				weaponvelocity = 7000,
				customparams = {
					stockpilelimit = 20,
				},
				damage = {
					default = 500,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "ALL",
				def = "ARMSCAB_WEAPON",
			},
		},
	},
}
