-- This file has been automatically generated by texture_atlas_builder.ipynb
-- Do not edit this file!
-- Note that the UV coordinates are unpadded, if you must avoid bleed then pad it with 0.5/atlas size 

-- Contains tileX and tileY as [7] and [8]
local atlas = {
	atlasimage = "luaui/images/particlesGL4/particlesgl4_plus.dds",
	width = 4096,
	height = 4096,
	flip = function(t) for k,v in pairs(t) do if type(v) == "table" then v[3], v[4] = 1.0 - v[3], 1.0 - v[4] end end end ,
	pad = function(t,p) for k,v in pairs(t) do if type(v) == "table" then p = p or 0.5; local px,py = p/t.width, p/t.height; v[1], v[2], v[3], v[4] = v[1] + px, v[2]-px, v[3] + py, v[4] - py end end end ,
	getUVCoords = function(t, name) if t[name] then return t[name][1], t[name][2], t[name][3], t[name][4] else return 0,1,0,1 end end ,

	["TX_Pyro_Clouds_A_2x4_P1.tga"] = {0.625,0.75,0.5,0.5625,1024,1024,1,1,0}, 
	["test_cube_normal.dds"] = {0.0,1.0,0.0,1.0,512,512,1,1,0}, 

}
return atlas
