return {
	["WhiteLight"] = {
		light = {
			useAirLos = false,
			usedefaultexplosions = false,
			class = [[CHeatCloudProjectile]],
			air = true,
			water = true,
			ground = true,
			unit = true,
			count = 1,
			properties = {
				heat = 25,
				texture = [[flare]],
				maxheat = 25,
				heatFalloff = 1.14,
				size = 12.0,
				sizeGrowth = 0.24,
				sizemod = 0,
				sizemodmod = 0,
				speed = [[0, 0, 0]],
				pos = [[0, 0.0, 0]],
				useAirLos = false,
			},
		},
	},

	["IntelLight"] = {
		light = {
			useAirLos = false,
			usedefaultexplosions = false,
			class = [[CHeatCloudProjectile]],
			air = true,
			water = true,
			ground = true,
			unit = true,
			count = 1,
			properties = {
				heat = 40,
				texture = [[flare1]],
				maxheat = 40,
				heatFalloff = 1.1,
				size = 10,
				sizeGrowth = 0.02,
				sizemod = 0,
				sizemodmod = 0,
				speed = [[0, 0, 0]],
				pos = [[0, 2, 0]],
				useAirLos = false,
			},
		},
	},

	["YellowLight"] = {
		light = {
			useAirLos = false,
			usedefaultexplosions = false,
			class = [[CHeatCloudProjectile]],
			air = true,
			water = true,
			ground = true,
			unit = true,
			count = 1,
			properties = {
				heat = 60,
				texture = [[flare1]],
				maxheat = 60,
				heatFalloff = 1.1,
				size = 9,
				sizeGrowth = 0.02,
				sizemod = 0,
				sizemodmod = 0,
				speed = [[0, 0, 0]],
				pos = [[0, 0.0, 0]],
				useAirLos = false,
			},
		},
	},

	["PurpleLight"] = {
		light = {
			useAirLos = false,
			usedefaultexplosions = false,
			class = [[CHeatCloudProjectile]],
			air = true,
			water = true,
			ground = true,
			unit = true,
			count = 1,
			properties = {
				heat = 50,
				texture = [[flare1]],
				maxheat = 50,
				heatFalloff = 1.80,
				size = 24,
				sizeGrowth = 0.04,
				sizemod = 0,
				sizemodmod = 0,
				speed = [[0, 0, 0]],
				pos = [[0, 4, 0]],
				useAirLos = false,
				alwaysvisible = true,
			},
		},
	},

	["GantWhiteLight"] = {
		light = {
			useAirLos = false,
			usedefaultexplosions = false,
			class = [[CHeatCloudProjectile]],
			air = true,
			water = true,
			ground = true,
			unit = true,
			count = 1,
			properties = {
				heat = 30,
				texture = [[flare]],
				maxheat = 30,
				heatFalloff = 0.34,
				size = 20.0,
				sizeGrowth = 0.09,
				sizemod = 0,
				sizemodmod = 0,
				speed = [[0, 0, 0]],
				pos = [[0, 0.0, 0]],
				useAirLos = false,
			},
		},
	},
		["LootboxLightGold"] = {
			light = {
			useAirLos = false,
			usedefaultexplosions = false,
			class = [[CHeatCloudProjectile]],
			air = true,
			water = true,
			ground = true,
			unit = true,
			count = 1,
			properties = {
				--alwaysVisible = true,
				heat = 80,
				texture = [[glow2]],
				maxheat = 80,
				heatFalloff = 2.6,
				size = 10.0,
				sizeGrowth = 0.04,
				sizemod = 0,
				sizemodmod = 0,
				speed = [[0, 0, 0]],
				pos = [[0, 1, 0]],
				useAirLos = false,
			},
		},
	},
}
