return {
	["WhiteLight"] = {
		useAirLos = false,
		usedefaultexplosions = false,
		["heatcloud"] = {
			air = true,
			water = true,
			ground = true,
			unit = true,
			count = 2,
			properties = {
				heat = 25,
				texture = [[flare]],
				maxheat = 25,
				heatFalloff = 1.14,
				size = [[12.0 r1]],
				sizeGrowth = [[0.08 r.16]],
				sizemod = 0,
				sizemodmod = 0,
				speed = [[0.05 r-0.1, 0.05 r-0.1, 0.05 r-0.1]],
				pos = [[0, 0.0, 0]],
				useAirLos = false,
			},
		},
	},

	["IntelLight"] = {
		useAirLos = false,
		usedefaultexplosions = false,
		["heatcloud"] = {
			air = true,
			water = true,
			ground = true,
			unit = true,
			count = 3,
			properties = {
				heat = 30,
				texture = [[flare1]],
				maxheat = 30,
				heatFalloff = 1.2,
				size = [[9.0 r0.4]],
				sizeGrowth = [[-0.005 r0.02]],
				sizemod = 0,
				sizemodmod = 0,
				speed = [[0.05 r-0.05, 0.05 r-0.05, 0.05 r-0.05]],
				pos = [[0, 0.0, 0]],
				useAirLos = false,
			},
		},
	},

	["YellowLight"] = {
		useAirLos = false,
		usedefaultexplosions = false,
		["heatcloud"] = {
			air = true,
			water = true,
			ground = true,
			unit = true,
			count = 3,
			properties = {
				heat = 30,
				texture = [[glow2]],
				maxheat = 30,
				heatFalloff = 1.2,
				size = [[5.0 r0.4]],
				sizeGrowth = [[-0.005 r0.02]],
				sizemod = 0,
				sizemodmod = 0,
				speed = [[0.05 r-0.05, 0.05 r-0.05, 0.05 r-0.05]],
				pos = [[0, 0.0, 0]],
				useAirLos = false,
			},
		},
	},

	["PurpleLight"] = {
		useAirLos = false,
		usedefaultexplosions = false,
		["heatcloud"] = {
			air = true,
			water = true,
			ground = true,
			unit = true,
			count = 2,
			properties = {
				heat = 25,
				texture = [[flare]],
				maxheat = 25,
				heatFalloff = 0.80,
				size = [[4.0 r0.5]],
				sizeGrowth = [[0.04 r.4]],
				sizemod = 0,
				sizemodmod = 0,
				speed = [[0.05 r-0.05, 0.05 r-0.05, 0.05 r-0.05]],
				pos = [[0, 0.0, 0]],
				useAirLos = false,
			},
		},
	},

	["GantWhiteLight"] = {
		useAirLos = false,
		usedefaultexplosions = false,
		["heatcloud"] = {
			air = true,
			water = true,
			ground = true,
			unit = true,
			count = 2,
			properties = {
				heat = 30,
				texture = [[flare]],
				maxheat = 30,
				heatFalloff = 0.34,
				size = [[20.0 r1]],
				sizeGrowth = [[0.09 r.16]],
				sizemod = 0,
				sizemodmod = 0,
				speed = [[0.05 r-0.1, 0.05 r-0.1, 0.05 r-0.1]],
				pos = [[0, 0.0, 0]],
				useAirLos = false,
			},
		},
	},
		["LootboxLightGold"] = {
		useAirLos = false,
		usedefaultexplosions = false,
		["heatcloud"] = {
			air = true,
			water = true,
			ground = true,
			unit = true,
			count = 3,
			properties = {
				--alwaysVisible = true,
				heat = 30,
				texture = [[glow2]],
				maxheat = 30,
				heatFalloff = 1.4,
				size = [[4.0 r0.4]],
				sizeGrowth = [[-0.02 r0.02]],
				sizemod = 0,
				sizemodmod = 0,
				speed = [[0.05 r-0.05, 0.05 r-0.05, 0.05 r-0.05]],
				pos = [[0, 0.0, 0]],
				useAirLos = false,
			},
		},
	},
}
