return {
	corhaca = {
		blocking = false,
		builddistance = 136,
		builder = true,
		buildpic = "CORCSA.DDS",
		buildtime = 12000,
		canfly = true,
		canmove = true,
		cansubmerge = true,
		collide = true,
		cruisealtitude = 55,
		energycost = 8200,
		energymake = 20,
		energystorage = 75,
		explodeas = "smallexplosiongeneric-builder",
		footprintx = 2,
		footprintz = 2,
		health = 435,
		hoverattack = true,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.072,
		maxdec = 0.4275,
		maxslope = 10,
		maxwaterdepth = 255,
		metalcost = 350,
		objectname = "Units/CORCSA.s3o",
		script = "Units/CORCSA.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd-builder",
		sightdistance = 351,
		speed = 217.5,
		terraformspeed = 300,
		turninplaceanglelimit = 360,
		turnrate = 240,
		workertime = 75,
		buildoptions = {
			[1] = "corfus",
			[2] = "corbhmth",
			[3] = "coruwadves",
			[4] = "coruwadvms",
			[5] = "corarad",
			[6] = "corshroud",
			[7] = "corfort",
			[8] = "corasp",
			[9] = "cortarg",
			[10] = "corsd",
			[11] = "corgate",
			[12] = "corvipe",
			[13] = "corflak",
			[14] = "cortron",
			[15] = "corfmd",
			[16] = "corap",
			[17] = "coraap",
			[18] = "corhaap",
			[19] = "cormoho",
		},
		customparams = {
			model_author = "Beherith",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "CorSeaplanes",
			unitgroup = "buildert2",
			techlevel = 2,
		},
		sfxtypes = {
			crashexplosiongenerators = {
				[1] = "crashing-small",
				[2] = "crashing-small",
				[3] = "crashing-small2",
				[4] = "crashing-small3",
				[5] = "crashing-small3",
			},
			pieceexplosiongenerators = {
				[1] = "airdeathceg2-builder",
				[2] = "airdeathceg3-builder",
				[3] = "airdeathceg4-builder",
			},
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "seapsel2",
			},
		},
	},
}
