return {
	corhalab = {
		builder = true,
		buildpic = "CORGANT.DDS",
		buildtime = 67300,
		canmove = true,
		collisionvolumeoffsets = "0 12 0",
		collisionvolumescales = "196 110 196",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 47000,
		energystorage = 1400,
		explodeas = "hugeBuildingexplosiongeneric",
		footprintx = 12,
		footprintz = 12,
		health = 17800,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0,
		maxdec = 0,
		maxslope = 10,
		maxwaterdepth = 0,
		metalcost = 6400,
		metalstorage = 800,
		objectname = "Units/CORGANT.s3o",
		script = "Units/CORGANT.cob",
		seismicsignature = 0,
		selfdestructas = "hugeBuildingExplosionGenericSelfd",
		sightdistance = 273,
		terraformspeed = 3000,
		workertime = 1200,
		yardmap = "oooooooooooo oooooooooooo oooooooooooo ooeeeeeeeeoo ooeeeeeeeeoo ooeeeeeeeeoo ooeeeeeeeeoo ooeeeeeeeeoo ooeeeeeeeeoo ooeeeeeeeeoo ooeeeeeeeeoo ooeeeeeeeeoo",
		buildoptions = {
			[1] = "corkorg",
			[2] = "corkarg",
			[3] = "corshiva",
			[4] = "corcat",
			[5] = "cordemon",
			[6] = "corhack",
			[7] = "corsumo",
			[8] = "cordecom",
			[9] = "corvoyr",
			[10] = "corsktl",
			[11] = "corspec"
		},
		customparams = {
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 15,
			buildinggrounddecalsizey = 15,
			buildinggrounddecaltype = "decals/corgant_aoplane.dds",
			model_author = "Mr Bob, Tharsis",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "CorBuildings/LandFactories",
			techlevel = 3,
			unitgroup = "buildert3",
			usebuildinggrounddecal = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 -21 0",
				collisionvolumescales = "114 74 129",
				collisionvolumetype = "CylZ",
				damage = 9600,
				featuredead = "HEAP",
				footprintx = 12,
				footprintz = 12,
				height = 20,
				metal = 5101,
				object = "Units/corgant_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 4800,
				footprintx = 12,
				footprintz = 12,
				height = 4,
				metal = 2040,
				object = "Units/cor7X7B.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:GantWhiteLight",
				[2] = "custom:YellowLight",
				[3] = "custom:WhiteLight",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg4",
			},
		},
		sounds = {
			activate = "gantok2",
			build = "gantok2",
			canceldestruct = "cancel2",
			deactivate = "gantok2",
			repair = "lathelrg",
			underattack = "warning1",
			unitcomplete = "gantok1",
			working = "build",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "gantsel1",
			},
		},
	},
}

