return {
	corhalab = {
		buildangle = 1024,
		builder = true,
		buildpic = "CORLAB.DDS",
		buildtime = 13000,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "93 92 87",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 2600,
		energystorage = 200,
		explodeas = "largeBuildingexplosiongeneric",
		footprintx = 6,
		footprintz = 6,
		health = 5800,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0,
		maxdec = 0,
		maxslope = 15,
		maxwaterdepth = 0,
		metalcost = 1240,
		metalstorage = 200,
		objectname = "Units/CORHALAB.s3o",
		script = "Units/CORHALAB.cob",
		seismicsignature = 0,
		selfdestructas = "largeBuildingExplosionGenericSelfd",
		sightdistance = 290,
		terraformspeed = 500,
		workertime = 400,
		yardmap = "oeeeeooeeeeooeeeeooeeeeooeeeeooeeeeo",
		buildoptions = {
			[1] = "corfast",
			[2] = "coraak",
			[3] = "cormort",
			[4] = "corcan",
			[5] = "corpyro",
			[6] = "corsktl",
			[7] = "coramph",
			[8] = "cormando"
		},
		customparams = {
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 8,
			buildinggrounddecalsizey = 8,
			buildinggrounddecaltype = "decals/corlab_aoplane.dds",
			model_author = "Mr Bob",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "CorBuildings/LandFactories",
			unitgroup = "builder",
			usebuildinggrounddecal = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "88 28 88",
				collisionvolumetype = "Box",
				damage = 1560,
				featuredead = "HEAP",
				footprintx = 6,
				footprintz = 6,
				height = 20,
				metal = 884,
				object = "Units/corhalab_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 780,
				footprintx = 6,
				footprintz = 6,
				height = 4,
				metal = 354,
				object = "Units/cor6X6B.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:WhiteLight",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			unitcomplete = "unitready",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "labselect",
			},
		},
	},
}
