return {
	corsaap = {
		activatewhenbuilt = true,
		builder = true,
		buildpic = "LEGAAP.DDS",
		buildtime = 35000,
		canmove = true,
		collisionvolumeoffsets = "0 4 0",
		collisionvolumescales = "142 64 142",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 35000,
		energystorage = 200,
		explodeas = "largeBuildingExplosionGeneric",
		footprintx = 9,
		footprintz = 9,
		health = 3900,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0,
		maxdec = 0,
		maxslope = 15,
		maxwaterdepth = 0,
		metalcost = 3500,
		metalstorage = 200,
		objectname = "Units/LEGAAP.s3o",
		radardistance = 1000,
		radaremitheight = 50,
		script = "Units/LEGAAP.cob",
		seismicsignature = 0,
		selfdestructas = "largeBuildingExplosionGenericSelfd",
		sightdistance = 305.5,
		terraformspeed = 1000,
		workertime = 200,
		yardmap = "ooooooooo ooooooooo ooooooooo ooooooooo ooooooooo ooooooooo ooooooooo ooooooooo ooooooooo",
		buildoptions = {
			[1] = "corcsa",
			[2] = "corape",
			[3] = "corhurc",
			[4] = "cortitan",
			[5] = "corvamp",
			[6] = "corseah",
			[7] = "corcrwh",
			[8] = "corhunt",
		},
		customparams = {
			airfactory = true,
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 12,
			buildinggrounddecalsizey = 12,
			buildinggrounddecaltype = "decals/coraap_aoplane.dds",
			model_author = "Mr Bob",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "CorBuildings/LandFactories",
			techlevel = 2,
			unitgroup = "buildert2",
			usebuildinggrounddecal = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 -12 -22",
				collisionvolumescales = "98 32 52",
				collisionvolumetype = "Box",
				damage = 2112,
				featuredead = "HEAP",
				footprintx = 9,
				footprintz = 9,
				height = 20,
				metal = 1936,
				object = "Units/legaap_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 1056,
				footprintx = 9,
				footprintz = 9,
				height = 4,
				metal = 968,
				object = "Units/cor6X6A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:WhiteLight",
				[2] = "custom:radarpulse_t1_slow",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			unitcomplete = "untdone",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "pairactv",
			},
		},
	},
}
