return {
	armdronecarry = {
		activatewhenbuilt = true,
		buildangle = 16384,
		buildpic = "ARMDRONECARRY.DDS",
		buildtime = 20000,
		canmove = true,
		canreclaim = false,
		canrepair = false,
		category = "ALL NOTLAND MOBILE NOTSUB NOWEAPON SHIP NOTAIR NOTHOVER SURFACE EMPABLE",
		collisionvolumeoffsets = "3 -7 -3",
		collisionvolumescales = "48 48 140",
		collisionvolumetype = "CylZ",
		corpse = "DEAD",
		energycost = 13000,
		energymake = 25,
		energystorage = 1500,
		energyupkeep = 25,
		explodeas = "hugeexplosiongeneric",
		floater = true,
		footprintx = 6,
		footprintz = 6,
		health = 3500,
		idleautoheal = 15,
		idletime = 600,
		mass = 10000,
		maxacc = 0.01722,
		maxdec = 0.01722,
		metalcost = 1300,
		minwaterdepth = 15,
		movementclass = "BOAT8",
		nochasecategory = "VTOL",
		objectname = "Units/ARMDRONECARRY.s3o",
		radardistance = 1500,
		radaremitheight = 56,
		script = "Units/ARMDRONECARRY.cob",
		seismicsignature = 0,
		selfdestructas = "hugeexplosiongenericSelfD",
		sightdistance = 700,
		sightemitheight = 56,
		sonardistance = 700,
		speed = 63,
		turninplace = true,
		turninplaceanglelimit = 90,
		turnrate = 180,
		waterline = 0,
		customparams = {
			childreninheritxp = "DRONE",
			inheritxpratemultiplier = 1,
			model_author = "Odin",
			normaltex = "unittextures/Arm_normal.dds",
			parentsinheritxp = "DRONE",
			subfolder = "ArmShips/T2",
			techlevel = 2,
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "-0.0550308227539 1.52587890767e-06 4.55026245117",
				collisionvolumescales = "61.8225860596 60.9250030518 154.450805664",
				collisionvolumetype = "Box",
				damage = 9168,
				featuredead = "HEAP",
				footprintx = 6,
				footprintz = 6,
				height = 4,
				metal = 700,
				object = "Units/armdronecarry_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 4032,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 350,
				object = "Units/arm6X6C.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:radarpulse_t1_slow",
				[2] = "custom:waterwake-large",
				[3] = "custom:bowsplash-huge",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "sharmmov",
			},
			select = {
				[1] = "sharmsel",
			},
		},
		weapondefs = {
			aamissile = {
				areaofeffect = 48,
				avoidfeature = false,
				burnblow = true,
				canattackground = false,
				castshadow = false,
				cegtag = "missiletrailaa",
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-medium-air",
				firestarter = 70,
				flighttime = 1.75,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				metalpershot = 0,
				model = "cormissile.s3o",
				name = "Missiles",
				noselfdamage = true,
				range = 710,
				reloadtime = 2,
				smokecolor = 0.95,
				smokeperiod = 7,
				smokesize = 5.4,
				smoketime = 13,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "xplomed2",
				soundhitwet = "splshbig",
				soundstart = "rockhvy2",
				startvelocity = 430,
				texture1 = "null",
				texture2 = "smoketrailaa3",
				tolerance = 8000,
				tracks = true,
				turnrate = 30000,
				turret = true,
				weaponacceleration = 90,
				weapontimer = 5,
				weapontype = "MissileLauncher",
				weaponvelocity = 450,
				damage = {
					vtol = 138,
				},
			},
			plasma = {
				areaofeffect = 4,
				avoidfeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "",
				gravityaffected = "true",
				hightrajectory = 1,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				name = "HeavyCannon",
				noselfdamage = true,
				range = 1300,
				reloadtime = 2.5,
				size = 0,
				soundhit = "",
				soundhitwet = "",
				soundstart = "",
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 800,
				customparams = {
					attackformationoffset = 30,
					attackformationspread = 120,
					carried_unit = "armdrone",
					carrierdeaththroe = "release",
					controlradius = 1400,
					decayrate = 6,
					dockingarmor = 0.2,
					dockinghealrate = 24,
					dockinghelperspeed = 5,
					dockingpieces = "11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27",
					dockingradius = 300,
					docktohealthreshold = 65,
					enabledocking = true,
					energycost = 600,
					engagementrange = 1300,
					maxunits = 16,
					metalcost = 25,
					spawnrate = 4,
					spawns_surface = "SEA",
				},
				damage = {
					default = 0,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "PLASMA",
				onlytargetcategory = "SURFACE",
			},
			[2] = {
				def = "AAMISSILE",
				onlytargetcategory = "VTOL",
			},
		},
	},
}
