return {
	raptor_allterrain_swarmer_acid_t2_v1 = {
		activatewhenbuilt = true,
		maxacc = 1.4375,
		maxdec = 2.3,
		energycost = 5280,
		metalcost = 99,
		builder = false,
		buildpic = "raptors/raptoracidallterrain.DDS",
		buildtime = 2250,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = "1",
		capturable = false,
		category = "RAPTOR",
		collisionvolumeoffsets = "0 -3 -3",
		collisionvolumescales = "18 28 40",
		collisionvolumetype = "box",
		defaultmissiontype = "Standby",
		explodeas = "BUG_DEATH_ACID",
		footprintx = 2,
		footprintz = 2,
		leavetracks = true,
		maneuverleashlength = "640",
		mass = 89,
		health = 2000,
		maxreversevelocity = 3,
		maxslope = 18,
		speed = 97.5,
		maxwaterdepth = 15,
		movementclass = "RAPTORALLTERRAINHOVER",
		noautofire = false,
		nochasecategory = "VTOL",
		objectname = "Raptors/raptoracidallterrain.s3o",
		script = "Raptors/raptorc3.cob",
		seismicsignature = 0,
		selfdestructas = "BIGBUG_DEATH_ACID",
		side = "THUNDERBIRDS",
		sightdistance = 300,
		smoothanim = true,
		sonardistance = 450,
		trackoffset = 0.5,
		trackstrength = 3,
		trackstretch = 1,
		tracktype = "RaptorTrackPointy",
		trackwidth = 35,
		turninplace = true,
		turninplaceanglelimit = 90,
		turnrate = 1840,
		unitname = "raptorc3",
		upright = false,
		workertime = 0,
		waterline = 12,
		customparams = {
			subfolder = "other/raptors",
			model_author = "KDR_11k, Beherith",
			normalmaps = "yes",
			normaltex = "unittextures/chicken_s_normals.png",
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:blood_spray",
				[2] = "custom:blood_explode",
				[3] = "custom:dirt",
			},
			pieceexplosiongenerators = {
				[1] = "blood_spray",
				[2] = "blood_spray",
				[3] = "blood_spray",
			},
		},
		weapondefs = {
			acidspit = {
				accuracy = 1024,
				areaofeffect = 75,
				collidefriendly = 0,
				collidefeature = 0,
				avoidfeature = 0,
				avoidfriendly = 0,
				burst = 2,
				burstrate = 0.3,
				cegtag = "blob_trail_green",
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.63,
				explosiongenerator = "custom:acid-explosion-small",
				impulseboost = 0,
				impulsefactor = 0.4,
				intensity = 0.7,
				interceptedbyshieldtype = 1,
				name = "GOOLAUNCHER",
				noselfdamage = true,
				range = 300,
				reloadtime = 5,
				rgbcolor = "0.8 0.99 0.11",
				nogap = false,
				size = 7,
				sizedecay = 0.05,
				alphaDecay = 0.15,
				stages = 7,
				soundhit = "bloodsplash3",
				soundstart = "alien_bombrel",
				sprayangle = 128,
				tolerance = 5000,
				turret = true,
				weapontimer = 0.2,
				weaponvelocity = 520,
				damage = {
					default = 1, --damage done in unit_area_timed_damage.lua
					shields = 80,
				},
			},
		},
		weapons = {
			[1] = {
				def = "acidspit",
				maindir = "0 0 1",
				maxangledif = 110,
				onlytargetcategory = "NOTAIR",
			},
		},
	},
}
