local blueprintConfig = VFS.Include('luarules/gadgets/ruins/Blueprints/' .. Game.gameShortName .. '/blueprint_tiers.lua')
local tiers = blueprintConfig.Tiers
local types = blueprintConfig.BlueprintTypes
local UDN = UnitDefNames

--	facing:
--  0 - south
--  1 - east
--  2 - north
--  3 - west


local function EpicDefence0()
	return {
		type = types.Land,
		tiers = {tiers.T3, tiers.T4},
		radius = 144,
		buildings = {
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -48, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -112, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 144, zOffset = 80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -144, zOffset = 80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -144, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 80, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 144, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -112, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -48, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 112, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -80, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 144, zOffset = 48, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -144, zOffset = 112, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -144, zOffset = -112, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 144, zOffset = -112, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -144, zOffset = 48, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 112, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 80, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -144, zOffset = -80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 144, zOffset = 112, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -80, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -144, zOffset = -48, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -144, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 144, zOffset = -80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 144, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 144, zOffset = -48, direction = 1},
			{ unitDefID = UnitDefNames.armrad_scav.id, xOffset = -112, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.armrad_scav.id, xOffset = 112, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -56, zOffset = 104, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -104, zOffset = 104, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -56, zOffset = -104, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 56, zOffset = -104, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 104, zOffset = -104, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -104, zOffset = 56, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 104, zOffset = 104, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 104, zOffset = 56, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -104, zOffset = -56, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 104, zOffset = -56, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 56, zOffset = 104, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -104, zOffset = -104, direction = 1},
			{ unitDefID = UnitDefNames.armjamt_scav.id, xOffset = 0, zOffset = -112, direction = 1},
			{ unitDefID = UnitDefNames.armjamt_scav.id, xOffset = 0, zOffset = 112, direction = 1},
			{ unitDefID = UnitDefNames.armbotrail_scav.id, xOffset = 0, zOffset = 0, direction = 1},
		},
	}
end

local function EpicDefence1()
	return {
		type = types.Land,
		tiers = {tiers.T3, tiers.T4},
		radius = 155,
		buildings = {
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 131, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 35, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -141, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 3, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 67, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -77, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 131, zOffset = -128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 131, zOffset = 128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -109, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -45, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -45, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 35, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 3, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 67, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 99, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -77, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -141, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -141, zOffset = -128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 131, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 99, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -141, zOffset = 128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -109, zOffset = -144, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -53, zOffset = -104, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -5, zOffset = 104, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 91, zOffset = 104, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 43, zOffset = 104, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -101, zOffset = 104, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 43, zOffset = -104, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -5, zOffset = -104, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -53, zOffset = 104, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 91, zOffset = -104, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -101, zOffset = -104, direction = 1},
			{ unitDefID = UnitDefNames.armjuno_scav.id, xOffset = -93, zOffset = -32, direction = 1},
			{ unitDefID = UnitDefNames.armjuno_scav.id, xOffset = -93, zOffset = 32, direction = 1},
			{ unitDefID = UnitDefNames.armminivulc_scav.id, xOffset = 155, zOffset = 56, direction = 1},
			{ unitDefID = UnitDefNames.armminivulc_scav.id, xOffset = 155, zOffset = -56, direction = 1},
			{ unitDefID = UnitDefNames.armbotrail_scav.id, xOffset = 51, zOffset = 0, direction = 1},
		},
	}
end

local function EpicDefence2()
	return {
		type = types.Land,
		tiers = {tiers.T3, tiers.T4},
		radius = 224,
		buildings = {
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -104, zOffset = 224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -184, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -184, zOffset = -192, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 184, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -104, zOffset = -224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 88, zOffset = -224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -184, zOffset = 192, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 88, zOffset = 224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 152, zOffset = -160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -8, zOffset = -224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -136, zOffset = 224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -184, zOffset = 160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 56, zOffset = 224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 24, zOffset = -224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -168, zOffset = 224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 184, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 56, zOffset = -224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -184, zOffset = 32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -40, zOffset = 224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -184, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -136, zOffset = -224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -72, zOffset = -224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -184, zOffset = -32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 184, zOffset = 128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 120, zOffset = 192, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -8, zOffset = 224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 184, zOffset = -32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 184, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 184, zOffset = -128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -168, zOffset = -224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -184, zOffset = -160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -184, zOffset = -128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -72, zOffset = 224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -184, zOffset = 128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 24, zOffset = 224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -184, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 120, zOffset = -192, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 184, zOffset = 0, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -184, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -40, zOffset = -224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 152, zOffset = 160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 184, zOffset = 32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 184, zOffset = -96, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 0, zOffset = -40, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -144, zOffset = -40, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 48, zOffset = 136, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 96, zOffset = 88, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 144, zOffset = 88, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -96, zOffset = 40, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 48, zOffset = 184, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 48, zOffset = -136, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 96, zOffset = -88, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -48, zOffset = 40, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 0, zOffset = 40, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 48, zOffset = 88, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -144, zOffset = 40, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -48, zOffset = -40, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 48, zOffset = -88, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 48, zOffset = -184, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 144, zOffset = -88, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -96, zOffset = -40, direction = 1},
			{ unitDefID = UnitDefNames.armflak_scav.id, xOffset = 88, zOffset = -160, direction = 1},
			{ unitDefID = UnitDefNames.armflak_scav.id, xOffset = 88, zOffset = -192, direction = 1},
			{ unitDefID = UnitDefNames.armflak_scav.id, xOffset = 152, zOffset = -128, direction = 1},
			{ unitDefID = UnitDefNames.armflak_scav.id, xOffset = 152, zOffset = 128, direction = 1},
			{ unitDefID = UnitDefNames.armflak_scav.id, xOffset = 120, zOffset = -128, direction = 1},
			{ unitDefID = UnitDefNames.armflak_scav.id, xOffset = 88, zOffset = -128, direction = 1},
			{ unitDefID = UnitDefNames.armflak_scav.id, xOffset = 120, zOffset = 128, direction = 1},
			{ unitDefID = UnitDefNames.armflak_scav.id, xOffset = 88, zOffset = 128, direction = 1},
			{ unitDefID = UnitDefNames.armflak_scav.id, xOffset = 88, zOffset = 192, direction = 1},
			{ unitDefID = UnitDefNames.armflak_scav.id, xOffset = 88, zOffset = 160, direction = 1},
			{ unitDefID = UnitDefNames.armanni_scav.id, xOffset = -136, zOffset = 176, direction = 3},
			{ unitDefID = UnitDefNames.armanni_scav.id, xOffset = -136, zOffset = -176, direction = 3},
			{ unitDefID = UnitDefNames.armanni_scav.id, xOffset = -136, zOffset = -112, direction = 3},
			{ unitDefID = UnitDefNames.armanni_scav.id, xOffset = -136, zOffset = 112, direction = 3},
			{ unitDefID = UnitDefNames.armbotrail_scav.id, xOffset = 88, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.armbotrail_scav.id, xOffset = -40, zOffset = 128, direction = 1},
			{ unitDefID = UnitDefNames.armbotrail_scav.id, xOffset = -40, zOffset = -128, direction = 1},
		},
	}
end

local function EpicDefence3()
	return {
		type = types.Land,
		tiers = {tiers.T3, tiers.T4},
		radius = 176,
		buildings = {
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -139, zOffset = -80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -139, zOffset = 16, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -139, zOffset = 80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -123, zOffset = 112, direction = 2},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -59, zOffset = -144, direction = 2},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -91, zOffset = 144, direction = 2},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -11, zOffset = -176, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 85, zOffset = 176, direction = 2},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 133, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 117, zOffset = 32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 21, zOffset = 176, direction = 2},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 53, zOffset = 176, direction = 2},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 117, zOffset = 160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 133, zOffset = 128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -91, zOffset = -144, direction = 2},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 21, zOffset = -176, direction = 2},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 53, zOffset = -176, direction = 2},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 133, zOffset = -128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 133, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -59, zOffset = 144, direction = 2},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -27, zOffset = -144, direction = 2},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -123, zOffset = -48, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 117, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 117, zOffset = -32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -27, zOffset = 144, direction = 2},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -123, zOffset = -144, direction = 2},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -123, zOffset = 144, direction = 2},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -123, zOffset = -112, direction = 2},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -139, zOffset = -16, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 85, zOffset = -176, direction = 2},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 117, zOffset = -160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -11, zOffset = 176, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 117, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 133, zOffset = 0, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -123, zOffset = 48, direction = 1},
			{ unitDefID = UnitDefNames.armrl_scav.id, xOffset = -83, zOffset = 104, direction = 1},
			{ unitDefID = UnitDefNames.armrl_scav.id, xOffset = -35, zOffset = -104, direction = 1},
			{ unitDefID = UnitDefNames.armrl_scav.id, xOffset = -35, zOffset = 104, direction = 1},
			{ unitDefID = UnitDefNames.armrl_scav.id, xOffset = -83, zOffset = -104, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -83, zOffset = -40, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -35, zOffset = -40, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 29, zOffset = 88, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -35, zOffset = 40, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 77, zOffset = -88, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 29, zOffset = -88, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -83, zOffset = 40, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 77, zOffset = 88, direction = 1},
			{ unitDefID = UnitDefNames.armhlt_scav.id, xOffset = 21, zOffset = 144, direction = 0},
			{ unitDefID = UnitDefNames.armhlt_scav.id, xOffset = 85, zOffset = -144, direction = 2},
			{ unitDefID = UnitDefNames.armhlt_scav.id, xOffset = 85, zOffset = 144, direction = 0},
			{ unitDefID = UnitDefNames.armhlt_scav.id, xOffset = 21, zOffset = -144, direction = 2},
			{ unitDefID = UnitDefNames.armannit3_scav.id, xOffset = 53, zOffset = 0, direction = 1},
		},
	}
end

local function EpicDefence4()
	return {
		type = types.Land,
		tiers = {tiers.T3, tiers.T4},
		radius = 245,
		buildings = {
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -203, zOffset = -160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -219, zOffset = 0, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -43, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 21, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 229, zOffset = 32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -11, zOffset = -160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -139, zOffset = 160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 181, zOffset = -160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -203, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 229, zOffset = -32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -171, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -219, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -203, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 149, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 213, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -219, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -219, zOffset = 128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -139, zOffset = -160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -11, zOffset = 160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 245, zOffset = -128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -107, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 21, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -219, zOffset = -128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 117, zOffset = 160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -107, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 85, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 149, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -203, zOffset = 160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -75, zOffset = 160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -171, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -203, zOffset = 32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 245, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 85, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 245, zOffset = 0, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 117, zOffset = -160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 53, zOffset = -160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -203, zOffset = -32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 213, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 229, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -43, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -75, zOffset = -160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 245, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 53, zOffset = 160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 229, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 181, zOffset = 160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 245, zOffset = 128, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 29, zOffset = -24, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -67, zOffset = 24, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -163, zOffset = -24, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 29, zOffset = 24, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 77, zOffset = -24, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -163, zOffset = 24, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -19, zOffset = -24, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -67, zOffset = -24, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 77, zOffset = 24, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -115, zOffset = 24, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -19, zOffset = 24, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -115, zOffset = -24, direction = 1},
			{ unitDefID = UnitDefNames.armmercury_scav.id, xOffset = -155, zOffset = -96, direction = 1},
			{ unitDefID = UnitDefNames.armmercury_scav.id, xOffset = -155, zOffset = 96, direction = 1},
			{ unitDefID = UnitDefNames.armanni_scav.id, xOffset = 181, zOffset = 96, direction = 1},
			{ unitDefID = UnitDefNames.armanni_scav.id, xOffset = 181, zOffset = -96, direction = 1},
			{ unitDefID = UnitDefNames.armminivulc_scav.id, xOffset = -83, zOffset = -104, direction = 2},
			{ unitDefID = UnitDefNames.armminivulc_scav.id, xOffset = -35, zOffset = 104, direction = 0},
			{ unitDefID = UnitDefNames.armminivulc_scav.id, xOffset = -83, zOffset = 104, direction = 0},
			{ unitDefID = UnitDefNames.armminivulc_scav.id, xOffset = -35, zOffset = -104, direction = 2},
			{ unitDefID = UnitDefNames.armbrtha_scav.id, xOffset = 85, zOffset = 96, direction = 0},
			{ unitDefID = UnitDefNames.armbrtha_scav.id, xOffset = 85, zOffset = -96, direction = 2},
			{ unitDefID = UnitDefNames.armannit3_scav.id, xOffset = 165, zOffset = 0, direction = 1},
		},
	}
end

local function EpicDefence5()
	return {
		type = types.Land,
		tiers = {tiers.T3, tiers.T4},
		radius = 176,
		buildings = {
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 112, zOffset = 24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -80, zOffset = -152, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = -120, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 176, zOffset = 120, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -16, zOffset = -152, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -112, zOffset = 152, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = -152, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 176, zOffset = -56, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = -24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = 120, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -48, zOffset = 152, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = 88, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 112, zOffset = 152, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -192, zOffset = -104, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -16, zOffset = 152, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -80, zOffset = 24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = -56, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 176, zOffset = 56, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 16, zOffset = 152, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 16, zOffset = -24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -80, zOffset = 152, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 16, zOffset = 24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -16, zOffset = -24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = 24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -176, zOffset = -136, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -144, zOffset = 136, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 176, zOffset = 88, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 112, zOffset = -152, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 80, zOffset = -152, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 176, zOffset = -24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -144, zOffset = -136, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 16, zOffset = -152, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -144, zOffset = -40, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 80, zOffset = -24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 144, zOffset = -24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -176, zOffset = 136, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = 56, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -80, zOffset = -24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 112, zOffset = -24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -176, zOffset = 40, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 176, zOffset = -120, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -112, zOffset = -152, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -48, zOffset = -152, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -192, zOffset = 104, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 144, zOffset = 152, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = -88, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 176, zOffset = -152, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -176, zOffset = -40, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -192, zOffset = -72, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -112, zOffset = -24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -16, zOffset = 24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -112, zOffset = 24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 144, zOffset = -152, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 80, zOffset = 152, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 80, zOffset = 24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -48, zOffset = -24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -192, zOffset = 72, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -48, zOffset = 24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 144, zOffset = 24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -144, zOffset = 40, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 176, zOffset = -88, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 176, zOffset = 24, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 176, zOffset = 152, direction = 0},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = 152, direction = 0},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -88, zOffset = -112, direction = 0},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 8, zOffset = -64, direction = 0},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -40, zOffset = -112, direction = 0},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -88, zOffset = 112, direction = 0},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -40, zOffset = 112, direction = 0},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -88, zOffset = 64, direction = 0},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 8, zOffset = -112, direction = 0},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -40, zOffset = 64, direction = 0},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -88, zOffset = -64, direction = 0},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -40, zOffset = -64, direction = 0},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 8, zOffset = 64, direction = 0},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 8, zOffset = 112, direction = 0},
			{ unitDefID = UnitDefNames.armgate_scav.id, xOffset = -144, zOffset = 88, direction = 0},
			{ unitDefID = UnitDefNames.armamd_scav.id, xOffset = -144, zOffset = -88, direction = 0},
			{ unitDefID = UnitDefNames.armannit3_scav.id, xOffset = 112, zOffset = 88, direction = 1},
			{ unitDefID = UnitDefNames.armannit3_scav.id, xOffset = 112, zOffset = -88, direction = 1},
		},
	}
end



local function EpicDefence6()
	return {
		type = types.Land,
		tiers = {tiers.T3, tiers.T4},
		radius = 157,
		buildings = {
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -131, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 29, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 125, zOffset = 80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -131, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -131, zOffset = 48, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -131, zOffset = 16, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -131, zOffset = 80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 125, zOffset = -80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 157, zOffset = -32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -35, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -131, zOffset = -48, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -99, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -131, zOffset = 112, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 29, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -3, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -67, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 157, zOffset = 32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -67, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 93, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 157, zOffset = 0, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -35, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -3, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -131, zOffset = -16, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 125, zOffset = -112, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 125, zOffset = 112, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 61, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 93, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 61, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 125, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -131, zOffset = -80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 157, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -99, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -131, zOffset = -112, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 157, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 125, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -51, zOffset = 48, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -19, zOffset = 48, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -51, zOffset = -48, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -83, zOffset = -48, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 125, zOffset = -32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -83, zOffset = -16, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -19, zOffset = -48, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 125, zOffset = 0, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 125, zOffset = 32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -83, zOffset = 16, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -83, zOffset = 48, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = 5, zOffset = -104, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -91, zOffset = 104, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -91, zOffset = -104, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = 5, zOffset = 104, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -43, zOffset = 104, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -43, zOffset = -104, direction = 1},
			{ unitDefID = UnitDefNames.corfmd_scav.id, xOffset = -35, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.cordoom_scav.id, xOffset = 77, zOffset = 96, direction = 1},
			{ unitDefID = UnitDefNames.cordoom_scav.id, xOffset = 77, zOffset = -96, direction = 1},
			{ unitDefID = UnitDefNames.cordoomt3_scav.id, xOffset = 61, zOffset = 0, direction = 1},
		},
	}
end

local function EpicDefence7()
	return {
		type = types.Land,
		tiers = {tiers.T3, tiers.T4},
		radius = 208,
		buildings = {
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 160, zOffset = -128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -128, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 144, zOffset = 160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -64, zOffset = -208, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 160, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 144, zOffset = 32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 144, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 160, zOffset = 0, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -128, zOffset = 192, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -128, zOffset = 128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 144, zOffset = -160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -144, zOffset = -160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -64, zOffset = 208, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -128, zOffset = -128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -144, zOffset = 160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -144, zOffset = -32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -144, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -96, zOffset = 208, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -96, zOffset = -208, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -128, zOffset = -192, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -144, zOffset = 32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 160, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -128, zOffset = 0, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -144, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -32, zOffset = -208, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 144, zOffset = -32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 144, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -128, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -32, zOffset = 208, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 160, zOffset = 128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -32, zOffset = 32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -32, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 0, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = 176, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -32, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -32, zOffset = -32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 16, zOffset = -176, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 16, zOffset = 176, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 112, zOffset = -176, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -16, zOffset = -176, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = -176, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -32, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -32, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -16, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 80, zOffset = -176, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 0, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 112, zOffset = 176, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -16, zOffset = 176, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 80, zOffset = 176, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -16, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -32, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.corrad_scav.id, xOffset = 16, zOffset = 144, direction = 1},
			{ unitDefID = UnitDefNames.corjamt_scav.id, xOffset = 16, zOffset = -144, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -88, zOffset = -88, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = 56, zOffset = -88, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -88, zOffset = -24, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -72, zOffset = -168, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -88, zOffset = 88, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = 56, zOffset = -136, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -88, zOffset = 24, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -72, zOffset = 168, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = 56, zOffset = 88, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = 56, zOffset = 136, direction = 1},
			{ unitDefID = UnitDefNames.corflak_scav.id, xOffset = 0, zOffset = -64, direction = 1},
			{ unitDefID = UnitDefNames.corflak_scav.id, xOffset = 112, zOffset = -80, direction = 1},
			{ unitDefID = UnitDefNames.corflak_scav.id, xOffset = 0, zOffset = 64, direction = 1},
			{ unitDefID = UnitDefNames.corflak_scav.id, xOffset = 0, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.corflak_scav.id, xOffset = 112, zOffset = 80, direction = 1},
			{ unitDefID = UnitDefNames.corminibuzz_scav.id, xOffset = 104, zOffset = -136, direction = 1},
			{ unitDefID = UnitDefNames.corminibuzz_scav.id, xOffset = 104, zOffset = 136, direction = 1},
			{ unitDefID = UnitDefNames.cordoomt3_scav.id, xOffset = 80, zOffset = 0, direction = 1},
		},
	}
end

local function EpicDefence8()
	return {
		type = types.Land,
		tiers = {tiers.T3, tiers.T4},
		radius = 216,
		buildings = {
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 3, zOffset = 56, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 83, zOffset = -168, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 51, zOffset = -168, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 51, zOffset = 168, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 51, zOffset = -40, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 147, zOffset = -136, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 147, zOffset = -104, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 115, zOffset = -168, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 147, zOffset = -72, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 147, zOffset = -40, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 83, zOffset = 40, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 51, zOffset = 40, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -125, zOffset = 56, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -29, zOffset = -56, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 147, zOffset = 104, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -29, zOffset = 56, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -125, zOffset = -56, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -61, zOffset = -56, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 147, zOffset = 72, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 115, zOffset = 40, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -61, zOffset = 56, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 3, zOffset = -56, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 147, zOffset = 168, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 115, zOffset = -40, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 147, zOffset = -168, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 83, zOffset = 168, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -93, zOffset = 56, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -93, zOffset = -56, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 147, zOffset = 136, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 115, zOffset = 168, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 83, zOffset = -40, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 147, zOffset = 40, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -125, zOffset = -120, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -61, zOffset = -216, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -29, zOffset = 216, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -93, zOffset = -216, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -125, zOffset = -88, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 3, zOffset = -216, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -125, zOffset = 184, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -125, zOffset = 120, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -29, zOffset = -216, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -125, zOffset = 88, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -61, zOffset = 216, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -125, zOffset = -184, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -125, zOffset = 152, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -125, zOffset = 216, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -125, zOffset = -216, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -125, zOffset = -152, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -93, zOffset = 216, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 3, zOffset = 216, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -5, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = 91, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = 43, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -101, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -53, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = 139, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -149, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.corgate_scav.id, xOffset = -13, zOffset = -104, direction = 1},
			{ unitDefID = UnitDefNames.corgate_scav.id, xOffset = -13, zOffset = 104, direction = 1},
			{ unitDefID = UnitDefNames.cortron_scav.id, xOffset = -77, zOffset = -168, direction = 1},
			{ unitDefID = UnitDefNames.cortron_scav.id, xOffset = -77, zOffset = 168, direction = 1},
			{ unitDefID = UnitDefNames.cortron_scav.id, xOffset = -13, zOffset = -168, direction = 1},
			{ unitDefID = UnitDefNames.cortron_scav.id, xOffset = -13, zOffset = 168, direction = 1},
			{ unitDefID = UnitDefNames.cortron_scav.id, xOffset = -77, zOffset = 104, direction = 1},
			{ unitDefID = UnitDefNames.cortron_scav.id, xOffset = -77, zOffset = -104, direction = 1},
			{ unitDefID = UnitDefNames.cordoomt3_scav.id, xOffset = 83, zOffset = -104, direction = 1},
			{ unitDefID = UnitDefNames.cordoomt3_scav.id, xOffset = 83, zOffset = 104, direction = 1},
		},
	}
end


local function EpicDefence9()
	return {
		type = types.Land,
		tiers = {tiers.T3, tiers.T4 },
		radius = 192,
		buildings = {
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 158, zOffset = 32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 126, zOffset = -192, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -114, zOffset = 48, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -2, zOffset = -160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -130, zOffset = -80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -114, zOffset = 112, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 158, zOffset = -32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 158, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 30, zOffset = -192, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -130, zOffset = -16, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 30, zOffset = 192, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 94, zOffset = -192, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 94, zOffset = 192, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -130, zOffset = 16, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 158, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -2, zOffset = 128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -114, zOffset = -112, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -2, zOffset = 192, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -2, zOffset = -128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -114, zOffset = -48, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 62, zOffset = 192, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 126, zOffset = 192, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 62, zOffset = -192, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -2, zOffset = 160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -130, zOffset = 80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 158, zOffset = 0, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -2, zOffset = -192, direction = 1},
			{ unitDefID = UnitDefNames.armrad_scav.id, xOffset = -50, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -26, zOffset = -40, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -26, zOffset = -88, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -26, zOffset = 40, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -74, zOffset = -40, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -74, zOffset = 40, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -74, zOffset = -88, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -26, zOffset = 88, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -74, zOffset = 88, direction = 1},
			{ unitDefID = UnitDefNames.armlab_scav.id, xOffset = 62, zOffset = 128, direction = 1},
			{ unitDefID = UnitDefNames.armlab_scav.id, xOffset = 62, zOffset = -128, direction = 1},
			{ unitDefID = UnitDefNames.armgate_scav.id, xOffset = -178, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.armbotrail_scav.id, xOffset = 78, zOffset = 0, direction = 1},
		},
	}
end

local function EpicDefence10()
	return {
		type = types.Land,
		tiers = {tiers.T3, tiers.T4 },
		radius = 96,
		buildings = {
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -32, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 96, zOffset = 16, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 32, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -96, zOffset = 16, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 0, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 80, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 64, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 0, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 64, zOffset = -32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 96, zOffset = -16, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 64, zOffset = 32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -32, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -64, zOffset = 32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -96, zOffset = -16, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 32, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 64, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -80, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -64, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -64, zOffset = -32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -80, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 80, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -64, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 64, zOffset = 0, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -48, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 0, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 0, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -64, zOffset = 0, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -48, zOffset = 64, direction = 1},
			{ unitDefID = UnitDefNames.armannit3_scav.id, xOffset = 0, zOffset = 0, direction = 1},
		},
	}
end

local function EpicDefence11()
	return {
		type = types.Land,
		tiers = {tiers.T3, tiers.T4 },
		radius = 128,
		buildings = {
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 112, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 128, zOffset = -32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 0, zOffset = -112, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -64, zOffset = 112, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -128, zOffset = 32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -80, zOffset = 80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -32, zOffset = 128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 112, zOffset = 0, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 112, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -112, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 128, zOffset = 32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 80, zOffset = -80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -64, zOffset = -112, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 32, zOffset = 128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 64, zOffset = 112, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -32, zOffset = -128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -80, zOffset = -80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -128, zOffset = -32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 80, zOffset = 80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 64, zOffset = -112, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 0, zOffset = 112, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -112, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -112, zOffset = 0, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 32, zOffset = -128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -80, zOffset = -48, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 80, zOffset = 0, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -80, zOffset = 48, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -80, zOffset = 0, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = -80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = 80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 80, zOffset = -48, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 0, zOffset = -80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -48, zOffset = 80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -48, zOffset = -80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 0, zOffset = 80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 80, zOffset = 48, direction = 1},
			{ unitDefID = UnitDefNames.armbotrail_scav.id, xOffset = 0, zOffset = 0, direction = 1},
		},
	}
end

local function EpicDefence12()
	return {
		type = types.Land,
		tiers = {tiers.T3, tiers.T4 },
		radius = 96,
		buildings = {
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -32, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -80, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 96, zOffset = 16, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -80, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -64, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -64, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 32, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -96, zOffset = 16, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 64, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -64, zOffset = 32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 64, zOffset = -32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 64, zOffset = 32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 0, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 32, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 64, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -96, zOffset = -16, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -64, zOffset = -32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 80, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 80, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 96, zOffset = -16, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 0, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -32, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -48, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 48, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -64, zOffset = 0, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 64, zOffset = 0, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 0, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = -48, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 2), xOffset = 0, zOffset = -64, direction = 1},
			{ unitDefID = UnitDefNames.cordoomt3_scav.id, xOffset = 0, zOffset = 0, direction = 1},
		},
	}
end

local function EpicDefence13()
	return {
		type = types.Land,
		tiers = {tiers.T3, tiers.T4 },
		radius = 304,
		buildings = {
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -24, zOffset = -304, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 232, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 168, zOffset = -208, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 136, zOffset = -240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -88, zOffset = 304, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 8, zOffset = -288, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 232, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 104, zOffset = -272, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 168, zOffset = 208, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -152, zOffset = -304, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 8, zOffset = 288, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -120, zOffset = 288, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -24, zOffset = 304, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 40, zOffset = -304, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -56, zOffset = -288, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 200, zOffset = -176, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 40, zOffset = 304, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 72, zOffset = 288, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 104, zOffset = 272, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 72, zOffset = -288, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -88, zOffset = -304, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -152, zOffset = 304, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -56, zOffset = 288, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 200, zOffset = 176, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -120, zOffset = -288, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 136, zOffset = 240, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -144, zOffset = -72, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 80, zOffset = 72, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -96, zOffset = 24, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 128, zOffset = -72, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -144, zOffset = -120, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -144, zOffset = 72, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -144, zOffset = -24, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -144, zOffset = 24, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 80, zOffset = -72, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 128, zOffset = 72, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -96, zOffset = -72, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -96, zOffset = -120, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -96, zOffset = 72, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 48, zOffset = 136, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -96, zOffset = -24, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 96, zOffset = -136, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 96, zOffset = 136, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -144, zOffset = 120, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -96, zOffset = 120, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 48, zOffset = -136, direction = 1},
			{ unitDefID = UnitDefNames.legmg_scav.id, xOffset = -72, zOffset = -192, direction = 1},
			{ unitDefID = UnitDefNames.legmg_scav.id, xOffset = -72, zOffset = 256, direction = 1},
			{ unitDefID = UnitDefNames.legmg_scav.id, xOffset = -136, zOffset = 256, direction = 1},
			{ unitDefID = UnitDefNames.legmg_scav.id, xOffset = -8, zOffset = -192, direction = 1},
			{ unitDefID = UnitDefNames.legmg_scav.id, xOffset = -8, zOffset = 192, direction = 1},
			{ unitDefID = UnitDefNames.legmg_scav.id, xOffset = -8, zOffset = 256, direction = 1},
			{ unitDefID = UnitDefNames.legmg_scav.id, xOffset = -72, zOffset = 192, direction = 1},
			{ unitDefID = UnitDefNames.legmg_scav.id, xOffset = -136, zOffset = -256, direction = 1},
			{ unitDefID = UnitDefNames.legmg_scav.id, xOffset = -8, zOffset = -256, direction = 1},
			{ unitDefID = UnitDefNames.legmg_scav.id, xOffset = -136, zOffset = -192, direction = 1},
			{ unitDefID = UnitDefNames.legmg_scav.id, xOffset = -72, zOffset = -256, direction = 1},
			{ unitDefID = UnitDefNames.legmg_scav.id, xOffset = -136, zOffset = 192, direction = 1},
			{ unitDefID = UnitDefNames.armamd_scav.id, xOffset = -200, zOffset = -112, direction = 1},
			{ unitDefID = UnitDefNames.armamd_scav.id, xOffset = -200, zOffset = 112, direction = 1},
			{ unitDefID = UnitDefNames.armgate_scav.id, xOffset = -200, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.armbrtha_scav.id, xOffset = 168, zOffset = 128, direction = 1},
			{ unitDefID = UnitDefNames.armbrtha_scav.id, xOffset = 168, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.armbrtha_scav.id, xOffset = 120, zOffset = -192, direction = 1},
			{ unitDefID = UnitDefNames.armbrtha_scav.id, xOffset = 8, zOffset = -64, direction = 1},
			{ unitDefID = UnitDefNames.armbrtha_scav.id, xOffset = 56, zOffset = 240, direction = 1},
			{ unitDefID = UnitDefNames.armbrtha_scav.id, xOffset = 200, zOffset = -64, direction = 1},
			{ unitDefID = UnitDefNames.armbrtha_scav.id, xOffset = 200, zOffset = 64, direction = 1},
			{ unitDefID = UnitDefNames.armbrtha_scav.id, xOffset = 168, zOffset = -128, direction = 1},
			{ unitDefID = UnitDefNames.armbrtha_scav.id, xOffset = 120, zOffset = 192, direction = 1},
			{ unitDefID = UnitDefNames.armbrtha_scav.id, xOffset = -24, zOffset = 128, direction = 1},
			{ unitDefID = UnitDefNames.armbrtha_scav.id, xOffset = 8, zOffset = 64, direction = 1},
			{ unitDefID = UnitDefNames.armbrtha_scav.id, xOffset = -24, zOffset = -128, direction = 1},
			{ unitDefID = UnitDefNames.armbrtha_scav.id, xOffset = 56, zOffset = -240, direction = 1},
			{ unitDefID = UnitDefNames.armbrtha_scav.id, xOffset = -24, zOffset = 0, direction = 1},
		},
	}
end

local function EpicDefence14()
	return {
		type = types.Land,
		tiers = {tiers.T3, tiers.T4 },
		radius = 344,
		buildings = {
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 169, zOffset = -280, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -151, zOffset = -328, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 9, zOffset = -344, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -151, zOffset = 328, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -55, zOffset = 344, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -119, zOffset = 344, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -87, zOffset = -328, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 9, zOffset = 344, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 41, zOffset = 328, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -23, zOffset = -328, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 137, zOffset = 312, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 265, zOffset = -184, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 137, zOffset = -312, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 73, zOffset = -344, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 233, zOffset = -216, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -183, zOffset = -344, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 169, zOffset = 280, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 265, zOffset = 184, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 201, zOffset = 248, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 41, zOffset = -328, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -119, zOffset = -344, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -55, zOffset = -344, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -183, zOffset = 344, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 105, zOffset = 328, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 201, zOffset = -248, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 105, zOffset = -328, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 73, zOffset = 344, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -23, zOffset = 328, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -87, zOffset = 328, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 233, zOffset = 216, direction = 1},
			{ unitDefID = UnitDefNames.corhllt_scav.id, xOffset = -23, zOffset = -296, direction = 1},
			{ unitDefID = UnitDefNames.corhllt_scav.id, xOffset = -151, zOffset = 296, direction = 1},
			{ unitDefID = UnitDefNames.corhllt_scav.id, xOffset = -87, zOffset = -296, direction = 1},
			{ unitDefID = UnitDefNames.corhllt_scav.id, xOffset = -151, zOffset = -232, direction = 1},
			{ unitDefID = UnitDefNames.corhllt_scav.id, xOffset = -23, zOffset = -232, direction = 1},
			{ unitDefID = UnitDefNames.corhllt_scav.id, xOffset = -23, zOffset = 296, direction = 1},
			{ unitDefID = UnitDefNames.corhllt_scav.id, xOffset = -87, zOffset = 232, direction = 1},
			{ unitDefID = UnitDefNames.corhllt_scav.id, xOffset = -87, zOffset = -232, direction = 1},
			{ unitDefID = UnitDefNames.corhllt_scav.id, xOffset = -23, zOffset = 232, direction = 1},
			{ unitDefID = UnitDefNames.corhllt_scav.id, xOffset = -87, zOffset = 296, direction = 1},
			{ unitDefID = UnitDefNames.corhllt_scav.id, xOffset = -151, zOffset = -296, direction = 1},
			{ unitDefID = UnitDefNames.corhllt_scav.id, xOffset = -151, zOffset = 232, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -111, zOffset = 80, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -111, zOffset = 32, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -159, zOffset = 176, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -159, zOffset = -128, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -111, zOffset = -80, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = 113, zOffset = -160, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = 161, zOffset = -80, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = 161, zOffset = 80, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -111, zOffset = -176, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = 113, zOffset = -80, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -159, zOffset = -32, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -111, zOffset = -128, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = 113, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -159, zOffset = -176, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -159, zOffset = 80, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = 113, zOffset = 160, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -159, zOffset = -80, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -159, zOffset = 32, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -159, zOffset = 128, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -111, zOffset = 176, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = 65, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -111, zOffset = 128, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = 65, zOffset = 160, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = 65, zOffset = -160, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -111, zOffset = -32, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = 113, zOffset = 80, direction = 1},
			{ unitDefID = UnitDefNames.corgate_scav.id, xOffset = -215, zOffset = 40, direction = 1},
			{ unitDefID = UnitDefNames.corfmd_scav.id, xOffset = -215, zOffset = -40, direction = 1},
			{ unitDefID = UnitDefNames.corint_scav.id, xOffset = -15, zOffset = -160, direction = 1},
			{ unitDefID = UnitDefNames.corint_scav.id, xOffset = -15, zOffset = 160, direction = 1},
			{ unitDefID = UnitDefNames.corint_scav.id, xOffset = 33, zOffset = 80, direction = 1},
			{ unitDefID = UnitDefNames.corint_scav.id, xOffset = 193, zOffset = -160, direction = 1},
			{ unitDefID = UnitDefNames.corint_scav.id, xOffset = 33, zOffset = 272, direction = 1},
			{ unitDefID = UnitDefNames.corint_scav.id, xOffset = 113, zOffset = -256, direction = 1},
			{ unitDefID = UnitDefNames.corint_scav.id, xOffset = 113, zOffset = 256, direction = 1},
			{ unitDefID = UnitDefNames.corint_scav.id, xOffset = 193, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.corint_scav.id, xOffset = 193, zOffset = 160, direction = 1},
			{ unitDefID = UnitDefNames.corint_scav.id, xOffset = 241, zOffset = -80, direction = 1},
			{ unitDefID = UnitDefNames.corint_scav.id, xOffset = -15, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.corint_scav.id, xOffset = 241, zOffset = 80, direction = 1},
			{ unitDefID = UnitDefNames.corint_scav.id, xOffset = 33, zOffset = -80, direction = 1},
			{ unitDefID = UnitDefNames.corint_scav.id, xOffset = 33, zOffset = -272, direction = 1},
		},
	}
end

local function EpicDefence15()
	return {
		type = types.Land,
		tiers = {tiers.T3, tiers.T4 },
		radius = 256,
		buildings = {
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 88, zOffset = -256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -136, zOffset = 240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -200, zOffset = -176, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 120, zOffset = -240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 216, zOffset = 32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 120, zOffset = 240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 56, zOffset = -240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 216, zOffset = -32, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -40, zOffset = -256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 24, zOffset = 256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 152, zOffset = -224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 200, zOffset = -160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -200, zOffset = 176, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -216, zOffset = -208, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 200, zOffset = 0, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -72, zOffset = 240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 152, zOffset = 224, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -200, zOffset = 240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 24, zOffset = -256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 200, zOffset = -64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 216, zOffset = 96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 184, zOffset = 192, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -104, zOffset = -256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 200, zOffset = 160, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 88, zOffset = 256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 200, zOffset = 128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 184, zOffset = -192, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -104, zOffset = 256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -216, zOffset = 208, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -8, zOffset = 240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -200, zOffset = -240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -168, zOffset = 256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 200, zOffset = 64, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -136, zOffset = -240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 56, zOffset = 240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -40, zOffset = 256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -8, zOffset = -240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 200, zOffset = -128, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -168, zOffset = -256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 216, zOffset = -96, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -72, zOffset = -240, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -160, zOffset = -120, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -160, zOffset = -24, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -160, zOffset = -72, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -48, zOffset = -184, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -160, zOffset = 24, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -48, zOffset = 184, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 0, zOffset = 184, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = 0, zOffset = -184, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -160, zOffset = 120, direction = 1},
			{ unitDefID = UnitDefNames.armnanotc_scav.id, xOffset = -160, zOffset = 72, direction = 1},
			{ unitDefID = UnitDefNames.corvipe_scav.id, xOffset = 80, zOffset = -184, direction = 1},
			{ unitDefID = UnitDefNames.corvipe_scav.id, xOffset = 80, zOffset = 184, direction = 1},
			{ unitDefID = UnitDefNames.corvipe_scav.id, xOffset = 144, zOffset = -120, direction = 1},
			{ unitDefID = UnitDefNames.corvipe_scav.id, xOffset = 144, zOffset = 120, direction = 1},
			{ unitDefID = UnitDefNames.corflak_scav.id, xOffset = -104, zOffset = 176, direction = 1},
			{ unitDefID = UnitDefNames.corflak_scav.id, xOffset = -104, zOffset = -176, direction = 1},
			{ unitDefID = UnitDefNames.corflak_scav.id, xOffset = -152, zOffset = 176, direction = 1},
			{ unitDefID = UnitDefNames.corflak_scav.id, xOffset = -152, zOffset = -176, direction = 1},
			{ unitDefID = UnitDefNames.corgate_scav.id, xOffset = -8, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.cortron_scav.id, xOffset = -88, zOffset = 112, direction = 1},
			{ unitDefID = UnitDefNames.cortron_scav.id, xOffset = 72, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.cortron_scav.id, xOffset = -8, zOffset = 112, direction = 1},
			{ unitDefID = UnitDefNames.cortron_scav.id, xOffset = -88, zOffset = -112, direction = 1},
			{ unitDefID = UnitDefNames.cortron_scav.id, xOffset = 72, zOffset = 112, direction = 1},
			{ unitDefID = UnitDefNames.cortron_scav.id, xOffset = 72, zOffset = -112, direction = 1},
			{ unitDefID = UnitDefNames.cortron_scav.id, xOffset = -8, zOffset = -112, direction = 1},
			{ unitDefID = UnitDefNames.corfmd_scav.id, xOffset = -88, zOffset = 0, direction = 1},
		},
	}
end

local function EpicDefence16()
	return {
		type = types.Land,
		tiers = {tiers.T3, tiers.T4 },
		radius = 256,
		buildings = {
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -168, zOffset = -256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -200, zOffset = -240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -184, zOffset = 256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 216, zOffset = 112, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 72, zOffset = 256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 40, zOffset = 240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -24, zOffset = 240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 216, zOffset = 48, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -120, zOffset = 256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 200, zOffset = 144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 216, zOffset = -80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 120, zOffset = -240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -152, zOffset = 240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 216, zOffset = -16, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -56, zOffset = 256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -216, zOffset = 240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 104, zOffset = 240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -88, zOffset = 240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -40, zOffset = -256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 152, zOffset = -208, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 56, zOffset = -240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -72, zOffset = -240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 200, zOffset = 16, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 200, zOffset = -48, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -136, zOffset = -240, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -104, zOffset = -256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 8, zOffset = 256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 200, zOffset = 80, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 200, zOffset = -112, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 184, zOffset = -176, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 168, zOffset = 176, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 216, zOffset = -144, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 88, zOffset = -256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 24, zOffset = -256, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = 136, zOffset = 208, direction = 1},
			{ unitDefID = BPWallOrPopup('scav', 1, "land"), xOffset = -8, zOffset = -240, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -64, zOffset = 184, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -64, zOffset = -184, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -176, zOffset = 120, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -176, zOffset = 72, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -16, zOffset = 184, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -176, zOffset = -120, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -176, zOffset = -24, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -16, zOffset = -184, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -176, zOffset = -72, direction = 1},
			{ unitDefID = UnitDefNames.cornanotc_scav.id, xOffset = -176, zOffset = 24, direction = 1},
			{ unitDefID = UnitDefNames.armpb_scav.id, xOffset = 128, zOffset = -120, direction = 1},
			{ unitDefID = UnitDefNames.armpb_scav.id, xOffset = 64, zOffset = -184, direction = 1},
			{ unitDefID = UnitDefNames.armpb_scav.id, xOffset = 128, zOffset = 120, direction = 1},
			{ unitDefID = UnitDefNames.armpb_scav.id, xOffset = 64, zOffset = 184, direction = 1},
			{ unitDefID = UnitDefNames.armflak_scav.id, xOffset = -168, zOffset = 176, direction = 1},
			{ unitDefID = UnitDefNames.armflak_scav.id, xOffset = -120, zOffset = -176, direction = 1},
			{ unitDefID = UnitDefNames.armflak_scav.id, xOffset = -120, zOffset = 176, direction = 1},
			{ unitDefID = UnitDefNames.armflak_scav.id, xOffset = -168, zOffset = -176, direction = 1},
			{ unitDefID = UnitDefNames.armamd_scav.id, xOffset = -104, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.armgate_scav.id, xOffset = -24, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.armemp_scav.id, xOffset = -104, zOffset = 112, direction = 1},
			{ unitDefID = UnitDefNames.armemp_scav.id, xOffset = 56, zOffset = 112, direction = 1},
			{ unitDefID = UnitDefNames.armemp_scav.id, xOffset = 56, zOffset = 0, direction = 1},
			{ unitDefID = UnitDefNames.armemp_scav.id, xOffset = 56, zOffset = -112, direction = 1},
			{ unitDefID = UnitDefNames.armemp_scav.id, xOffset = -24, zOffset = -112, direction = 1},
			{ unitDefID = UnitDefNames.armemp_scav.id, xOffset = -24, zOffset = 112, direction = 1},
			{ unitDefID = UnitDefNames.armemp_scav.id, xOffset = -104, zOffset = -112, direction = 1},
		},
	}
end


return {
	EpicDefence0,
	EpicDefence1,
    EpicDefence2,
	EpicDefence3,
	EpicDefence4,
	EpicDefence5,
    EpicDefence6,
	EpicDefence7,
    EpicDefence8,
	EpicDefence9,
    EpicDefence10,
	EpicDefence11,
	EpicDefence12,
	EpicDefence13,
    EpicDefence14,
	EpicDefence15,
    EpicDefence16,
}