return {
	armafust3 = {
		buildangle = 4096,
		buildpic = "ARMAFUS.DDS",
		buildtime = 2500000,
		canrepeat = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "192 192 192",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		damagemodifier = 0.95,
		energycost = 550000,
		energymake = 30000,
		energystorage = 90000,
		explodeas = "ScavComBossExplo",
		footprintx = 12,
		footprintz = 12,
		health = 7900,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0,
		maxdec = 0,
		maxslope = 13,
		maxwaterdepth = 0,
		metalcost = 90000,
		objectname = "Units/ARMAFUST3.s3o",
		script = "Units/ARMAFUS.cob",
		seismicsignature = 0,
		selfdestructas = "ScavComBossExplo",
		sightdistance = 273,
		yardmap = "oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo",
		customparams = {
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 18,
			buildinggrounddecalsizey = 18,
			buildinggrounddecaltype = "decals/armafus_aoplane.dds",
			model_author = "Cremuss",
			normaltex = "unittextures/Arm_normal.dds",
			removestop = true,
			removewait = true,
			subfolder = "ArmBuildings/LandEconomy",
			techlevel = 3,
			unitgroup = "energy",
			usebuildinggrounddecal = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "192 192 192",
				collisionvolumetype = "Box",
				damage = 16290,
				featuredead = "HEAP",
				footprintx = 5,
				footprintz = 4,
				height = 40,
				metal = 64410,
				object = "Units/armafust3_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "96.0 14.0 6.0",
				collisionvolumetype = "box",
				damage = 8145,
				footprintx = 4,
				footprintz = 4,
				height = 4,
				metal = 25760,
				object = "Units/arm4X4A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "fusion1",
			},
		},
	},
}
