return {
	armhasy = {
		builder = true,
		buildpic = "ARMSHLTXUW.DDS",
		buildtime = 61400,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "256 80 221",
		collisionvolumetype = "Box",
		corpse = "ARMSHLT_DEAD",
		energycost = 58000,
		energystorage = 1400,
		explodeas = "hugeBuildingexplosiongeneric-uw",
		footprintx = 15,
		footprintz = 15,
		health = 16000,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0,
		maxdec = 0,
		maxslope = 10,
		metalcost = 7900,
		metalstorage = 800,
		minwaterdepth = 30,
		objectname = "Units/ARMHASY.s3o",
		script = "Units/ARMHASY.cob",
		seismicsignature = 0,
		selfdestructas = "hugeBuildingExplosionGenericSelfd-uw",
		sightdistance = 273,
		terraformspeed = 3000,
		workertime = 600,
		waterline = 1.5,
		yardmap = "weeeeeeeeeeeeew eeeeeeeeeeeeeee eeeeeeeeeeeeeee eeeeeeeeeeeeeee eeeeeeeeeeeeeee eeeeeeeeeeeeeee eeeeeeeeeeeeeee eeeeeeeeeeeeeee eeeeeeeeeeeeeee eeeeeeeeeeeeeee eeeeeeeeeeeeeee eeeeeeeeeeeeeee eeeeeeeeeeeeeee eeeeeeeeeeeeeee weeeeeeeeeeeeew",
		buildoptions = {
			[1] = "armhacs",
			[2] = "armserp",
			[3] = "armsjam",
			[4] = "armbats",
			[5] = "armepoch",
			[6] = "armantiship",
			[7] = "armbanth",
			[8] = "armmar",
			[9] = "armlun",
			[10] = "armaas"
		},
		customparams = {
			model_author = "FireStorm",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmBuildings/SeaFactories",
			techlevel = 3,
			unitgroup = "buildert3",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "-2 -2 -3",
				collisionvolumescales = "116 52 116",
				collisionvolumetype = "Box",
				damage = 8640,
				featuredead = "HEAP",
				footprintx = 15,
				footprintz = 15,
				height = 20,
				metal = 4807,
				object = "Units/armhasy_dead.s3o",
				reclaimable = true,
			},
		},
		sfxtypes = {
 			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			unitcomplete = "untdone",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "pshpactv",
			},
		},
	},
}
