return {
	armhasy = {
		builder = true,
		buildpic = "ARMSY.DDS",
		buildtime = 9990,
		canmove = true,
		collisionvolumeoffsets = "0 -6 0",
		collisionvolumescales = "128 60 128",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 1240,
		energystorage = 200,
		explodeas = "largeBuildingExplosionGeneric",
		footprintx = 6,
		footprintz = 6,
		health = 4100,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0,
		maxdec = 0,
		metalcost = 1200,
		metalstorage = 200,
		minwaterdepth = 30,
		objectname = "Units/ARMHASY.s3o",
		script = "Units/ARMHASY.cob",
		seismicsignature = 0,
		selfdestructas = "largeBuildingExplosionGenericSelfd",
		sightdistance = 340,
		terraformspeed = 500,
		waterline = 1,
		workertime = 400,
		yardmap = "weeeeeeeeeew eeeeeeeeeeee eeeeeeeeeeee eeeeeeeeeeee eeeeeeeeeeee eeeeeeeeeeee eeeeeeeeeeee eeeeeeeeeeee eeeeeeeeeeee eeeeeeeeeeee eeeeeeeeeeee weeeeeeeeeew",
		buildoptions = {
			[1] = "armhacs",
			[2] = "armmship",
			[3] = "armcrus",
			[4] = "armsubk",
			[5] = "armaas",
			[6] = "armantiship",
			[7] = "armlship",		
		},
		customparams = {
			model_author = "FireStorm",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmBuildings/SeaFactories",
			unitgroup = "builder",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "-2 -2 -3",
				collisionvolumescales = "116 52 116",
				collisionvolumetype = "Box",
				damage = 1794,
				footprintx = 7,
				footprintz = 7,
				height = 4,
				metal = 400,
				object = "Units/armhasy_dead.s3o",
				reclaimable = true,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:YellowLight",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			unitcomplete = "untdone",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "pshpactv",
			},
		},
	},
}
