return {
	scavengerdroppodfriendly = {
		maxacc = 0,
		activatewhenbuilt = true,
		autoheal = 1.8,
		blocking = false,
		maxdec = 0,
		energycost = 10,
		metalcost = 10,
		buildpic = "scavengers/SCAVBEACON.DDS",
		buildtime = 10,
		canmove = false,
		capturable = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "0 0 0",
		collisionvolumetype = "box",
		explodeas = "",
		footprintx = 0,
		footprintz = 0,
		idleautoheal = 10,
		idletime = 90,
		levelground = false,
		mass = 10,
		health = 11,
		speed = 0.0,
		noautofire = false,
		objectname = "scavs/cube.s3o",
		script = "scavs/droppod.cob",
		seismicsignature = 4,
		selfdestructas = "",
		selfdestructcountdown = 0,
		smoothanim = true,
		turninplace = true,
		turninplaceanglelimit = 90,
		turnrate = 0,
		unitname = "scavengerfriendlydroppod",
		upright = false,
		waterline = 0,
		yardmap = "",
		customparams = {
			isairbase = true,
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "other/scavengers",
		},
		featuredefs = {},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:dirtpoof",
			},
		},
		weapondefs = {
			weapon = {
				alwaysvisible = true,
				areaofeffect = 0,
				avoidfriendly = 0,
				cegtag = "scaspawn-greentrail",
				collidefriendly = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.3,
				explosiongenerator = "custom:dirtpoof",
				firestarter = 70,
				flighttime = 250,
				impulsefactor = 0.1,
				interceptedbyshieldtype = 4,
				metalpershot = 0,
				model = "scavs/scavbeacondroppodbyar.s3o",
        mygravity = 0.1, -- to ensure consistent speed
				name = "Droppod",
				range = 29999,
				reloadtime = 5,
				rgbcolor = "0 1 0",
				smoketrail = 1,
				soundhit = "scavspawn",
				startvelocity = 2000, -- === weaponvelocity to ensure consistent speed
				targetborder = 0.75,
				turret = 1,
				weaponacceleration = 450,
				weapontimer = 2,
				weapontype = "MissileLauncher",
				weaponvelocity = 2000, -- elmos/sec
				wobble = 50,
				damage = {
					raptor = 0,
					default = 0,
				},
			},
		},
		weapons = {
			[1] = {
				def = "WEAPON",
			},
		},
	},
}
