return {
	corphantom = {
		activatewhenbuilt = true,
		buildpic = "CORPHANTOM.DDS",
		buildtime = 9000,
		canmove = true,
		cloakcost = 10,
		cloakcostmoving = 30,
		collisionvolumeoffsets = "0 -4 0",
		collisionvolumescales = "30 18 36",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 4500,
		explodeas = "smallexplosiongeneric",
		footprintx = 2,
		footprintz = 2,
		health = 1400,
		idleautoheal = 5,
		idletime = 1800,
		leavetracks = false,
		maxacc = 0.0697,
		maxdec = 0.13939,
		maxslope = 12,
		maxwaterdepth = 0,
		metalcost = 300,
		mincloakdistance = 50,
		movementclass = "ATANK3",
		movestate = 0,
		nochasecategory = "VTOL",
		objectname = "Units/corphantom.s3o",
		radardistance = 1000,
		radaremitheight = 25,
		script = "Units/corphantom_clean.cob",
		seismicsignature = 4,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 650,
		sonardistance = 350,
		speed = 72,
		stealth = true,
		trackstrength = 6,
		tracktype = "corwidetracks",
		trackwidth = 29,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.64802,
		turnrate = 701.79999,
		customparams = {
			basename = "base",
			model_author = "Hornet",
			normaltex = "unittextures/cor_normal.dds",
			paralyzemultiplier = 1,
			subfolder = "CorVehicles/T2",
			techlevel = 2,
			unitgroup = "util",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 -4 0",
				collisionvolumescales = "30 18 36",
				collisionvolumetype = "Box",
				damage = 700,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 15,
				metal = 85,
				object = "Units/corphantom_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 350,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 85,
				object = "Units/cor2X2E.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "tarmmove",
			},
			select = {
				[1] = "tarmsel",
			},
		},
	},
}
