return {
	lootboxsilver = {
		maxacc = 0,
		activatewhenbuilt = true,
		autoheal = 1,
		maxdec = 1,
		energycost = 25000,
		metalcost = 750,
		buildpic = "lootboxes/LOOTBOXSILVER.DDS",
		buildtime = 1000,
		canfight = false,
		canguard = false,
		canmove = true,
		canpatrol = false,
		canrepeat = false,
		canselfdestruct = true,
		canstop = false,
		cantbetransported = false,
		capturable = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "48 48 48",
		collisionvolumetype = "box",
		energymake = 800,
		explodeas = "lootboxExplosion2",
		floater = true,
		footprintx = 3,
		footprintz = 3,
		idleautoheal = 10,
		idletime = 1800,
		levelground = false,
		mass = 749,
		health = 44500,
		maxslope = 10,
		speed = 0.03,
		maxwaterdepth = 0,
		metalmake = 40,
		movementclass = "HOVER3",
		movestate = 0,
		noautofire = false,
		objectname = "lootboxes/lootboxv2_silver.s3o",
		script = "lootboxes/lootboxv2.cob",
		seismicsignature = 0,
		selfdestructas = "lootboxExplosion2",
		selfdestructcountdown = 9,
		sightdistance = 96,
		transportbyenemy = true,
		turninplace = false,
		turnrate = 0,
		unitname = "lootboxsilver",
		upright = true,
		usebuildinggrounddecal = false,
		reclaimable = false,
		customparams = {
			fall_damage_multiplier = 0,
			unitgroup = 'energy',
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "other/lootboxes",
			paratrooper = true,
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:LootboxLightGold",
				[2] = "custom:LootboxBeaconSilver",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg4",
			},
		},
	},
}
