return {
	legfhp = {
		maxacc = 0,
		maxdec = 0,
		energycost = 2750,
		metalcost = 750,
		builder = true,
		buildpic = "LEGFHP.DDS",
		buildtime = 9500,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "96 35 96",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energystorage = 200,
		explodeas = "largeBuildingexplosiongeneric",
		footprintx = 6,
		footprintz = 6,
		idleautoheal = 5,
		idletime = 1800,
		health = 3750,
		metalstorage = 200,
		minwaterdepth = 5,
		objectname = "Units/legfhp.s3o",
		script = "Units/legfhp.cob",
		seismicsignature = 0,
		selfdestructas = "largeBuildingExplosionGenericSelfd",
		sightdistance = 312,
		terraformspeed = 1000,
		waterline = 4,
		workertime = 150,
		yardmap = "weeeew weeeew weeeew weeeew weeeew weeeew",
		buildoptions = {
			[1] = "legch",
			[2] = "legsh",
			[3] = "legner",
			[4] = "legah",
			[5] = "legmh",
			[6] = "legcar",
		},
		customparams = {
			unitgroup = 'builder',
			model_author = "Protar, ZephyrSkies",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/Labs",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "96 35 96",
				collisionvolumetype = "Box",
				damage = 2014,
				footprintx = 8,
				footprintz = 7,
				height = 20,
				metal = 715,
				object = "Units/legfhp_dead.s3o",
				reclaimable = true,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			build = "hoverok2",
			canceldestruct = "cancel2",
			underattack = "warning1",
			unitcomplete = "untdone",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "hoversl2",
			},
		},
	},
}
