return {
  chicken_egg =
  {
    description = "Egg",
    blocking = 0,
    category = "corpses",
    damage = 2000,
    energy = 250,
    featurereclamate = "SMUDGE01",
    footprintx = 1,
    footprintz = 1,
    height = 30,
    hitdensity = 999999,
    metal = 25,
    object = "ChickenDefenseModels/chickenegg.s3o",
    reclaimable = 1,
    seqnamereclamate = "TREE1RECLAMATE",
    world = "All Worlds",
  },
  chicken_eggb =
  {
    description = "Egg",
    blocking = 0,
    category = "corpses",
    damage = 2000,
    energy = 250,
    featurereclamate = "SMUDGE01",
    footprintx = 1,
    footprintz = 1,
    height = 30,
    hitdensity = 999999,
    metal = 25,
    object = "ChickenDefenseModels/chickeneggb.s3o",
    reclaimable = 1,
    seqnamereclamate = "TREE1RECLAMATE",
    world = "All Worlds",
  },
  chicken_eggc =
  {
    description = "Egg",
    blocking = 0,
    category = "corpses",
    damage = 2000,
    energy = 250,
    featurereclamate = "SMUDGE01",
    footprintx = 1,
    footprintz = 1,
    height = 30,
    hitdensity = 999999,
    metal = 25,
    object = "ChickenDefenseModels/chickeneggc.s3o",
    reclaimable = 1,
    seqnamereclamate = "TREE1RECLAMATE",
    world = "All Worlds",
  },
  chicken_eggd =
  {
    description = "Egg",
    blocking = 0,
    category = "corpses",
    damage = 2000,
    energy = 250,
    featurereclamate = "SMUDGE01",
    footprintx = 1,
    footprintz = 1,
    height = 30,
    hitdensity = 999999,
    metal = 25,
    object = "ChickenDefenseModels/chickeneggd.s3o",
    reclaimable = 1,
    seqnamereclamate = "TREE1RECLAMATE",
    world = "All Worlds",
  },
}