return {
	armhacv = {
		builddistance = 136,
		builder = true,
		buildpic = "ARMCONSUL.DDS",
		buildtime = 6800,
		canmove = true,
		collisionvolumeoffsets = "0 0 -3",
		collisionvolumescales = "32 30 30",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 4300,
		energymake = 15,
		energystorage = 100,
		explodeas = "smallexplosiongeneric-builder",
		footprintx = 3,
		footprintz = 3,
		health = 1080,
		idleautoheal = 5,
		idletime = 1800,
		leavetracks = true,
		maxacc = 0.07029,
		maxdec = 0.14059,
		maxslope = 18,
		maxwaterdepth = 18,
		metalcost = 250,
		movementclass = "TANK2",
		objectname = "Units/ARMCONSUL.s3o",
		script = "Units/ARMCONSUL.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd-builder",
		sightdistance = 500,
		speed = 78,
		terraformspeed = 750,
		trackoffset = 10,
		trackstrength = 5,
		tracktype = "armgremlin_tracks",
		trackwidth = 35,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.83678,
		turnrate = 635,
		workertime = 150,
		buildoptions = {
				[1] = "armadvsol",
				[2] = "armamex",
				[3] = "armbeamer",
				[4] = "armhlt",
				[5] = "armguard",
				[6] = "armferret",
				[7] = "armcir",
				[8] = "armjuno",
				[9] = "armclaw",
				[10] = "armarad",
				[11] = "armfus",
				[12] = "armgmm",
				[13] = "armhalab",
				[14] = "armlab",
				[15] = "armalab"
		},
		customparams = {
			model_author = "FireStorm",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmVehicles/T2",
			techlevel = 2,
			unitgroup = "buildert2",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 -3",
				collisionvolumescales = "32 30 30",
				collisionvolumetype = "Box",
				damage = 800,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				metal = 153,
				object = "Units/armconsul_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 700,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 61,
				object = "Units/arm3X3A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2-builder",
				[2] = "deathceg3-builder",
				[3] = "deathceg4-builder",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "tarmmove",
			},
			select = {
				[1] = "tarmsel",
			},
		},
	},
}
