return {
	legnavyscout = {
		maxacc = 0.08,
		maxdec = 0.08,
		buildangle = 16384,
		energycost = 1600,
		metalcost = 120,
		buildpic = "legnavyscout.DDS",
		buildtime = 1800,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "20 20 41",
		collisionvolumetype = "CylZ",
		corpse = "DEAD",
		explodeas = "mediumexplosiongeneric",
		floater = true,
		footprintx = 3,
		footprintz = 3,
		idleautoheal = 5,
		idletime = 1800,
		health = 700,
		speed = 93,
		minwaterdepth = 12,
		movementclass = "BOAT3",
		nochasecategory = "UNDERWATER VTOL",
		objectname = "Units/legnavyscout.s3o",
		script = "Units/legnavyscout.cob",
		seismicsignature = 0,
		selfdestructas = "mediumexplosiongenericSelfd",
		sightdistance = 600,
		turninplace = true,
		turninplaceanglelimit = 90,
		turnrate = 430,
		waterline = 0,
		customparams = {
			unitgroup = 'weapon',
			model_author = "ZephyrSkies (model), Phill-Art (Concept)",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/Ships",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
                collisionvolumeoffsets = "0 0 0",
                collisionvolumescales = "20 16 41",
				collisionvolumetype = "Box",
				damage = 300,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				metal = 82.5,
				object = "Units/legnavyscout_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "85.0 14.0 6.0",
				collisionvolumetype = "cylY",
				damage = 500,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 41.25,
				object = "Units/arm4X4B.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-tiny",
				[2] = "custom:waterwake-small-long",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "sharmmov",
			},
			select = {
				[1] = "sharmsel",
			},
		},
		weapondefs = {
			mg_guns = {
				accuracy = 7,
				areaofeffect = 16,
				avoidfeature = false,
				burst = 2,
				burstrate = 0.1,
				burnblow = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.04,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:plasmahit-sparkonly",
				fallOffRate = 0.2,
				firestarter = 0,
				impulsefactor = 1.5,
				intensity = 0.8,
				name = "Twin Rapid-fire Machine Guns",
				noselfdamage = true,
				ownerExpAccWeight = 4.0,
				proximitypriority = 1,
				range = 351,
				reloadtime = 0.4,
				rgbcolor = "1 0.95 0.4",
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "mgun2",
				soundstartvolume = 6.0,
				soundtrigger = true,
				sprayangle = 800,
				texture1 = "shot",
				texture2 = "empty",
				thickness = 3,
				tolerance = 16000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 1050,
				damage = {
					default = 12,
					vtol = 6,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory="vtol",
				def = "mg_guns",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}