return {
	legnavyconship = {
		builddistance = 200,
		builder = true,
		buildpic = "legnavyconship.DDS",
		buildtime = 3700,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "42 33 50",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 2000,
		energymake = 7,
		energystorage = 50,
		explodeas = "mediumexplosiongeneric-builder",
		floater = true,
		footprintx = 3,
		footprintz = 3,
		health = 1080,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.03567,
		maxdec = 0.03567,
		metalcost = 200,
		minwaterdepth = 15,
		movementclass = "BOAT3",
		objectname = "Units/legnavyconship.s3o",
		script = "Units/legnavyconship.cob",
		seismicsignature = 0,
		selfdestructas = "mediumexplosiongenericSelfd-builder",
		sightdistance = 400,
		speed = 60,
		terraformspeed = 1250,
		turninplace = true,
		turninplaceanglelimit = 90,
		turnrate = 391.5,
		waterline = 0,
		workertime = 125,
		buildoptions = {
			[1] = "legmex",
			[2] = "legvp",
			[3] = "legap",
			[4] = "leglab",
			[5] = "legeyes",
			[6] = "legctl",
			[7] = "legdrag",
			[8] = "legdtr",
			[9] = "legcluster",
			[10] = "legtide",
			[11] = "leggeo",
			[12] = "leguwgeo",
			[13] = "legfeconv",
			[14] = "leguwmstore",
			[15] = "leguwestore",
			[16] = "legsy",
			[17] = "corasy",
			[18] = "legnanotcplat",
			[19] = "legfhp",
			[20] = "legamphlab",
			[21] = "corplat",
			[22] = "legfrad",
			[23] = "legfdrag",
			[24] = "legtl",
			[25] = "legfrl",
			[26] = "legfmg",
            [27] = "legmext15",
		},
		customparams = {
			model_author = "ZephyrSkies (Model), Phill-Arts (Concept Art)",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/Ships",
			unitgroup = "builder",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
                collisionvolumeoffsets = "0 0 0",
                collisionvolumescales = "42 30 50",
				collisionvolumetype = "Box",
				damage = 1380,
				featuredead = "HEAP",
				footprintx = 5,
				footprintz = 5,
				height = 4,
				metal = 100,
				object = "Units/legnavyconship_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 4032,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 50,
				object = "Units/cor5X5C.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:waterwake-small",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2-builder",
				[2] = "deathceg3-builder",
				[3] = "deathceg4-builder",
			},
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			repair = "repair2",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "shcormov",
			},
			select = {
				[1] = "shcorsel",
			},
		},
	},
}
