return {
	legnavysub = {
		activatewhenbuilt = true,
		autoheal = 2,
		buildpic = "legnavysub.DDS",
		buildtime = 4800,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "26 16 36",
		collisionvolumetype = "box",
		corpse = "DEAD",
		energycost = 2600,
		explodeas = "smallExplosionGeneric-uw",
		footprintx = 3,
		footprintz = 3,
		health = 640,
		idleautoheal = 8,
		idletime = 900,
		maxacc = 0.0451,
		maxdec = 0.0451,
		metalcost = 340,
		minwaterdepth = 15,
		movementclass = "UBOAT4",
		nochasecategory = "VTOL",
		objectname = "Units/legnavysub.s3o",
		script = "Units/legnavysub.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd-uw",
		sightdistance = 400,
		sonardistance = 400,
		speed = 54,
		turninplace = true,
		turninplaceanglelimit = 90,
		turnrate = 520,
		upright = true,
		waterline = 45,
		customparams = {
			model_author = "Tharsis",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "Legion/Ships",
			unitgroup = "sub",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "0.0 0.0 0.0",
				collisionvolumescales = "25 12.5 50",
				collisionvolumetype = "Box",
				damage = 1002,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 265,
				object = "Units/legnavysub_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "85.0 14.0 6.0",
				collisionvolumetype = "cylY",
				damage = 4032,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 132.5,
				object = "Units/cor4X4B.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[0] = "custom:subbubbles",
				[1] = "custom:subwake",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "sucormov",
			},
			select = {
				[1] = "sucorsel",
			},
		},
		weapondefs = {
			leg_torpedo_launcher = {
				areaofeffect = 32,
				avoidfeature = false,
				avoidfriendly = true,
				burnblow = true,
				cegtag = "torpedotrail-tiny",
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-small-uw",
				flighttime = 3,
				impulsefactor = 0.123,
				model = "legtorpedomini.s3o",
				name = "Submerged Torpedo Launcher",
				noselfdamage = true,
				predictboost = 1,
				range = 400,
				reloadtime = 1.5,
				soundhit = "xplodep1",
				soundhitvolume = 10,
				soundstart = "torpedo1",
				startvelocity = 130,
				tolerance = 12000,
				turnrate = 12000,
				turret = false,
				waterweapon = true,
				weaponacceleration = 15,
				weapontimer = 3.25,
				weapontype = "TorpedoLauncher",
				weaponvelocity = 200,
				damage = {
					default = 140,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "NOTSHIP",
				def = "leg_torpedo_launcher",
				maindir = "0 0 1",
				maxangledif = 90,
				onlytargetcategory = "NOTHOVER",
			},
		},
	},
}
