-- comm_explosion

return {
  ["comm_explosion"] = {
    dirt = {
      count              = 4,
      ground             = true,
      properties = {
        alphafalloff       = 2,
        alwaysvisible      = true,
        color              = [[0.2, 0.1, 0.05]],
        pos                = [[r-10 r10, 0, r-10 r10]],
        size               = 20,
        speed              = [[r1.5 r-1.5, 2, r1.5 r-1.5]],
      },
    },
    dirt2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.9,
        alwaysvisible      = true,
        colormap           = [[1 1 1 0.01	0.5 0.3 0.0 0.05    0.5 0.5 0.5 1.0    0 0 0 0.01]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = 10,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.2, 0]],
        numparticles       = 50,
        particlelife       = 70,
        particlelifespread = 0,
        particlesize       = 100,
        particlesizespread = 10,
        particlespeed      = 5,
        particlespeedspread = 57,
        pos                = [[r-1 r1, r-1 r1, r-1 r1]],
        sizegrowth         = 3,
        sizemod            = 1.0,
        texture            = [[dirt]],
        useairlos          = true,
      },
    },
    groundflash = {
      air                = true,
      alwaysvisible      = true,
      circlealpha        = 0.5,
      circlegrowth       = 8,
      flashalpha         = 0.9,
      flashsize          = 120,
      ground             = true,
      ttl                = 17,
      water              = true,
      color = {
        [1]  = 0,
        [2]  = 0.30000001192093,
        [3]  = 1,
      },
    },
    pop1 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 2,
      ground             = true,
      water              = true,
      properties = {
        alwaysvisible      = true,
        heat               = 10,
        heatfalloff        = 0.4,
        maxheat            = 10,
        pos                = [[r-10 r10, 0, r-10 r10]],
        size               = 1,
        sizegrowth         = 37,
        speed              = [[0, 0, 0]],
        texture            = [[bluenovaexplo]],
      },
    },
    pop2 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 5,
      ground             = true,
      water              = true,
      properties = {
        alwaysvisible      = true,
        heat               = 10,
        heatfalloff        = 0.6,
        maxheat            = 15,
        pos                = [[r-150 r150, 0, r-300 r150]],
        size               = 1,
        sizegrowth         = 30,
        speed              = [[0, 0, 0]],
        texture            = [[brightblueexplo]],
      },
    },
  },

}

