-- cruisemissiletrail

local definitions = {
	["cruisemissiletrail"] = {
    groundflash = {
      circlealpha        = 0,
      circlegrowth       = 0,
      flashalpha         = 0.13,
      flashsize          = 90,
      ttl                = 10,
      color = {
        [1]  = 0.80000001192093,
        [2]  = 0.50000000149012,
        [3]  = 0.15,
      },
    },
    smokeandfire = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        alwaysvisible      = true,
        colormap           = [[0.66 0.55 0.4 0.22   0.58 0.4 0.08 0.28    0.5 0.14 0 0.24    0.16 0.02 0 0.16    0.07 0.005 0 0.09   0.03 0.003 0 0.05	 0 0 0 0.01]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = 5,
        emitvector         = [[0.0, 1, 0.0]],
        gravity            = [[0.0, 0.1, 0.0]],
        numparticles       = 3,
        particlelife       = 30,
        particlelifespread = 44,
        particlesize       = 15,
        particlesizespread = 7,
        particlespeed      = 1.5,
        particlespeedspread = 1,
        pos                = [[0.0, 2, 0.0]],
        sizegrowth         = -0.01,
        sizemod            = 0.9,
        texture            = [[dirt]],
        useairlos          = true,
      },
    },
    searingflame = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = true,
        colormap           = [[0.9 0.5 0.4 0.04   0.9 0.4 0.1 0.01  0.5 0.1 0.1 0.01]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.01, 0]],
        numparticles       = 6,
        particlelife       = 3,
        particlelifespread = 9,
        particlesize       = 15,
        particlesizespread = 9,
        particlespeed      = 1,
        particlespeedspread = 1.2,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 0.8,
        texture            = [[gunshot]],
        useairlos          = false,
      },
    },
    exhale4 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.7,
        alwaysvisible      = true,
        colormap           = [[0.03 0.03 0.03 0.27	   0.11 0.11 0.11 0.24   0.11 0.11 0.11 0.14    0.03 0.03 0.03 0.07    0 0 0 0.01]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = 5,
        emitvector         = [[0.0, 1, 0.0]],
        gravity            = [[0.0, -0.07, 0.0]],
        numparticles       = 1,
        particlelife       = 150,
        particlelifespread = 70,
        particlesize       = 12,
        particlesizespread = 12,
        particlespeed      = 1.5,
        particlespeedspread = 1,
        pos                = [[0.0, 1, 0.0]],
        sizegrowth         = 0.12,
        sizemod            = 0.99,
        texture            = [[dirt]],
        useairlos          = true,
      },
    },
    exhale5 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.7,
        alwaysvisible      = true,
        colormap           = [[0.03 0.03 0.03 0.03  0.07 0.07 0.07 0.17  0.075 0.075 0.075 0.1   0 0 0 0]],
        directional        = true,
        emitrot            = 4,
        emitrotspread      = 4,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.04, 0]],
        numparticles       = 1,
        particlelife       = 150,
        particlelifespread = 70,
        particlesize       = 10,
        particlesizespread = 7,
        particlespeed      = 1.5,
        particlespeedspread = 1.2,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.1,
        sizemod            = 1,
        texture            = [[bigexplosmoke]],
      },
    },
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.77,
        colormap           = [[0.1 0.1 0.1 0.22		0.3 0.3 0.3 0.22		0.2 0.2 0.2 0.11		0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 2,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 140,
        particlelifespread = 50,
        particlesize       = 16,
        particlesizespread = 6,
        particlespeed      = 1.5,
        particlespeedspread = 1,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.12,
        sizemod            = 0.8,
        texture            = [[smoke]],
      },
    },
		coreflame2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = false,
      underwater         = true,
      water              = true,
      properties = {
        airdrag            = 0.77,
        colormap           = [[0 0 0 0   0.2 0.2 0.2 0.018  0.15 0.15 0.15 0.014  0.1 0.1 0.1 0.009    0.05 0.05 0.05 0.005  0 0 0 0]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 1,
        particlelife       = 100,
        particlelifespread = 40,
        particlesize       = 11,
        particlesizespread = 2,
        particlespeed      = 1,
        particlespeedspread = 1,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.1,
        sizemod            = 1.0,
        texture            = [[randomdots]],
      },
    },
 	},
}



function deepcopy(orig)
    local orig_type = type(orig)
    local copy
    if orig_type == 'table' then
        copy = {}
        for orig_key, orig_value in next, orig, nil do
            copy[deepcopy(orig_key)] = deepcopy(orig_value)
        end
        setmetatable(copy, deepcopy(getmetatable(orig)))
    else -- number, string, boolean, etc
        copy = orig
    end
    return copy
end

definitions["cruisemissiletrail-emp"] = deepcopy(definitions["cruisemissiletrail"])
definitions["cruisemissiletrail-emp"].smokeandfire2 = {
  air                = true,
  class              = [[CSimpleParticleSystem]],
  count              = 1,
  ground             = true,
  water              = true,
  properties = {
    airdrag            = 0.6,
    alwaysvisible      = true,
    colormap           = [[0 0 0.33 0.3  0 0 0 0.01]],
    directional        = true,
    emitrot            = 90,
    emitrotspread      = 5,
    emitvector         = [[0.0, 1, 0.0]],
    gravity            = [[0.0, 0.1, 0.0]],
    numparticles       = 2,
    particlelife       = 16,
    particlelifespread = 32,
    particlesize       = 17,
    particlesizespread = 10,
    particlespeed      = 1.5,
    particlespeedspread = 1,
    pos                = [[0.0, 1, 0.0]],
    sizegrowth         = -0.02,
    sizemod            = 0.9,
    texture            = [[dirt]],
    useairlos          = true,
  },
}
definitions["cruisemissiletrail-tacnuke"] = deepcopy(definitions["cruisemissiletrail"])
definitions["cruisemissiletrail-tacnuke"].smokeandfire2 = {
  air                = true,
  class              = [[CSimpleParticleSystem]],
  count              = 1,
  ground             = true,
  water              = true,
  properties = {
    airdrag            = 0.6,
    alwaysvisible      = true,
    colormap           = [[0.33 0 0 0.3  0 0 0 0.01]],
    directional        = true,
    emitrot            = 90,
    emitrotspread      = 5,
    emitvector         = [[0.0, 1, 0.0]],
    gravity            = [[0.0, 0.1, 0.0]],
    numparticles       = 2,
    particlelife       = 16,
    particlelifespread = 32,
    particlesize       = 17,
    particlesizespread = 10,
    particlespeed      = 1.5,
    particlespeedspread = 1,
    pos                = [[0.0, 1, 0.0]],
    sizegrowth         = -0.02,
    sizemod            = 0.9,
    texture            = [[dirt]],
    useairlos          = true,
  },
}

return definitions