-- f3mech
-- f3

return {
  ["f3mech"] = {
    searingflame = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 1,
        colormap           = [[0.1 0.1 0.1 0.01    1 0.5 0.5 0.01    1 0.5 0.5 0.01    1 0.5 0.5 0.01    1 0.5 0.5 0.01    1 0.5 0.5 0.01    0.5 0.1 1 0.01    0 0 0 0.01]],
        directional        = true,
        emitrot            = 3,
        emitrotspread      = 1,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 3,
        particlelife       = 75,
        particlelifespread = 5,
        particlesize       = 15,
        particlesizespread = 4,
        particlespeed      = 2,
        particlespeedspread = 10,
        pos                = [[0, 0, 0]],
        sizegrowth         = 1,
        sizemod            = 1,
        texture            = [[fire]],
        useairlos          = true,
      },
    },
    searingflame2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 1,
        colormap           = [[0.1 0.1 0.1 0.01    1 0.4 0.4 0.01    1 0.4 0.4 0.01    1 0.4 0.4 0.01    1 0.4 0.4 0.01    1 0.4 0.4 0.01    0.5 0.1 1 0.01    0 0 0 0.01]],
        directional        = true,
        emitrot            = 3,
        emitrotspread      = 1,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 3,
        particlelife       = 75,
        particlelifespread = 5,
        particlesize       = 10,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 10,
        pos                = [[0, 0, 0]],
        sizegrowth         = 1,
        sizemod            = 1,
        texture            = [[flashside2]],
        useairlos          = true,
      },
    },
    whiteglow = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        heat               = 5,
        heatfalloff        = 1,
        maxheat            = 15,
        pos                = [[0, 0, 0]],
        size               = 5,
        sizegrowth         = 10,
        speed              = [[0, 0, 0]],
        texture            = [[laserend]],
      },
    },
  },

  ["f3"] = {
    searingflame = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[0.1 0.1 0.1 0.01    0.5 0.5 1 0.01    0.8 0.3 0.1 0.01    0 0 0 0.01]],
        directional        = true,
        emitrot            = 3,
        emitrotspread      = 1,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 10,
        particlelife       = 50,
        particlelifespread = 0,
        particlesize       = 2,
        particlesizespread = 1,
        particlespeed      = 8,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.5,
        sizemod            = 1,
        texture            = [[fire]],
        useairlos          = true,
      },
    },
    searingflame2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[0.1 0.1 0.1 0.01    0.4 0.4 1 0.01    0.8 0.3 0.1 0.01    0 0 0 0.01]],
        directional        = true,
        emitrot            = 3,
        emitrotspread      = 1,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 10,
        particlelife       = 50,
        particlelifespread = 5,
        particlesize       = 2,
        particlesizespread = 0,
        particlespeed      = 8,
        particlespeedspread = 3,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.5,
        sizemod            = 1,
        texture            = [[flashside2]],
        useairlos          = true,
      },
    },
    whiteglow = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        heat               = 5,
        heatfalloff        = 1,
        maxheat            = 15,
        pos                = [[0, 0, 0]],
        size               = 2,
        sizegrowth         = 5,
        speed              = [[0, 0, 0]],
        texture            = [[laserend]],
      },
    },
  },

}

