-- nukedatbewm

return {
  ["nukedatbewm"] = {
    alwaysvisible      = true,
    groundflash = {
      air                = true,
      ground             = true,
		  water		           = true,
	 		underwater		     = true,
      alwaysvisible      = true,
      flashalpha         = 0.4,
      flashsize          = 680,
      ground             = true,
      ttl                = 120,
      water              = true,
      color = {
        [1]  = 1,
        [2]  = 0.88,
        [3]  = 0.5,
      },
    },
    explosion = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true, 
	 	  underwater         = true,
      properties = {
        airdrag            = 0.88,
        alwaysvisible      = true,
        colormap           = [[0.8 0.3 0.1 0.06    1 0.5 0.15 0.15      0.75 0.16 0.05 0.06     0.6 0.12 0.02 0.03   0 0 0 0]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = -15,
        emitvector         = [[0, 1.24, 0]],
        gravity            = [[0, 0.05, 0]],
        numparticles       = 60,
        particlelife       = 22,
        particlelifespread = 44,
        particlesize       = 25,
        particlesizespread = 10,
        particlespeed      = 0.6,
        particlespeedspread = 5.5,
        pos                = [[0, 49, 0]],
        sizegrowth         = 1.5,
        sizemod            = 1,
        texture            = [[flashside2]],
        useairlos          = false,
      },
    },
    dustcloud = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = false,
	  	water        			 = false,
      properties = {
        airdrag            = 0.97,
        alwaysvisible      = true,
        colormap           = [[0.12 0.12 0.12 0.2   0.045 0.045 0.045 0.11      0.035 0.035 0.035 0.07   0.025 0.025 0.025 0.04   0 0 0 0.0]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = -7,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.015, 0]],
        numparticles       = 50,
        particlelife       = 120,
        particlelifespread = 400,
        particlesize       = 50,
        particlesizespread = 70,
        particlespeed      = 0.6,
        particlespeedspread = 7,
        pos                = [[0, 50, 0]],
        sizegrowth         = 0.3,
        sizemod            = 1.0,
        texture            = [[bigexplosmoke]],
      },
    },
    dustcloud = {
      air                = false,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  	water        			 = true,
      properties = {
        airdrag            = 0.96,
        alwaysvisible      = true,
        colormap           = [[0.16 0.125 0.06 0.2   0.065 0.05 0.025 0.11      0.05 0.04 0.015 0.07   0.031 0.024 0.006 0.04   0 0 0 0.0]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = -7,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.015, 0]],
        numparticles       = 50,
        particlelife       = 180,
        particlelifespread = 440,
        particlesize       = 66,
        particlesizespread = 100,
        particlespeed      = 1.2,
        particlespeedspread = 8,
        pos                = [[0, 50, 0]],
        sizegrowth         = 0.3,
        sizemod            = 1.0,
        texture            = [[bigexplosmoke]],
      },
    },
    grounddust = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.955,
        alwaysvisible      = true,
        colormap           = [[0.21 0.16 0.08 0.2 	0 0 0 0.0]],
        directional        = false,
        emitrot            = 90,
        emitrotspread      = 20,
        emitvector         = [[0, 1.22, 0]],
        gravity            = [[0, 0.1, 0]],
        numparticles       = 100,
        particlelife       = 40,
        particlelifespread = 80,
        particlesize       = 15,
        particlesizespread = 3,
        particlespeed      = 7,
        particlespeedspread = 1,
        pos                = [[0, 15, 0]],
        sizegrowth         = 0.25,
        sizemod            = 1.0,
        texture            = [[bigexplosmoke]],
      },
    },
    sparks = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.99,
        alwaysvisible      = true,
        colormap           = [[0.9 0.5 0.2 0.022   0.5 0.3 0.1 0.013   0.04 0.03 0.01 0.09   c0 0 0 0]],
        directional        = true,
        emitrot            = 45,
        emitrotspread      = 10,
        emitvector         = [[0, 1.33, 0]],
        gravity            = [[0, -0.2, 0]],
        numparticles       = 160,
        particlelife       = 130,
        particlelifespread = 130,
        particlesize       = 6,
        particlesizespread = 5,
        particlespeed      = 2.2,
        particlespeedspread = 5.5,
        pos                = [[0, 4, 0]],
        sizegrowth         = -0.015,
        sizemod            = 1,
        texture            = [[gunshot]],
        useairlos          = false,
      },
    },
    dirt = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  	water        			 = true,
	  	air        			   = false,
      properties = {
        airdrag            = 0.97,
        alwaysvisible      = true,
        colormap           = [[0.04 0.03 0.01 0.05   0.1 0.07 0.033 0.66    0.02 0.02 0.2 0.4   0.08 0.065 0.035 0.55   0.075 0.07 0.06 0.4   0 0 0 0  ]],
        directional        = true,
        emitrot            = 55,
        emitrotspread      = 20,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.36, 0]],
        numparticles       = 250,
        particlelife       = 30,
        particlelifespread = 160,
        particlesize       = 3.5,
        particlesizespread = -2.5,
        particlespeed      = 6.5,
        particlespeedspread = 12,
        pos                = [[0, 6, 0]],
        sizegrowth         = -0.04,
        sizemod            = 1,
        texture            = [[bigexplosmoke]],
        useairlos          = false,
      },
    },
    dirtbig = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
	  	water        			 = true,
	  	underwater         = true,
      properties = {
        airdrag            = 0.97,
        alwaysvisible      = true,
        colormap           = [[0.04 0.03 0.01 0.05   0.1 0.07 0.033 0.66    0.02 0.02 0.2 0.4   0.08 0.065 0.035 0.55   0.075 0.07 0.06 0.4   0 0 0 0  ]],
        directional        = true,
        emitrot            = 55,
        emitrotspread      = 18,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.4, 0]],
        numparticles       = 70,
        particlelife       = 30,
        particlelifespread = 160,
        particlesize       = 5.5,
        particlesizespread = -3,
        particlespeed      = 6,
        particlespeedspread = 9.5,
        pos                = [[0, 10, 0]],
        sizegrowth         = -0.04,
        sizemod            = 1,
        texture            = [[bigexplosmoke]],
        useairlos          = false,
      },
    },
	},
}

