featureTable = {
  corfatf_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corfatf",
    energy = 0,
    metal = 447,
  },
  armvader_corpse = {
    reclaimable = true,
    blocking = true,
    unitName = "armvader",
    energy = 0,
    metal = 49,
  },
  armguard_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 428,
  },
  armfort_rockteethx = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 7,
  },
  armmex_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 13,
  },
  corgator_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 31,
  },
  armfhp_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armfhp",
    energy = 0,
    metal = 670,
  },
  corssub_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 376,
  },
  armmav_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 196,
  },
  corseal_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 118,
  },
  corhlt_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corhlt",
    energy = 0,
    metal = 292,
  },
  chickenf1_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  corrl_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corrl",
    energy = 0,
    metal = 49,
  },
  chickenh5_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armsolar_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 30,
  },
  corfmd_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 392,
  },
  cormabm_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cormabm",
    energy = 0,
    metal = 980,
  },
  chicken1y_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armmstor_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armmstor",
    energy = 0,
    metal = 198,
  },
  armfark_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armfark",
    energy = 0,
    metal = 131,
  },
  corshroud_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corshroud",
    energy = 0,
    metal = 81,
  },
  armacv_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armacv",
    energy = 0,
    metal = 280,
  },
  armrad_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 14,
  },
  mercury_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "mercury",
    energy = 0,
    metal = 1022,
  },
  armyork_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armyork",
    energy = 0,
    metal = 276,
  },
  corfus_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corfus",
    energy = 0,
    metal = 2927,
  },
  armack_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armack",
    energy = 0,
    metal = 189,
  },
  decade_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "decade",
    energy = 0,
    metal = 197,
  },
  treetype10 = {
    reclaimable = true,
    blocking = true,
    energy = 250,
    metal = 0,
  },
  coruwes_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "coruwes",
    energy = 0,
    metal = 182,
  },
  armalab_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armalab",
    energy = 0,
    metal = 1773,
  },
  chicken_eggd = {
    reclaimable = true,
    blocking = false,
    energy = 250,
    metal = 25,
  },
  chicken1c_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  treetype5 = {
    reclaimable = true,
    blocking = true,
    energy = 250,
    metal = 0,
  },
  corarad_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 136,
  },
  chickenh5_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickenh5",
    energy = 0,
    metal = 0,
  },
  armfrad_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armfrad",
    energy = 0,
    metal = 83,
  },
  armuwmme_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armuwmme",
    energy = 0,
    metal = 391,
  },
  corlab_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 177,
  },
  coruwmex_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 14,
  },
  armmls_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armmls",
    energy = 0,
    metal = 138,
  },
  corcrus_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corcrus",
    energy = 0,
    metal = 1241,
  },
  armcom_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 1250,
  },
  armason_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armason",
    energy = 0,
    metal = 106,
  },
  armlab_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armlab",
    energy = 0,
    metal = 458,
  },
  armch_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armch",
    energy = 0,
    metal = 88,
  },
  corhrk_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corhrk",
    energy = 0,
    metal = 194,
  },
  armmanni_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 294,
  },
  armflak_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 200,
  },
  armmart_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armmart",
    energy = 0,
    metal = 198,
  },
  chicken_dodo1_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  chicken1c_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chicken1c",
    energy = 0,
    metal = 0,
  },
  coruwadves_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 206,
  },
  corcan_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 136,
  },
  armfus_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armfus",
    energy = 0,
    metal = 2603,
  },
  treetype8 = {
    reclaimable = true,
    blocking = true,
    energy = 250,
    metal = 0,
  },
  corfhp_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corfhp",
    energy = 0,
    metal = 715,
  },
  chicken_dodo2_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chicken_dodo2",
    energy = 0,
    metal = 0,
  },
  armbull_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 220,
  },
  screamer_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 458,
  },
  chickenh3_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  chickenh2_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armmls_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 66,
  },
  coresupp_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 91,
  },
  armdf_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armdf",
    energy = 0,
    metal = 222,
  },
  armmark_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armmark",
    energy = 0,
    metal = 76,
  },
  corasp_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 131,
  },
  corbhmth_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corbhmth",
    energy = 0,
    metal = 1917,
  },
  armfflak_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armfflak",
    energy = 0,
    metal = 525,
  },
  armmark_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 38,
  },
  armsam_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armsam",
    energy = 0,
    metal = 97,
  },
  armpincer_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armpincer",
    energy = 0,
    metal = 122,
  },
  coralab_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "coralab",
    energy = 0,
    metal = 1743,
  },
  coruwmme_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "coruwmme",
    energy = 0,
    metal = 550,
  },
  coraak_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 158,
  },
  coradvsol_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 92,
  },
  chicken_dodo2_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  cormh_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 48,
  },
  treetype11 = {
    reclaimable = true,
    blocking = true,
    energy = 250,
    metal = 0,
  },
  armck_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 26,
  },
  corsent_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 115,
  },
  screamer_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "screamer",
    energy = 0,
    metal = 1145,
  },
  armjanus_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 59,
  },
  corsolar_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 29,
  },
  treetype6 = {
    reclaimable = true,
    blocking = true,
    energy = 250,
    metal = 0,
  },
  armarad_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 136,
  },
  armuwms_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armuwms",
    energy = 0,
    metal = 234,
  },
  corah_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 62,
  },
  cormart_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cormart",
    energy = 0,
    metal = 138,
  },
  armuwes_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armuwes",
    energy = 0,
    metal = 185,
  },
  coreter_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 26,
  },
  armuwfus_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 1214,
  },
  treetype15 = {
    reclaimable = true,
    blocking = true,
    energy = 250,
    metal = 0,
  },
  armraz_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 930,
  },
  armflea_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 4,
  },
  armsnipe_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 129,
  },
  coruwes_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 73,
  },
  corhp_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corhp",
    energy = 0,
    metal = 662,
  },
  chickena1c_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickena1c",
    energy = 0,
    metal = 0,
  },
  tawf114_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 244,
  },
  marauder_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 237,
  },
  corparrow_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corparrow",
    energy = 0,
    metal = 642,
  },
  aseadragon_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 5066,
  },
  armvulc_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armvulc",
    energy = 0,
    metal = 22029,
  },
  chickena2_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  corspy_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 40,
  },
  armhlt_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armhlt",
    energy = 0,
    metal = 269,
  },
  cafus_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cafus",
    energy = 0,
    metal = 6440,
  },
  aafus_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "aafus",
    energy = 0,
    metal = 6441,
  },
  corck_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 29,
  },
  armanac_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 70,
  },
  chickenf1b_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickenf1b",
    energy = 0,
    metal = 0,
  },
  armbats_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armbats",
    energy = 0,
    metal = 3368,
  },
  corgant_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corgant",
    energy = 0,
    metal = 5101,
  },
  chickenw1b_dead = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  corroy_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corroy",
    energy = 0,
    metal = 577,
  },
  corllt_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 22,
  },
  corsy_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corsy",
    energy = 0,
    metal = 390,
  },
  chickenc3c_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickenc3c",
    energy = 0,
    metal = 0,
  },
  corvp_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corvp",
    energy = 0,
    metal = 470,
  },
  chickens1_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickens1",
    energy = 0,
    metal = 0,
  },
  corflak_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corflak",
    energy = 0,
    metal = 515,
  },
  armsptk_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armsptk",
    energy = 0,
    metal = 244,
  },
  armfast_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armfast",
    energy = 0,
    metal = 105,
  },
  corbats_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corbats",
    energy = 0,
    metal = 3513,
  },
  armsjam_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armsjam",
    energy = 0,
    metal = 85,
  },
  chickenw1d_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  chickenw1_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armwar_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 64,
  },
  armjamt_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armjamt",
    energy = 0,
    metal = 147,
  },
  armaas_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 164,
  },
  cormstor_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 83,
  },
  corshark_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 127,
  },
  armaser_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 19,
  },
  corerad_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 194,
  },
  chickenw1c_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armroy_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armroy",
    energy = 0,
    metal = 558,
  },
  armtide_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armtide",
    energy = 0,
    metal = 53,
  },
  chicken2b_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  vh_chickenq_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armalab_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 887,
  },
  corblackhy_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corblackhy",
    energy = 0,
    metal = 22480,
  },
  corspy_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corspy",
    energy = 0,
    metal = 101,
  },
  armflea_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armflea",
    energy = 0,
    metal = 9,
  },
  armsy_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armsy",
    energy = 0,
    metal = 400,
  },
  armfast_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 42,
  },
  armstump_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 61,
  },
  corptl_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corptl",
    energy = 0,
    metal = 205,
  },
  chicken1b_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  corsnap_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corsnap",
    energy = 0,
    metal = 192,
  },
  armuwfus_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armuwfus",
    energy = 0,
    metal = 3034,
  },
  corexp_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 49,
  },
  chicken1y_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chicken1y",
    energy = 0,
    metal = 0,
  },
  armpb_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 140,
  },
  armamd_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 374,
  },
  armspy_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armspy",
    energy = 0,
    metal = 83,
  },
  asubpen_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "asubpen",
    energy = 0,
    metal = 559,
  },
  corthovr_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corthovr",
    energy = 0,
    metal = 423,
  },
  armrectr_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 36,
  },
  armvulc_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 8812,
  },
  nsaclash_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "nsaclash",
    energy = 0,
    metal = 390,
  },
  cormexp_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cormexp",
    energy = 0,
    metal = 1442,
  },
  corestor_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corestor",
    energy = 0,
    metal = 108,
  },
  armmstor_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 79,
  },
  armpb_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armpb",
    energy = 0,
    metal = 350,
  },
  armzeus_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armzeus",
    energy = 0,
    metal = 214,
  },
  chickenc3b_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  chickenr3_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickenr3",
    energy = 0,
    metal = 0,
  },
  chicken1_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chicken1",
    energy = 0,
    metal = 0,
  },
  armshock_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armshock",
    energy = 0,
    metal = 2028,
  },
  corwin_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corwin",
    energy = 0,
    metal = 27,
  },
  armseer_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armseer",
    energy = 0,
    metal = 80,
  },
  corenaa_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corenaa",
    energy = 0,
    metal = 541,
  },
  chickend1_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickend1",
    energy = 0,
    metal = 0,
  },
  armaser_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armaser",
    energy = 0,
    metal = 47,
  },
  armfhlt_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armfhlt",
    energy = 0,
    metal = 341,
  },
  corarch_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corarch",
    energy = 0,
    metal = 354,
  },
  armavp_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armavp",
    energy = 0,
    metal = 1754,
  },
  armfboy_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 403,
  },
  armshock_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 811,
  },
  corch_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 40,
  },
  armrock_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 25,
  },
  chicken_eggb = {
    reclaimable = true,
    blocking = false,
    energy = 250,
    metal = 25,
  },
  armsam_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 45,
  },
  armmmkr_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 93,
  },
  armfatf_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 187,
  },
  chickena2b_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickena2b",
    energy = 0,
    metal = 0,
  },
  corhlt_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 117,
  },
  armfatf_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armfatf",
    energy = 0,
    metal = 467,
  },
  corfast_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 50,
  },
  ajuno_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 145,
  },
  armsonar_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armsonar",
    energy = 0,
    metal = 13,
  },
  h_chickenq_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "h_chickenq",
    energy = 0,
    metal = 0,
  },
  cjuno_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 192,
  },
  corason_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corason",
    energy = 0,
    metal = 99,
  },
  cortoast_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cortoast",
    energy = 0,
    metal = 1507,
  },
  corgeo_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corgeo",
    energy = 0,
    metal = 328,
  },
  cornecro_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cornecro",
    energy = 0,
    metal = 72,
  },
  armflash_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armflash",
    energy = 0,
    metal = 71,
  },
  armack_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 76,
  },
  armcv_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 33,
  },
  corvipe_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 61,
  },
  armadvsol_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armadvsol",
    energy = 0,
    metal = 223,
  },
  armcir_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 182,
  },
  corcs_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corcs",
    energy = 0,
    metal = 169,
  },
  armanac_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armanac",
    energy = 0,
    metal = 175,
  },
  armuwmme_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 156,
  },
  armah_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armah",
    energy = 0,
    metal = 141,
  },
  armamph_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armamph",
    energy = 0,
    metal = 159,
  },
  armgate_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armgate",
    energy = 0,
    metal = 2296,
  },
  chickens1_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armuwadves_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 201,
  },
  ve_chickenq_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "ve_chickenq",
    energy = 0,
    metal = 0,
  },
  chickena1c_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armspid_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 43,
  },
  armasy_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armasy",
    energy = 0,
    metal = 2232,
  },
  armraven_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 1183,
  },
  cortron_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 178,
  },
  armlab_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 183,
  },
  armsub_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 201,
  },
  cortarg_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cortarg",
    energy = 0,
    metal = 487,
  },
  chicken1z_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chicken1z",
    energy = 0,
    metal = 0,
  },
  armanni_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 776,
  },
  armrectr_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armrectr",
    energy = 0,
    metal = 72,
  },
  armbanth_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 3300,
  },
  armck_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armck",
    energy = 0,
    metal = 66,
  },
  armcom_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armcom",
    energy = 0,
    metal = 2500,
  },
  cortl_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "cortl",
    energy = 0,
    metal = 205,
  },
  armavp_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 877,
  },
  chickena1_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickena1",
    energy = 0,
    metal = 0,
  },
  armmh_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armmh",
    energy = 0,
    metal = 106,
  },
  coraak_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "coraak",
    energy = 0,
    metal = 395,
  },
  corsumo_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corsumo",
    energy = 0,
    metal = 1118,
  },
  corthud_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 38,
  },
  corfrad_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corfrad",
    energy = 0,
    metal = 80,
  },
  armdf_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 89,
  },
  corcs_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 66,
  },
  corsd_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 234,
  },
  armmerl_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armmerl",
    energy = 0,
    metal = 560,
  },
  armbeaver_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 37,
  },
  armscab_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armscab",
    energy = 0,
    metal = 934,
  },
  corcrash_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 30,
  },
  corgol_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corgol",
    energy = 0,
    metal = 894,
  },
  corasy_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corasy",
    energy = 0,
    metal = 2174,
  },
  chickenw2_dead = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armuwmex_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armuwmex",
    energy = 0,
    metal = 36,
  },
  armspy_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 33,
  },
  cornecro_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 26,
  },
  armsilo_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 1982,
  },
  armlatnk_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 80,
  },
  intruder_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 329,
  },
  corstorm_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 22,
  },
  corfgate_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corfgate",
    energy = 0,
    metal = 2296,
  },
  corfus_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 1171,
  },
  chicken1z_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armbrtha_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armbrtha",
    energy = 0,
    metal = 2720,
  },
  corspec_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 28,
  },
  coresupp_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "coresupp",
    energy = 0,
    metal = 191,
  },
  tawf114_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "tawf114",
    energy = 0,
    metal = 510,
  },
  armptl_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armptl",
    energy = 0,
    metal = 196,
  },
  coravp_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "coravp",
    energy = 0,
    metal = 1721,
  },
  armpw_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 12,
  },
  chickenr2_dead = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  chickenc1_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickenc1",
    energy = 0,
    metal = 0,
  },
  epic_chickenq_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armdl_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armdl",
    energy = 0,
    metal = 176,
  },
  armtship_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armtship",
    energy = 0,
    metal = 597,
  },
  armstump_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armstump",
    energy = 0,
    metal = 152,
  },
  mercury_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 409,
  },
  corgeo_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 131,
  },
  armfrt_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armfrt",
    energy = 0,
    metal = 46,
  },
  corarch_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 125,
  },
  armjeth_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 30,
  },
  armuwadvms_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armuwadvms",
    energy = 0,
    metal = 458,
  },
  armcrus_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 466,
  },
  shiva_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "shiva",
    energy = 0,
    metal = 937,
  },
  cortarg_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 195,
  },
  armsnipe_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armsnipe",
    energy = 0,
    metal = 322,
  },
  armuwadvms_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 183,
  },
  cormist_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cormist",
    energy = 0,
    metal = 100,
  },
  cormls_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 66,
  },
  chickenc3c_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  chickena2b_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armshltxuw_armshlt_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 1923,
  },
  armuwmex_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 14,
  },
  chicken1d_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chicken1d",
    energy = 0,
    metal = 0,
  },
  armwar_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armwar",
    energy = 0,
    metal = 161,
  },
  aafus_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 2576,
  },
  cafus_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 2576,
  },
  chickenp1_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armmship_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armmship",
    energy = 0,
    metal = 1721,
  },
  corcarry_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corcarry",
    energy = 0,
    metal = 1026,
  },
  chickenr2_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armjam_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armjam",
    energy = 0,
    metal = 78,
  },
  chickenw1d_dead = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  chickens2_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickens2",
    energy = 0,
    metal = 0,
  },
  corvrad_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 48,
  },
  corpun_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 449,
  },
  corack_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corack",
    energy = 0,
    metal = 207,
  },
  armmship_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 491,
  },
  corvp_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 188,
  },
  armsilo_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armsilo",
    energy = 0,
    metal = 4956,
  },
  armwin_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 9,
  },
  armdl_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 70,
  },
  armeyes_dragonseyes_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armeyes",
    energy = 0,
    metal = 12,
  },
  freefusion_free_fusion_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "freefusion",
    energy = 0,
    metal = 3300,
  },
  armjeth_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armjeth",
    energy = 0,
    metal = 75,
  },
  armemp_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 390,
  },
  corfast_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corfast",
    energy = 0,
    metal = 125,
  },
  armvp_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armvp",
    energy = 0,
    metal = 483,
  },
  corhrk_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 78,
  },
  corvroc_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 215,
  },
  coruwmex_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "coruwmex",
    energy = 0,
    metal = 36,
  },
  armmlv_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armmlv",
    energy = 0,
    metal = 34,
  },
  armfgate_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 918,
  },
  armbanth_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armbanth",
    energy = 0,
    metal = 8249,
  },
  corasp_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corasp",
    energy = 0,
    metal = 377,
  },
  chickenc3_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armyork_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 110,
  },
  armst_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 55,
  },
  armanni_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armanni",
    energy = 0,
    metal = 1940,
  },
  cormoho_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 137,
  },
  armspid_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armspid",
    energy = 0,
    metal = 108,
  },
  armsubk_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armsubk",
    energy = 0,
    metal = 681,
  },
  coravp_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 860,
  },
  armrock_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armrock",
    energy = 0,
    metal = 63,
  },
  geovent = {
    reclaimable = false,
    blocking = false,
    energy = 0,
    metal = 0,
  },
  armmoho_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armmoho",
    energy = 0,
    metal = 378,
  },
  corbhmth_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 767,
  },
  treetype14 = {
    reclaimable = true,
    blocking = true,
    energy = 250,
    metal = 0,
  },
  treetype13 = {
    reclaimable = true,
    blocking = true,
    energy = 250,
    metal = 0,
  },
  coruwadvms_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 185,
  },
  armasp_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 126,
  },
  armrad_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armrad",
    energy = 0,
    metal = 35,
  },
  corcom_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 1250,
  },
  treetype12 = {
    reclaimable = true,
    blocking = true,
    energy = 250,
    metal = 0,
  },
  armcarry_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 266,
  },
  treetype9 = {
    reclaimable = true,
    blocking = true,
    energy = 250,
    metal = 0,
  },
  treetype7 = {
    reclaimable = true,
    blocking = true,
    energy = 250,
    metal = 0,
  },
  treetype4 = {
    reclaimable = true,
    blocking = true,
    energy = 250,
    metal = 0,
  },
  armfido_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armfido",
    energy = 0,
    metal = 164,
  },
  cormaw_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cormaw",
    energy = 0,
    metal = 177,
  },
  armgate_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 918,
  },
  armbull_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armbull",
    energy = 0,
    metal = 549,
  },
  treetype2 = {
    reclaimable = true,
    blocking = true,
    energy = 250,
    metal = 0,
  },
  treetype0 = {
    reclaimable = true,
    blocking = true,
    energy = 250,
    metal = 0,
  },
  corssub_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corssub",
    energy = 0,
    metal = 1202,
  },
  armguard_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armguard",
    energy = 0,
    metal = 1069,
  },
  treetype1 = {
    reclaimable = true,
    blocking = true,
    energy = 250,
    metal = 0,
  },
  vh_chickenq_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "vh_chickenq",
    energy = 0,
    metal = 0,
  },
  corfav_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 6,
  },
  ve_chickenq_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  trem_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 527,
  },
  trem_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "trem",
    energy = 0,
    metal = 1118,
  },
  armcv_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armcv",
    energy = 0,
    metal = 83,
  },
  tawf013_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 37,
  },
  tawf013_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "tawf013",
    energy = 0,
    metal = 92,
  },
  corgant_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 2040,
  },
  tawf009_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "tawf009",
    energy = 0,
    metal = 1332,
  },
  corsub_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 150,
  },
  tawf001_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "tawf001",
    energy = 0,
    metal = 114,
  },
  shiva_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 375,
  },
  packo_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 110,
  },
  armaak_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 126,
  },
  armham_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armham",
    energy = 0,
    metal = 79,
  },
  armsd_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 227,
  },
  armraven_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armraven",
    energy = 0,
    metal = 2958,
  },
  chicken2_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  packo_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "packo",
    energy = 0,
    metal = 275,
  },
  chickenh1_dead = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  nsaclash_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 156,
  },
  n_chickenq_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  n_chickenq_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "n_chickenq",
    energy = 0,
    metal = 0,
  },
  armsub_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armsub",
    energy = 0,
    metal = 338,
  },
  marauder_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "marauder",
    energy = 0,
    metal = 592,
  },
  madsam_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 103,
  },
  madsam_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "madsam",
    energy = 0,
    metal = 257,
  },
  chicken1d_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armfav_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 6,
  },
  intruder_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "intruder",
    energy = 0,
    metal = 822,
  },
  hllt_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 48,
  },
  armmart_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 79,
  },
  armmh_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 42,
  },
  corerad_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corerad",
    energy = 0,
    metal = 486,
  },
  h_chickenq_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  gorg_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 2793,
  },
  armtl_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armtl",
    energy = 0,
    metal = 196,
  },
  chickena2_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickena2",
    energy = 0,
    metal = 0,
  },
  gorg_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "gorg",
    energy = 0,
    metal = 13959,
  },
  epic_chickenq_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "epic_chickenq",
    energy = 0,
    metal = 0,
  },
  armsubk_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 181,
  },
  armcroc_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 119,
  },
  cortron_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cortron",
    energy = 0,
    metal = 445,
  },
  corsolar_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corsolar",
    energy = 0,
    metal = 72,
  },
  e_chickenq_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "e_chickenq",
    energy = 0,
    metal = 0,
  },
  decade_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 97,
  },
  armscab_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 374,
  },
  coraap_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "coraap",
    energy = 0,
    metal = 1936,
  },
  csubpen_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "csubpen",
    energy = 0,
    metal = 596,
  },
  armamph_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 64,
  },
  corwolv_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corwolv",
    energy = 0,
    metal = 103,
  },
  corwin_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 11,
  },
  corvroc_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corvroc",
    energy = 0,
    metal = 538,
  },
  cjuno_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cjuno",
    energy = 0,
    metal = 388,
  },
  chickena1b_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickena1b",
    energy = 0,
    metal = 0,
  },
  ajuno_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "ajuno",
    energy = 0,
    metal = 352,
  },
  corvrad_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corvrad",
    energy = 0,
    metal = 64,
  },
  corvoyr_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 24,
  },
  corvoyr_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corvoyr",
    energy = 0,
    metal = 60,
  },
  corvipe_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corvipe",
    energy = 0,
    metal = 380,
  },
  coralab_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 872,
  },
  coruwms_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 91,
  },
  coruwms_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "coruwms",
    energy = 0,
    metal = 228,
  },
  treetype3 = {
    reclaimable = true,
    blocking = true,
    energy = 250,
    metal = 0,
  },
  coruwfus_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 1240,
  },
  coruwfus_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "coruwfus",
    energy = 0,
    metal = 3099,
  },
  corak_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corak",
    energy = 0,
    metal = 22,
  },
  coruwadvms_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "coruwadvms",
    energy = 0,
    metal = 462,
  },
  coruwadves_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "coruwadves",
    energy = 0,
    metal = 514,
  },
  chicken_eggc = {
    reclaimable = true,
    blocking = false,
    energy = 250,
    metal = 25,
  },
  armsjam_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 23,
  },
  chicken1x_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  cortship_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 291,
  },
  corrad_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corrad",
    energy = 0,
    metal = 36,
  },
  armwin_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armwin",
    energy = 0,
    metal = 23,
  },
  corint_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 1125,
  },
  e_chickenq_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  cortoast_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 241,
  },
  armjanus_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armjanus",
    energy = 0,
    metal = 147,
  },
  armtide_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 17,
  },
  armtship_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 209,
  },
  armamex_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armamex",
    energy = 0,
    metal = 103,
  },
  armrl_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armrl",
    energy = 0,
    metal = 51,
  },
  armflash_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 28,
  },
  armaap_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armaap",
    energy = 0,
    metal = 1953,
  },
  armaas_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armaas",
    energy = 0,
    metal = 325,
  },
  corthud_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corthud",
    energy = 0,
    metal = 96,
  },
  corroy_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 249,
  },
  armamd_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armamd",
    energy = 0,
    metal = 934,
  },
  cortermite_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 209,
  },
  cortermite_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cortermite",
    energy = 0,
    metal = 523,
  },
  armamex_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 41,
  },
  corfort_rockteethx = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 7,
  },
  tawf001_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 46,
  },
  corsub_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corsub",
    energy = 0,
    metal = 353,
  },
  armmoho_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 151,
  },
  corhp_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 265,
  },
  chickenw1_dead = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  corstorm_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corstorm",
    energy = 0,
    metal = 55,
  },
  corspec_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corspec",
    energy = 0,
    metal = 56,
  },
  chicken2b_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chicken2b",
    energy = 0,
    metal = 0,
  },
  correap_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "correap",
    energy = 0,
    metal = 350,
  },
  armaak_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armaak",
    energy = 0,
    metal = 314,
  },
  armamb_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armamb",
    energy = 0,
    metal = 1522,
  },
  armseer_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 48,
  },
  chickenc3_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickenc3",
    energy = 0,
    metal = 0,
  },
  corsonar_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corsonar",
    energy = 0,
    metal = 13,
  },
  corsnap_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 77,
  },
  armmex_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armmex",
    energy = 0,
    metal = 33,
  },
  corsjam_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 46,
  },
  corsjam_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corsjam",
    energy = 0,
    metal = 88,
  },
  corsilo_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 1869,
  },
  tawf009_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 513,
  },
  corshroud_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 32,
  },
  corshark_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corshark",
    energy = 0,
    metal = 321,
  },
  corsh_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 16,
  },
  corsh_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corsh",
    energy = 0,
    metal = 40,
  },
  corparrow_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 257,
  },
  cordrag_rockteeth = {
    reclaimable = true,
    blocking = false,
    unitName = "cordrag",
    energy = 0,
    metal = 2,
  },
  corsent_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corsent",
    energy = 0,
    metal = 288,
  },
  cordl_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 73,
  },
  corsd_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corsd",
    energy = 0,
    metal = 584,
  },
  armjam_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 39,
  },
  armfgate_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armfgate",
    energy = 0,
    metal = 2296,
  },
  coreter_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "coreter",
    energy = 0,
    metal = 65,
  },
  correap_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 150,
  },
  chicken1b_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chicken1b",
    energy = 0,
    metal = 0,
  },
  armuwes_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 74,
  },
  corraid_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 67,
  },
  cordl_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cordl",
    energy = 0,
    metal = 182,
  },
  corraid_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corraid",
    energy = 0,
    metal = 167,
  },
  corgol_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 378,
  },
  armestor_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 41,
  },
  corpyro_heap = {
    reclaimable = true,
    blocking = false,
    unitName = "corpyro",
    energy = 0,
    metal = 124,
  },
  corpun_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corpun",
    energy = 0,
    metal = 1123,
  },
  cormoho_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cormoho",
    energy = 0,
    metal = 318,
  },
  corpt_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 22,
  },
  corpt_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corpt",
    energy = 0,
    metal = 44,
  },
  corplat_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corplat",
    energy = 0,
    metal = 1748,
  },
  corint_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corint",
    energy = 0,
    metal = 2813,
  },
  cormabm_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 392,
  },
  cortide_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "cortide",
    energy = 0,
    metal = 53,
  },
  corlevlr_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corlevlr",
    energy = 0,
    metal = 190,
  },
  consul_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 61,
  },
  chickens3_dead = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armadvsol_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 89,
  },
  corrad_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 14,
  },
  cormort_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 47,
  },
  cormort_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cormort",
    energy = 0,
    metal = 118,
  },
  cormmkr_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 91,
  },
  armap_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armap",
    energy = 0,
    metal = 553,
  },
  cormmkr_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cormmkr",
    energy = 0,
    metal = 228,
  },
  aseadragon_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "aseadragon",
    energy = 0,
    metal = 20879,
  },
  cormlv_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 15,
  },
  armatl_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armatl",
    energy = 0,
    metal = 548,
  },
  cormlv_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cormlv",
    energy = 0,
    metal = 37,
  },
  armmerl_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 224,
  },
  corlab_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corlab",
    energy = 0,
    metal = 442,
  },
  coracv_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 118,
  },
  cormist_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 46,
  },
  corch_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corch",
    energy = 0,
    metal = 100,
  },
  cormart_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 55,
  },
  corcv_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 35,
  },
  chickenc2_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armpt_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armpt",
    energy = 0,
    metal = 43,
  },
  armsptk_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 98,
  },
  cormh_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "cormh",
    energy = 0,
    metal = 119,
  },
  armtarg_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armtarg",
    energy = 0,
    metal = 492,
  },
  armfav_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armfav",
    energy = 0,
    metal = 15,
  },
  cormexp_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 577,
  },
  chicken1_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armcarry_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armcarry",
    energy = 0,
    metal = 1022,
  },
  corcom_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corcom",
    energy = 0,
    metal = 2500,
  },
  cormex_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 13,
  },
  corkrog_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corkrog",
    energy = 0,
    metal = 17668,
  },
  armestor_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armestor",
    energy = 0,
    metal = 103,
  },
  cormex_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cormex",
    energy = 0,
    metal = 33,
  },
  chickenr1_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  cormls_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cormls",
    energy = 0,
    metal = 157,
  },
  corblackhy_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 10066,
  },
  cormaw_rockteeth = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 2,
  },
  corestor_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 43,
  },
  chickenh4_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  corseal_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corseal",
    energy = 0,
    metal = 236,
  },
  armbrtha_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 1088,
  },
  armbats_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 1066,
  },
  chickens2_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  corllt_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corllt",
    energy = 0,
    metal = 55,
  },
  corlevlr_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 76,
  },
  armacv_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 112,
  },
  chickenh1b_dead = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  cormstor_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cormstor",
    energy = 0,
    metal = 208,
  },
  armacsub_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armacsub",
    energy = 0,
    metal = 452,
  },
  chickenf2_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  corsumo_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 447,
  },
  armfort_fortification = {
    reclaimable = true,
    blocking = true,
    unitName = "armfort",
    energy = 0,
    metal = 15,
  },
  corkrog_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 15067,
  },
  chickenf2_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickenf2",
    energy = 0,
    metal = 0,
  },
  corkarg_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corkarg",
    energy = 0,
    metal = 1014,
  },
  corbats_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 1066,
  },
  corjamt_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corjamt",
    energy = 0,
    metal = 71,
  },
  armfus_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 1041,
  },
  armshltx_armshltx_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 1923,
  },
  cortship_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "cortship",
    energy = 0,
    metal = 577,
  },
  armclaw_rockteeth = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 2,
  },
  cormuskrat_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 42,
  },
  corsilo_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corsilo",
    energy = 0,
    metal = 4672,
  },
  armfmmm_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armfmmm",
    energy = 0,
    metal = 247,
  },
  armsd_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armsd",
    energy = 0,
    metal = 566,
  },
  chickenc2_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickenc2",
    energy = 0,
    metal = 0,
  },
  cormship_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "cormship",
    energy = 0,
    metal = 1679,
  },
  armshltxuw_armshlt_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armshltxuw",
    energy = 0,
    metal = 4807,
  },
  armrl_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 20,
  },
  armmanni_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armmanni",
    energy = 0,
    metal = 734,
  },
  corak_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 9,
  },
  corgate_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 971,
  },
  corgate_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corgate",
    energy = 0,
    metal = 2428,
  },
  corgarp_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corgarp",
    energy = 0,
    metal = 134,
  },
  corgantuw_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 2040,
  },
  armhp_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 248,
  },
  corgantuw_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corgantuw",
    energy = 0,
    metal = 5101,
  },
  armpt_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 21,
  },
  armcs_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 59,
  },
  corfrt_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corfrt",
    energy = 0,
    metal = 47,
  },
  corfort_fortification_core = {
    reclaimable = true,
    blocking = true,
    unitName = "corfort",
    energy = 0,
    metal = 15,
  },
  chickenf1_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickenf1",
    energy = 0,
    metal = 0,
  },
  corfmmm_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 97,
  },
  corfmmm_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corfmmm",
    energy = 0,
    metal = 242,
  },
  corfmd_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corfmd",
    energy = 0,
    metal = 980,
  },
  armckfus_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armckfus",
    energy = 0,
    metal = 3100,
  },
  corfhlt_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corfhlt",
    energy = 0,
    metal = 363,
  },
  corbuzz_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 8440,
  },
  armhlt_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 108,
  },
  corfgate_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 918,
  },
  armch_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 35,
  },
  armraz_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armraz",
    energy = 0,
    metal = 2325,
  },
  armfark_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 52,
  },
  armsh_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armsh",
    energy = 0,
    metal = 49,
  },
  chickenh1_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  corfdrag_floatingteeth_core = {
    reclaimable = true,
    blocking = true,
    unitName = "corfdrag",
    energy = 0,
    metal = 20,
  },
  corck_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corck",
    energy = 0,
    metal = 73,
  },
  armah_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 56,
  },
  chickenh1b_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armasp_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armasp",
    energy = 0,
    metal = 366,
  },
  corfatf_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 179,
  },
  armacsub_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 207,
  },
  cortide_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 17,
  },
  chickenc1_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  coramph_heap = {
    reclaimable = true,
    blocking = false,
    unitName = "coramph",
    energy = 0,
    metal = 114,
  },
  armuwms_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 94,
  },
  coreyes_cdragonseyes_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "coreyes",
    energy = 0,
    metal = 12,
  },
  coracsub_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "coracsub",
    energy = 0,
    metal = 449,
  },
  corexp_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corexp",
    energy = 0,
    metal = 122,
  },
  coraap_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 968,
  },
  corap_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corap",
    energy = 0,
    metal = 540,
  },
  hllt_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "hllt",
    energy = 0,
    metal = 120,
  },
  armemp_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armemp",
    energy = 0,
    metal = 976,
  },
  chickenh2_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickenh2",
    energy = 0,
    metal = 0,
  },
  cordoom_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 644,
  },
  cordoom_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cordoom",
    energy = 0,
    metal = 1611,
  },
  armuwadves_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armuwadves",
    energy = 0,
    metal = 502,
  },
  chickenr3_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  cormship_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 566,
  },
  armaap_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 977,
  },
  armst_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armst",
    energy = 0,
    metal = 138,
  },
  armcs_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armcs",
    energy = 0,
    metal = 166,
  },
  armsh_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 20,
  },
  chicken2_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chicken2",
    energy = 0,
    metal = 0,
  },
  corcrus_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 476,
  },
  armsolar_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armsolar",
    energy = 0,
    metal = 75,
  },
  corcrash_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corcrash",
    energy = 0,
    metal = 75,
  },
  armllt_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armllt",
    energy = 0,
    metal = 53,
  },
  chickenw1b_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  chickenc3b_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickenc3b",
    energy = 0,
    metal = 0,
  },
  corcarry_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 266,
  },
  armllt_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 21,
  },
  armbeaver_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armbeaver",
    energy = 0,
    metal = 92,
  },
  corcv_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corcv",
    energy = 0,
    metal = 87,
  },
  corrl_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 20,
  },
  armshltx_armshltx_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armshltx",
    energy = 0,
    metal = 4807,
  },
  coracv_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "coracv",
    energy = 0,
    metal = 294,
  },
  armmmkr_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armmmkr",
    energy = 0,
    metal = 233,
  },
  chickena1_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armckfus_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 1240,
  },
  armcroc_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armcroc",
    energy = 0,
    metal = 238,
  },
  chicken_dodo1_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chicken_dodo1",
    energy = 0,
    metal = 0,
  },
  armroy_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 234,
  },
  corgator_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corgator",
    energy = 0,
    metal = 77,
  },
  armthovr_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armthovr",
    energy = 0,
    metal = 432,
  },
  armzeus_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 86,
  },
  armplat_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armplat",
    energy = 0,
    metal = 1734,
  },
  corap_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 216,
  },
  chickenw2_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  corflak_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 206,
  },
  consul_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "consul",
    energy = 0,
    metal = 153,
  },
  armveil_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 31,
  },
  chickens3_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armclaw_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armclaw",
    energy = 0,
    metal = 205,
  },
  armamb_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 244,
  },
  corarad_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corarad",
    energy = 0,
    metal = 339,
  },
  corack_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 83,
  },
  corah_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corah",
    energy = 0,
    metal = 154,
  },
  coradvsol_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "coradvsol",
    energy = 0,
    metal = 231,
  },
  chickenr1_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickenr1",
    energy = 0,
    metal = 0,
  },
  armfboy_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armfboy",
    energy = 0,
    metal = 1008,
  },
  armarad_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armarad",
    energy = 0,
    metal = 341,
  },
  armhp_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armhp",
    energy = 0,
    metal = 621,
  },
  armcrus_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armcrus",
    energy = 0,
    metal = 1272,
  },
  chickenh3_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickenh3",
    energy = 0,
    metal = 0,
  },
  armgeo_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 135,
  },
  armvp_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 193,
  },
  armpw_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "armpw",
    energy = 0,
    metal = 29,
  },
  chickenw1c_dead = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  coratl_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "coratl",
    energy = 0,
    metal = 676,
  },
  armmav_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armmav",
    energy = 0,
    metal = 394,
  },
  armham_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 32,
  },
  cormuskrat_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "cormuskrat",
    energy = 0,
    metal = 105,
  },
  armfmmm_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 99,
  },
  corfav_dead = {
    reclaimable = true,
    blocking = false,
    unitName = "corfav",
    energy = 0,
    metal = 16,
  },
  chickenf1b_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  chickenh4_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chickenh4",
    energy = 0,
    metal = 0,
  },
  chickenp1_dead = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armfido_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 66,
  },
  chickend1_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  coruwmme_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 220,
  },
  armap_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 221,
  },
  chicken_egg = {
    reclaimable = true,
    blocking = false,
    energy = 250,
    metal = 25,
  },
  chickena1b_heap = {
    reclaimable = true,
    blocking = true,
    energy = 0,
    metal = 0,
  },
  armvader_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 12,
  },
  chicken1x_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "chicken1x",
    energy = 0,
    metal = 0,
  },
  armveil_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armveil",
    energy = 0,
    metal = 77,
  },
  armlatnk_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armlatnk",
    energy = 0,
    metal = 200,
  },
  armmlv_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 14,
  },
  armgeo_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armgeo",
    energy = 0,
    metal = 338,
  },
  armcir_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armcir",
    energy = 0,
    metal = 456,
  },
  armflak_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "armflak",
    energy = 0,
    metal = 500,
  },
  coracsub_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 183,
  },
  armdrag_rockteeth = {
    reclaimable = true,
    blocking = false,
    unitName = "armdrag",
    energy = 0,
    metal = 2,
  },
  corcan_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corcan",
    energy = 0,
    metal = 339,
  },
  armtarg_heap = {
    reclaimable = true,
    blocking = false,
    energy = 0,
    metal = 197,
  },
  corbuzz_dead = {
    reclaimable = true,
    blocking = true,
    unitName = "corbuzz",
    energy = 0,
    metal = 21099,
  },
}