local ModeDSL = VFS.Include("modules/transfer/mode_dsl.lua")
local Mode, Share, Assist, Reclaim, Resurrect, Take, Tech =
	ModeDSL.Mode, ModeDSL.Share, ModeDSL.Assist, ModeDSL.Reclaim, ModeDSL.Resurrect, ModeDSL.Take, ModeDSL.Tech

return Mode("Tech Core")
	.Desc("Tech levels gate unit construction. Build Keystone buildings to advance. Sharing unlocks with tech. Legion's mex economy is rebalanced for the universal Voussoir.")
	.Ranked()
	.Gate(Tech, 1, 1.5)
	.Deny(Share.Units)
	.Allow(Share.Units.Constructors.AtT2)
	.Deny(Share.Units.AtT3)
	.Allow(Share.Resources)
	.Tax(Share.Resources, 0.6)
	.Tax(Share.Resources.AtT2, 0.5)
	.Tax(Share.Resources.AtT3, 0.4)
	.Allow(Assist.Allied)
	.Allow(Reclaim.AlliedUnits)
	.Deny(Resurrect.Partial)
	.Defer(Take)
	.Delay(Take.Resource, 60)
