-- UNITDEF -- ARMDECOM --
--------------------------------------------------------------------------------

local unitName = "armdecom"

--------------------------------------------------------------------------------

local unitDef = {
  acceleration       = 0.18,
  activateWhenBuilt  = true,
  autoHeal           = 5,
  badTargetCategory  = [[VTOL]],
  bmcode             = 1,
  brakeRate          = 0.375,
  buildCostEnergy    = 11561,
  buildCostMetal     = 721,
  buildDistance      = 128,
  builder            = true,
  buildPic           = [[ARMDECOM.DDS]],
  buildTime          = 24048,
  canAttack          = true,
  canDGun            = true,
  canGuard           = true,
  canMove            = true,
  canPatrol          = true,
  canreclamate       = 1,
  canstop            = 1,
  category           = [[ALL WEAPON NOTSUB NOTSHIP NOTAIR]],
  cloakCost          = 30,
  cloakCostMoving    = 180,
  decoyFor           = [[armcom]],
  defaultmissiontype = [[Standby]],
  description        = [[Decoy Commander]],
  energyMake         = 15,
  energyStorage      = 50,
  explodeAs          = [[DECOY_COMMANDER_BLAST]],
  firestandorders    = 1,
  footprintX         = 2,
  footprintZ         = 2,
  hideDamage         = true,
  iconType           = [[armcommander]],
  idleAutoHeal       = 5,
  idleTime           = 1800,
  immunetoparalyzer  = 1,
  maneuverleashlength = 640,
  mass               = 5000,
  maxDamage          = 3000,
  maxSlope           = 20,
  maxVelocity        = 1.25,
  maxWaterDepth      = 35,
  metalMake          = 0.5,
  metalStorage       = 50,
  minCloakDistance   = 50,
  mobilestandorders  = 1,
  movementClass      = [[AKBOT2]],
  name               = [[Commander]],
  noChaseCategory    = [[VTOL]],
  norestrict         = 1,
  objectName         = [[ARMCOM]],
  radarDistance      = 50,
  reclaimable        = false,
  seismicSignature   = 0,
  selfDestructAs     = [[DECOY_COMMANDER_BLAST]],
  showPlayerName     = true,
  side               = [[arm]],
  sightDistance      = 377,
  smoothAnim         = true,
  standingfireorder  = 2,
  standingmoveorder  = 0,
  steeringmode       = 2,
  TEDClass           = [[COMMANDER]],
  terraformSpeed     = 450,
  turnRate           = 1148,
  unitname           = [[armdecom]],
  upright            = true,
  workerTime         = 150,
  buildoptions = {
    [[armmine1]],
    [[armmine2]],
    [[armmine3]],
    [[armsolar]],
    [[armtide]],
    [[armwin]],
    [[armmstor]],
    [[armestor]],
    [[armuwms]],
    [[armuwes]],
    [[armmex]],
    [[armuwmex]],
    [[armmakr]],
    [[armfmkr]],
  },
  sounds = {
    build              = [[nanlath1]],
    canceldestruct     = [[cancel2]],
    capture            = [[capture1]],
    repair             = [[repair1]],
    underattack        = [[warning1]],
    working            = [[reclaim1]],
    cant = {
      [[cantdo4]],
    },
    count = {
      [[count6]],
      [[count5]],
      [[count4]],
      [[count3]],
      [[count2]],
      [[count1]],
    },
    ok = {
      [[kbarmmov]],
    },
    select = {
      [[kbarmsel]],
    },
  },
  weapons = {
    [1]  = {
      def                = [[ARMCOMLASER]],
    },
    [3]  = {
      def                = [[DECOY_DISINTEGRATOR]],
    },
  },
}


--------------------------------------------------------------------------------

local weaponDefs = {
  ARMCOMLASER = {
    areaOfEffect       = 12,
    avoidFeature       = false,
    beamlaser          = 1,
    beamTime           = 0.1,
    coreThickness      = 0.1,
    craterBoost        = 0,
    craterMult         = 0,
    cylinderTargetting = 1,
    edgeEffectiveness  = 0.99,
    explosionGenerator = [[custom:SMALL_RED_BURN]],
    fireStarter        = 70,
    impactonly         = 1,
    impulseBoost       = 0.123,
    impulseFactor      = 0.123,
    laserFlareSize     = 7,
    lineOfSight        = true,
    name               = [[J7Laser]],
    noSelfDamage       = true,
    range              = 300,
    reloadtime         = 0.4,
    renderType         = 0,
    rgbColor           = [[1 0 0]],
    soundHit           = [[lasrhit2]],
    soundStart         = [[lasrfir1]],
    soundTrigger       = true,
    targetMoveError    = 0.05,
    thickness          = 2,
    tolerance          = 10000,
    turret             = true,
    weaponType         = [[BeamLaser]],
    weaponVelocity     = 900,
    damage = {
      default            = 75,
      l1bombers          = 180,
      l1fighters         = 110,
      l1subs             = 5,
      l2bombers          = 180,
      l2fighters         = 110,
      l2subs             = 5,
      l3subs             = 5,
      vtrans             = 110,
    },
  },
  DECOY_DISINTEGRATOR = {
    areaOfEffect       = 32,
    avoidFriendly      = false,
    beamWeapon         = true,
    commandfire        = true,
    craterBoost        = 0,
    craterMult         = 0,
    energypershot      = 50,
    explosionGenerator = [[custom:DGUNTRACE]],
    impulseBoost       = 0,
    impulseFactor      = 0,
    lineOfSight        = true,
    name               = [[Disintegrator]],
    noExplode          = true,
    noSelfDamage       = true,
    range              = 250,
    reloadtime         = 1.5,
    renderType         = 3,
    soundHit           = [[xplomas2]],
    soundStart         = [[disigun1]],
    soundTrigger       = true,
    startsmoke         = 1,
    tolerance          = 10000,
    turret             = true,
    weaponType         = [[DGun]],
    weaponTimer        = 4.2,
    weaponVelocity     = 300,
    damage = {
      amphibious         = 10,
      anniddm            = 10,
      antibomber         = 10,
      antifighter        = 10,
      antiraider         = 10,
      atl                = 10,
      blackhydra         = 10,
      commanders         = 10,
      crawlingbombs      = 10,
      default            = 99999,
      dl                 = 10,
      ["else"]           = 10,
      flakboats          = 10,
      flaks              = 10,
      flamethrowers      = 10,
      gunships           = 10,
      heavyunits         = 10,
      hgunships          = 10,
      jammerboats        = 10,
      krogoth            = 10,
      l1bombers          = 10,
      l1fighters         = 10,
      l1subs             = 10,
      l2bombers          = 10,
      l2fighters         = 10,
      l2subs             = 10,
      l3subs             = 10,
      mechs              = 10,
      mines              = 10,
      nanos              = 10,
      otherboats         = 10,
      plasmaguns         = 10,
      radar              = 10,
      seadragon          = 10,
      spies              = 10,
      tl                 = 10,
      vradar             = 10,
      vtol               = 10,
      vtrans             = 10,
    },
  },
}
unitDef.weaponDefs = weaponDefs


--------------------------------------------------------------------------------

return lowerkeys({ [unitName] = unitDef })

--------------------------------------------------------------------------------
