return {
	armfdrag = {
		acceleration = 0,
		brakerate = 0,
		buildangle = 8192,
		buildcostenergy = 600,
		buildcostmetal = 20,
		builder = false,
		buildpic = "ARMFDRAG.DDS",
		buildtime = 930,
		category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR",
		corpse = "FLOATINGTEETH",
		description = "Perimeter Defense",
		energymake = 0,
		energystorage = 0,
		energyuse = 0,
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 5,
		idletime = 1800,
		isfeature = true,
		maxdamage = 50,
		maxslope = 32,
		maxvelocity = 0,
		maxwaterdepth = 0,
		metalstorage = 0,
		minwaterdepth = 1,
		name = "Shark's Teeth",
		noautofire = false,
		objectname = "ARMFDRAG",
		seismicsignature = 0,
		sightdistance = 130,
		smoothanim = false,
		turnrate = 0,
		waterline = 12,
		workertime = 0,
		yardmap = "wwww",
		featuredefs = {
			floatingteeth = {
				autoreclaimable = 0,
				blocking = true,
				category = "dragonteeth",
				damage = 15000,
				description = "Shark's Teeth",
				footprintx = 2,
				footprintz = 2,
				height = 75,
				hitdensity = 100,
				metal = 20,
				nodrawundergray = true,
				object = "armfdrag",
				reclaimable = true,
				world = "allworld",
			},
		},
	},
}
