return {
	armrecl = {
		acceleration = 0.048000000417233,
		brakerate = 0.25,
		buildcostenergy = 6911,
		buildcostmetal = 413,
		builddistance = 128,
		builder = true,
		buildpic = "ARMRECL.DDS",
		buildtime = 9259,
		canassist = false,
		canmove = true,
		canresurrect = true,
		category = "ALL UNDERWATER CONSTR NOWEAPON NOTAIR",
		collisionvolumeoffsets = "0 0 2",
		collisionvolumescales = "49 11 78",
		collisionvolumetest = 1,
		collisionvolumetype = "Ell",
		description = "Ressurection Sub",
		energymake = 2,
		energyuse = 2,
		explodeas = "SMALL_UNITEX",
		footprintx = 3,
		footprintz = 3,
		icontype = "sea",
		idleautoheal = 5 ,
		idletime = 1800 ,
		maxdamage = 670,
		maxvelocity = 2.3599998950958,
		minwaterdepth = 20,
		movementclass = "UBOAT3",
		name = "Grim Reaper",
		objectname = "ARMRECL",
		seismicsignature = 0,
		selfdestructas = "SMALL_UNIT",
		sightdistance = 156,
		terraformspeed = 2250,
		turnrate = 282,
		waterline = 30,
		workertime = 450,
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			capture = "capture1",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "sucormov",
			},
			select = {
				[1] = "sucorsel",
			},
		},
	},
}
