return {
	corawac = {
		acceleration = 0.096000000834465,
		brakerate = 3.75,
		buildcostenergy = 7824,
		buildcostmetal = 169,
		builder = false,
		buildpic = "CORAWAC.DDS",
		buildtime = 13264,
		canfly = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		category = "ALL ANTIEMG NOTLAND MOBILE ANTIGATOR NOTSUB ANTIFLAME ANTILASER VTOL NOWEAPON NOTSHIP",
		collide = false,
		cruisealt = 210,
		description = "Radar/Sonar Plane",
		energymake = 20,
		energystorage = 0,
		energyuse = 20,
		explodeas = "BIG_UNITEX",
		footprintx = 3,
		footprintz = 3,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 890,
		maxslope = 10,
		maxvelocity = 10.699999809265,
		maxwaterdepth = 0,
		metalstorage = 0,
		name = "Vulture",
		noautofire = false,
		objectname = "CORAWAC",
		radardistance = 2400,
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 1250,
		smoothanim = false,
		sonardistance = 1200,
		turnrate = 402,
		workertime = 0,
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "caradsel",
			},
		},
	},
}
