return {
	coratl = {
		acceleration = 0,
		activatewhenbuilt = true,
		brakerate = 0,
		buildangle = 16384,
		buildcostenergy = 8638,
		buildcostmetal = 1079,
		builder = false,
		buildpic = "CORATL.DDS",
		buildtime = 10875,
		canattack = true,
		category = "ALL NOTLAND WEAPON NOTSHIP NOTAIR",
		corpse = "DEAD",
		description = "Advanced Torpedo Launcher",
		energymake = 0.10000000149012,
		energystorage = 0,
		energyuse = 0.10000000149012,
		explodeas = "BIG_UNITEX",
		footprintx = 3,
		footprintz = 3,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 1562,
		maxvelocity = 0,
		metalstorage = 0,
		minwaterdepth = 12,
		name = "Lamprey",
		noautofire = false,
		objectname = "CORATL",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 585,
		smoothanim = false,
		turnrate = 0,
		waterline = 10,
		workertime = 0,
		yardmap = "ooooooooo",
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				damage = 337,
				description = "Lamprey Wreckage",
				energy = 0,
				footprintx = 3,
				footprintz = 3,
				height = 20,
				hitdensity = 100,
				metal = 676,
				object = "CORATL_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "torpadv2",
			},
			select = {
				[1] = "torpadv2",
			},
		},
		weapondefs = {
			coratl_torpedo = {
				areaofeffect = 16,
				avoidfriendly = false,
				burnblow = true,
				collidefriendly = false,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:FLASH2",
				impulseboost = 0.12300000339746,
				impulsefactor = 0.12300000339746,
				model = "advtorpedo",
				name = "LongRangeTorpedo",
				noselfdamage = true,
				range = 890,
				reloadtime = 5.5999999046326,
				soundhit = "xplodep1",
				soundstart = "torpedo1",
				startvelocity = 100,
				tracks = true,
				turnrate = 20000,
				turret = true,
				waterweapon = true,
				weaponacceleration = 80,
				weapontimer = 3,
				weapontype = "TorpedoLauncher",
				weaponvelocity = 580,
				damage = {
					commanders = 2800,
					default = 1400,
					krogoth = 2800,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "HOVER NOTSHIP",
				def = "CORATL_TORPEDO",
			},
		},
	},
}
