return {
	corjamt = {
		acceleration = 0,
		activatewhenbuilt = true,
		bmcode = 0,
		brakerate = 0,
		buildangle = 9821,
		buildcostenergy = 4791,
		buildcostmetal = 109,
		builder = false,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 4,
		buildinggrounddecalsizey = 4,
		buildinggrounddecaltype = "corjamt_aoplane.dds",
		buildpic = "CORJAMT.DDS",
		buildtime = 4577,
		canattack = false,
		category = "ALL NOTSUB JAM NOWEAPON SPECIAL NOTAIR",
		corpse = "DEAD",
		description = "Short-Range Jamming Device",
		energymake = 0,
		energystorage = 0,
		energyuse = 25,
		explodeas = "BIG_UNITEX",
		footprintx = 2,
		footprintz = 2,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		maxangledif1 = 1,
		maxdamage = 960,
		maxslope = 32,
		maxvelocity = 0,
		maxwaterdepth = 0,
		metalstorage = 0,
		name = "Castro",
		noautofire = false,
		objectname = "CORJAMT",
		onoffable = true,
		radardistancejam = 360,
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		side = "CORE",
		sightdistance = 104,
		smoothanim = false,
		tedclass = "SPECIAL",
		turnrate = 0,
		unitname = "corjamt",
		usebuildinggrounddecal = true,
		workertime = 0,
		yardmap = "oooo",
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				damage = 576,
				description = "Castro Wreckage",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 3,
				hitdensity = 100,
				metal = 71,
				object = "CORJAMT_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "all",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbcormov",
			},
			select = {
				[1] = "radjam2",
			},
		},
	},
}
