return {
	correcl = {
		acceleration = 0.13,
		autoheal = 2,
		brakerate = 0.75,
		buildcostenergy = 4204,
		buildcostmetal = 421,
		builddistance = 140,
		builder = true,
		buildpic = "CORRECL.DDS",
		buildtime = 7596,
		canassist = false,
		canmove = true,
		canresurrect = true,
		category = "UNDERWATER ALL CONSTR NOWEAPON NOTAIR NOTHOVER",
		collisionvolumeoffsets = "0 -3 2",
		collisionvolumescales = "37 15 48",
		collisionvolumetype = "box",
		description = "Ressurection Sub",
		explodeas = "SMALL_UNITEX",
		footprintx = 2,
		footprintz = 2,
		icontype = "sea",
		idleautoheal = 3,
		idletime = 300,
		maxdamage = 621,
		maxvelocity = 2.61,
		minwaterdepth = 15,
		movementclass = "UBOAT3",
		name = "Death Cavalry",
		objectname = "CORRECL",
		repairspeed = 250,
		seismicsignature = 0,
		selfdestructas = "SMALL_UNIT",
		sightdistance = 430,
		sonardistance = 270,
		terraformspeed = 2250,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 1.7226,
		turnrate = 600,
		waterline = 17,
		workertime = 450,
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			capture = "capture1",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "suarmmov",
			},
			select = {
				[1] = "suarmsel",
			},
		},
	},
}
