return {
	krogtaar = {
		acceleration = 0.14399999380112,
		badtargetcategory = "VTOL",
		bmcode = 1,
		brakerate = 0.23800000548363,
		buildcostenergy = 50499,
		buildcostmetal = 6784,
		builder = false,
		buildpic = "krogtaar.DDS",
		buildtime = 101125,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "KBOT WEAPON ALL NOTSUB NOTAIR",
		corpse = "dead",
		defaultmissiontype = "Standby",
		description = "Heavy Weapons Mech",
		energymake = 3,
		energystorage = 0,
		energyuse = 3,
		explodeas = "CRAWL_BLAST",
		firestandorders = 1,
		footprintx = 4,
		footprintz = 4,
		immunetoparalyzer = 1,
		maneuverleashlength = 640,
		mass = 999999995904,
		maxdamage = 70000,
		maxslope = 17,
		maxvelocity = 1.3300000429153,
		maxwaterdepth = 13,
		metalstorage = 0,
		mobilestandorders = 1,
		movementclass = "HKBOT4",
		name = "KrogTaar",
		noautofire = false,
		nochasecategory = "VTOL",
		objectname = "krogtaar",
		radardistance = 0,
		selfdestructas = "CRAWL_BLAST",
		selfdestructcountdown = 10,
		shootme = 1,
		side = "CORE",
		sightdistance = 390,
		smoothanim = true,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 2,
		tedclass = "KBOT",
		turnrate = 1058,
		unitname = "krogtaar",
		unitnumber = 12323,
		upright = true,
		workertime = 0,
		featuredefs = {
			dead = {
				blocking = true,
				category = "cor_corpses",
				damage = 15700,
				description = "Wreckage",
				featuredead = "heap",
				featurereclamate = "smudge01",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				hitdensity = 100,
				metal = 5990,
				object = "krogtaar_dead",
				reclaimable = true,
				seqnamereclamate = "tree1reclamate",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 6960,
				description = "Wreckage",
				featurereclamate = "smudge01",
				footprintx = 3,
				footprintz = 3,
				height = 4,
				hitdensity = 100,
				metal = 4472,
				object = "3x3a",
				reclaimable = true,
				seqnamereclamate = "tree1reclamate",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbcormov",
			},
			select = {
				[1] = "kbcorsel",
			},
		},
		weapondefs = {
			cor_taar_rc = {
				accuracy = 200,
				areaofeffect = 64,
				burnblow = true,
				cegtag = "krogtaarblaster",
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:FLASHKROGTAAR",
				impulseboost = 0.12300000339746,
				impulsefactor = 0.12300000339746,
				intensity = 4,
				lineofsight = true,
				model = "bomb2",
				name = "KrogTaarBlaster",
				noselfdamage = true,
				range = 465,
				reloadtime = 0.40000000596046,
				rendertype = 4,
				rgbcolor = "0 0 0",
				size = 1,
				soundhit = "xplomed3",
				soundstart = "Mavgun2",
				sprayangle = 200,
				startsmoke = 1,
				tolerance = 10000,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 400,
				damage = {
					anniddm = 200,
					default = 344,
					l1subs = 5,
					l2subs = 5,
					l3subs = 5,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "NOWEAPON",
				def = "COR_TAAR_RC",
			},
		},
	},
}
