return {
	nsaclash = {
		acceleration = 0.071999996900558,
		badtargetcategory = "VTOL",
		bmcode = 1,
		brakerate = 0.075000002980232,
		buildcostenergy = 12211,
		buildcostmetal = 600,
		builder = false,
		buildpic = "NSACLASH.DDS",
		buildtime = 12907,
		canattack = true,
		canguard = true,
		canhover = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL HOVER WEAPON NOTSUB NOTAIR",
		corpse = "DEAD",
		defaultmissiontype = "Standby",
		description = "Assault Hovertank",
		energymake = 3.5,
		energystorage = 0,
		energyuse = 3.5,
		explodeas = "BIG_UNITEX",
		firestandorders = 1,
		footprintx = 3,
		footprintz = 3,
		idleautoheal = 5,
		idletime = 1800,
		maneuverleashlength = 640,
		maxdamage = 3465,
		maxslope = 16,
		maxvelocity = 1.4800000190735,
		maxwaterdepth = 0,
		metalstorage = 0,
		mobilestandorders = 1,
		movementclass = "HOVER3",
		name = "Halberd",
		noautofire = false,
		nochasecategory = "VTOL",
		objectname = "NSACLASH",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		side = "CORE",
		sightdistance = 349,
		smoothanim = false,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		tedclass = "TANK",
		turnrate = 410,
		unitname = "nsaclash",
		workertime = 0,
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				damage = 2079,
				description = "Halberd Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				hitdensity = 100,
				metal = 390,
				object = "NSACLASH_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 1040,
				description = "Halberd Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 3,
				footprintz = 3,
				hitdensity = 100,
				metal = 156,
				object = "3X3A",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "hovlgok2",
			},
			select = {
				[1] = "hovlgsl2",
			},
		},
		weapondefs = {
			core_canlaser = {
				areaofeffect = 8,
				beamlaser = 1,
				beamtime = 0.15000000596046,
				corethickness = 0.20000000298023,
				craterboost = 0,
				cratermult = 0,
				energypershot = 75,
				explosiongenerator = "custom:SMALL_GREEN_LASER_BURN",
				firestarter = 90,
				impactonly = 1,
				impulseboost = 0.12300000339746,
				impulsefactor = 0.12300000339746,
				laserflaresize = 10,
				lineofsight = true,
				name = "HighEnergyLaser",
				noselfdamage = true,
				range = 275,
				reloadtime = 0.80000001192093,
				rendertype = 0,
				rgbcolor = "0 1 0",
				soundhit = "lasrhit1",
				soundstart = "lasrhvy3",
				targetmoveerror = 0.20000000298023,
				thickness = 3,
				tolerance = 10000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 700,
				damage = {
					default = 275,
					gunships = 55,
					hgunships = 55,
					l1bombers = 55,
					l1fighters = 55,
					l1subs = 5,
					l2bombers = 55,
					l2fighters = 55,
					l2subs = 5,
					l3subs = 5,
					vradar = 55,
					vtol = 55,
					vtrans = 55,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "CORE_CANLASER",
			},
		},
	},
}
