
UnitTweeks

--Nukes.BCB.FiendishD.a02.lua 
{
corsilo = {
		customparams = {
    			i18n_en_tooltip = 'Cluster Nuke ICBM Launcher',
		},
		weapondefs = {
			crblmssl = {
				areaofeffect = 1000,
				craterareaofeffect = 1000,
				craterboost = 2.4,
				cratermult = 1.2,
				edgeeffectiveness = 0.399,
				flighttime = 600,
				impulsefactor = 5.95,
				stockpiletime = 60,
				tolerance = 4000,
				turnrate = 3580,
				weaponacceleration = 205,
				weapontimer = 5.5,
				weaponvelocity = 1600,
				customparams = {
					cluster_def = 'nuke_cluster',
					cluster_number = 14,
				},
				damage = {
					commanders = 2500,
					default = 31500,
				},
			},
			nuclear_launch = {
				areaofeffect = 0,
				avoidfeature = false,
				avoidfriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0,
				impulsefactor = 0,
				metalpershot = 0,
				name = "Nuclear Launch",
				range = 0,
				reloadtime = 30,
				soundhit = "nukelaunchalarm",
				soundhitvolume = 50,
				tolerance = 10000,
				turnrate = 10000,
				weaponacceleration = 191,
				weapontimer = 0.1,
				weapontype = "Cannon",
				weaponvelocity = 900,
				damage = {
					default = 0,
				},
			},
			nuke_cluster = {
				areaofeffect = 350,
				avoidfeature = false,
				cegtag = "ministarfire",
				craterareaofeffect = 350,
				craterboost = 2.4,
				cratermult = 1.2,
				edgeeffectiveness = 0.45,
				explosiongenerator = "custom:newnukecor",
				gravityaffected = "false",
				impulsefactor = 0.5,
				name = "Cluster Nuke",
				noselfdamage = true,
				range = 650,
				rgbcolor = "0.7 0.7 1.0 1.0 1.0 1.0 1.0 1.0",
				soundhit = "xplomed4",
				soundhitwet = "splsmed",
				soundstart = "cannhvy2",
				weapontype = "Cannon",
				damage = {
					default = 20250,
				},
			},

		},
		weapons = {
			[1] = {
				def = "CRBLMSSL",
				onlytargetcategory = "NOTSUB",
			},
			[2] = {
				def = "NUCLEAR_LAUNCH",
				onlytargetcategory = "NOTSUB",
			},
			[3] = {
				def = "NUKE_CLUSTER",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
armsilo = {
		customparams = {
    			i18n_en_tooltip = 'Bunker Buster Nuke ICBM Launcher',
		},
		weapondefs = {
			nuclear_missile = {
				areaofeffect = 1280,
				craterareaofeffect = 1280,
				craterboost = 2.4,
				cratermult = 1.2,
				edgeeffectiveness = 0.399,
				flighttime = 600,
				impulsefactor = 22.95,
				stockpiletime = 60,
				tolerance = 4000,
				turnrate = 3580,
				weaponacceleration = 205,
				weapontimer = 5.5,
				weaponvelocity = 1655,
				customparams = {
					cluster_def = 'nuke_cluster',
					cluster_number = 90,
				},
				damage = {
					commanders = 2500,
					default = 25500,
				},
			},
			nuclear_launch = {
				areaofeffect = 0,
				avoidfeature = false,
				avoidfriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0,
				impulsefactor = 0,
				metalpershot = 0,
				name = "Nuclear Launch",
				range = 0,
				reloadtime = 30,
				soundhit = "nukelaunchalarm",
				soundhitvolume = 50,
				tolerance = 4000,
				turnrate = 3780,
				weaponacceleration = 330,
				weapontimer = 0.1,
				weapontype = "Cannon",
				weaponvelocity = 955,
				damage = {
					default = 0,
				},
			},
			nuke_cluster = {
				areaofeffect = 1280,
				avoidfeature = false,
				cegtag = "ministarfire",
				craterareaofeffect = 1180,
				craterboost = 45.4,
				cratermult = 6.2,
				edgeeffectiveness = 0.125,
				explosiongenerator = "custom:newnukecor",
				gravityaffected = "true",
		        mygravity = 2000,
				impulsefactor = 22.35,
				name = "Cluster Nuke",
				noselfdamage = true,
				range = 50,
				rgbcolor = "0.7 0.7 1.0 1.0 1.0 1.0 1.0 1.0",
				soundhit = "xplomed4",
				soundhitwet = "splsmed",
				soundstart = "cannhvy2",
				weapontype = "Cannon",
				weaponvelocity = 45,
				damage = {
					commanders = 2500,
					default = 55250,
				},
			},

		},
		weapons = {
			[1] = {
				def = "NUCLEAR_MISSILE",
				onlytargetcategory = "NOTSUB",
			},
			[2] = {
				def = "NUCLEAR_LAUNCH",
				onlytargetcategory = "NOTSUB",
			},
			[3] = {
				def = "NUKE_CLUSTER",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
legsilo = {
		customparams = {
    			i18n_en_tooltip = 'Radioactive Napalm ICBM Launcher',
		},
		weapondefs = {
			legicbm = {
				areaofeffect = 1080,
				craterareaofeffect = 1080,
				craterboost = 2.4,
				cratermult = 1.2,
				edgeeffectiveness = 0.399,
				flighttime = 600,
				impulsefactor = 22.95,
		        mygravity = 2,
				stockpiletime = 60,
				tolerance = 4000,
				turnrate = 3580,
				weaponacceleration = 105,
				weapontimer = 5.5,
				weaponvelocity = 1600,
				customparams = {
					cluster_def = 'nuke_napalm',
					cluster_number = 36,
				},
				damage = {
					commanders = 2500,
					default = 55500,
				},
			},
			nuclear_launch = {
				areaofeffect = 0,
				avoidfeature = false,
				avoidfriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0,
				impulsefactor = 0,
				metalpershot = 0,
				name = "Nuclear Launch",
				range = 0,
				reloadtime = 30,
				soundhit = "nukelaunchalarm",
				soundhitvolume = 50,
				tolerance = 4000,
				turnrate = 1550,
		        mygravity = 0.05,
				weaponacceleration = 1230,
				weapontimer = 0.1,
				weapontype = "Cannon",
				weaponvelocity = 2000,
				damage = {
					default = 0,
				},
			},
			nuke_napalm = {
				areaofeffect = 425,
				avoidfeature = false,
				cegtag = "burnflame",
				colormap = "0.75 0.73 0.67 0.024   0.37 0.4 0.30 0.021   0.22 0.21 0.14 0.018  0.024 0.014 0.009 0.03   0.0 0.0 0.0 0.008",
				craterareaofeffect = 360,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.75,
				explosiongenerator = "custom:fire-explosion-large",
				flamegfxtime = 1,
				gravityaffected = "true",
		        mygravity = 1.25,
				impulsefactor = 0.123,
				name = "Napalm",
				noselfdamage = true,
				projectiles = 1,
				range = 750,
				rgbcolor = ".17 0.98 0.11",
				soundhitdry = "flamhit1",
				soundhitwet = "sizzle",
				soundstart = "cannhvy2",
				sprayangle = 600,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 180,
				customparams = {
					area_onhit_ceg = "fire-area-150-repeat",
					area_onhit_damageCeg = "burnflamexl-gen",
					area_onhit_resistance = "fire",
					area_onhit_damage = 3175,
					area_onhit_range = 300,
					area_onhit_time = 40,
				},
				damage = {
					commanders = 2700,
					default = 42000,
				},
			},
		},
		weapons = {
			[1] = {
				def = "LEGICBM",
				onlytargetcategory = "NOTSUB",
			},
			[2] = {
				def = "NUCLEAR_LAUNCH",
				onlytargetcategory = "NOTSUB",
			},
			[3] = {
				def = "NUKE_NAPALM",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}


LS1OdWtlcy5CQ0IuRmllbmRpc2hELmEwMi5sdWEgDQp7DQpjb3JzaWxvID0gew0KCQljdXN0b21wYXJhbXMgPSB7DQogICAgCQkJaTE4bl9lbl90b29sdGlwID0gJ0NsdXN0ZXIgTnVrZSBJQ0JNIExhdW5jaGVyJywNCgkJfSwNCgkJd2VhcG9uZGVmcyA9IHsNCgkJCWNyYmxtc3NsID0gew0KCQkJCWFyZWFvZmVmZmVjdCA9IDEwMDAsDQoJCQkJY3JhdGVyYXJlYW9mZWZmZWN0ID0gMTAwMCwNCgkJCQljcmF0ZXJib29zdCA9IDIuNCwNCgkJCQljcmF0ZXJtdWx0ID0gMS4yLA0KCQkJCWVkZ2VlZmZlY3RpdmVuZXNzID0gMC4zOTksDQoJCQkJZmxpZ2h0dGltZSA9IDYwMCwNCgkJCQlpbXB1bHNlZmFjdG9yID0gNS45NSwNCgkJCQlzdG9ja3BpbGV0aW1lID0gNjAsDQoJCQkJdG9sZXJhbmNlID0gNDAwMCwNCgkJCQl0dXJucmF0ZSA9IDM1ODAsDQoJCQkJd2VhcG9uYWNjZWxlcmF0aW9uID0gMjA1LA0KCQkJCXdlYXBvbnRpbWVyID0gNS41LA0KCQkJCXdlYXBvbnZlbG9jaXR5ID0gMTYwMCwNCgkJCQljdXN0b21wYXJhbXMgPSB7DQoJCQkJCWNsdXN0ZXJfZGVmID0gJ251a2VfY2x1c3RlcicsDQoJCQkJCWNsdXN0ZXJfbnVtYmVyID0gMTQsDQoJCQkJfSwNCgkJCQlkYW1hZ2UgPSB7DQoJCQkJCWNvbW1hbmRlcnMgPSAyNTAwLA0KCQkJCQlkZWZhdWx0ID0gMzE1MDAsDQoJCQkJfSwNCgkJCX0sDQoJCQludWNsZWFyX2xhdW5jaCA9IHsNCgkJCQlhcmVhb2ZlZmZlY3QgPSAwLA0KCQkJCWF2b2lkZmVhdHVyZSA9IGZhbHNlLA0KCQkJCWF2b2lkZnJpZW5kbHkgPSBmYWxzZSwNCgkJCQljcmF0ZXJhcmVhb2ZlZmZlY3QgPSAwLA0KCQkJCWNyYXRlcmJvb3N0ID0gMCwNCgkJCQljcmF0ZXJtdWx0ID0gMCwNCgkJCQllZGdlZWZmZWN0aXZlbmVzcyA9IDAsDQoJCQkJaW1wdWxzZWZhY3RvciA9IDAsDQoJCQkJbWV0YWxwZXJzaG90ID0gMCwNCgkJCQluYW1lID0gIk51Y2xlYXIgTGF1bmNoIiwNCgkJCQlyYW5nZSA9IDAsDQoJCQkJcmVsb2FkdGltZSA9IDMwLA0KCQkJCXNvdW5kaGl0ID0gIm51a2VsYXVuY2hhbGFybSIsDQoJCQkJc291bmRoaXR2b2x1bWUgPSA1MCwNCgkJCQl0b2xlcmFuY2UgPSAxMDAwMCwNCgkJCQl0dXJucmF0ZSA9IDEwMDAwLA0KCQkJCXdlYXBvbmFjY2VsZXJhdGlvbiA9IDE5MSwNCgkJCQl3ZWFwb250aW1lciA9IDAuMSwNCgkJCQl3ZWFwb250eXBlID0gIkNhbm5vbiIsDQoJCQkJd2VhcG9udmVsb2NpdHkgPSA5MDAsDQoJCQkJZGFtYWdlID0gew0KCQkJCQlkZWZhdWx0ID0gMCwNCgkJCQl9LA0KCQkJfSwNCgkJCW51a2VfY2x1c3RlciA9IHsNCgkJCQlhcmVhb2ZlZmZlY3QgPSAzNTAsDQoJCQkJYXZvaWRmZWF0dXJlID0gZmFsc2UsDQoJCQkJY2VndGFnID0gIm1pbmlzdGFyZmlyZSIsDQoJCQkJY3JhdGVyYXJlYW9mZWZmZWN0ID0gMzUwLA0KCQkJCWNyYXRlcmJvb3N0ID0gMi40LA0KCQkJCWNyYXRlcm11bHQgPSAxLjIsDQoJCQkJZWRnZWVmZmVjdGl2ZW5lc3MgPSAwLjQ1LA0KCQkJCWV4cGxvc2lvbmdlbmVyYXRvciA9ICJjdXN0b206bmV3bnVrZWNvciIsDQoJCQkJZ3Jhdml0eWFmZmVjdGVkID0gImZhbHNlIiwNCgkJCQlpbXB1bHNlZmFjdG9yID0gMC41LA0KCQkJCW5hbWUgPSAiQ2x1c3RlciBOdWtlIiwNCgkJCQlub3NlbGZkYW1hZ2UgPSB0cnVlLA0KCQkJCXJhbmdlID0gNjUwLA0KCQkJCXJnYmNvbG9yID0gIjAuNyAwLjcgMS4wIDEuMCAxLjAgMS4wIDEuMCAxLjAiLA0KCQkJCXNvdW5kaGl0ID0gInhwbG9tZWQ0IiwNCgkJCQlzb3VuZGhpdHdldCA9ICJzcGxzbWVkIiwNCgkJCQlzb3VuZHN0YXJ0ID0gImNhbm5odnkyIiwNCgkJCQl3ZWFwb250eXBlID0gIkNhbm5vbiIsDQoJCQkJZGFtYWdlID0gew0KCQkJCQlkZWZhdWx0ID0gMjAyNTAsDQoJCQkJfSwNCgkJCX0sDQoNCgkJfSwNCgkJd2VhcG9ucyA9IHsNCgkJCVsxXSA9IHsNCgkJCQlkZWYgPSAiQ1JCTE1TU0wiLA0KCQkJCW9ubHl0YXJnZXRjYXRlZ29yeSA9ICJOT1RTVUIiLA0KCQkJfSwNCgkJCVsyXSA9IHsNCgkJCQlkZWYgPSAiTlVDTEVBUl9MQVVOQ0giLA0KCQkJCW9ubHl0YXJnZXRjYXRlZ29yeSA9ICJOT1RTVUIiLA0KCQkJfSwNCgkJCVszXSA9IHsNCgkJCQlkZWYgPSAiTlVLRV9DTFVTVEVSIiwNCgkJCQlvbmx5dGFyZ2V0Y2F0ZWdvcnkgPSAiTk9UU1VCIiwNCgkJCX0sDQoJCX0sDQoJfSwNCmFybXNpbG8gPSB7DQoJCWN1c3RvbXBhcmFtcyA9IHsNCiAgICAJCQlpMThuX2VuX3Rvb2x0aXAgPSAnQnVua2VyIEJ1c3RlciBOdWtlIElDQk0gTGF1bmNoZXInLA0KCQl9LA0KCQl3ZWFwb25kZWZzID0gew0KCQkJbnVjbGVhcl9taXNzaWxlID0gew0KCQkJCWFyZWFvZmVmZmVjdCA9IDEyODAsDQoJCQkJY3JhdGVyYXJlYW9mZWZmZWN0ID0gMTI4MCwNCgkJCQljcmF0ZXJib29zdCA9IDIuNCwNCgkJCQljcmF0ZXJtdWx0ID0gMS4yLA0KCQkJCWVkZ2VlZmZlY3RpdmVuZXNzID0gMC4zOTksDQoJCQkJZmxpZ2h0dGltZSA9IDYwMCwNCgkJCQlpbXB1bHNlZmFjdG9yID0gMjIuOTUsDQoJCQkJc3RvY2twaWxldGltZSA9IDYwLA0KCQkJCXRvbGVyYW5jZSA9IDQwMDAsDQoJCQkJdHVybnJhdGUgPSAzNTgwLA0KCQkJCXdlYXBvbmFjY2VsZXJhdGlvbiA9IDIwNSwNCgkJCQl3ZWFwb250aW1lciA9IDUuNSwNCgkJCQl3ZWFwb252ZWxvY2l0eSA9IDE2NTUsDQoJCQkJY3VzdG9tcGFyYW1zID0gew0KCQkJCQljbHVzdGVyX2RlZiA9ICdudWtlX2NsdXN0ZXInLA0KCQkJCQljbHVzdGVyX251bWJlciA9IDkwLA0KCQkJCX0sDQoJCQkJZGFtYWdlID0gew0KCQkJCQljb21tYW5kZXJzID0gMjUwMCwNCgkJCQkJZGVmYXVsdCA9IDI1NTAwLA0KCQkJCX0sDQoJCQl9LA0KCQkJbnVjbGVhcl9sYXVuY2ggPSB7DQoJCQkJYXJlYW9mZWZmZWN0ID0gMCwNCgkJCQlhdm9pZGZlYXR1cmUgPSBmYWxzZSwNCgkJCQlhdm9pZGZyaWVuZGx5ID0gZmFsc2UsDQoJCQkJY3JhdGVyYXJlYW9mZWZmZWN0ID0gMCwNCgkJCQljcmF0ZXJib29zdCA9IDAsDQoJCQkJY3JhdGVybXVsdCA9IDAsDQoJCQkJZWRnZWVmZmVjdGl2ZW5lc3MgPSAwLA0KCQkJCWltcHVsc2VmYWN0b3IgPSAwLA0KCQkJCW1ldGFscGVyc2hvdCA9IDAsDQoJCQkJbmFtZSA9ICJOdWNsZWFyIExhdW5jaCIsDQoJCQkJcmFuZ2UgPSAwLA0KCQkJCXJlbG9hZHRpbWUgPSAzMCwNCgkJCQlzb3VuZGhpdCA9ICJudWtlbGF1bmNoYWxhcm0iLA0KCQkJCXNvdW5kaGl0dm9sdW1lID0gNTAsDQoJCQkJdG9sZXJhbmNlID0gNDAwMCwNCgkJCQl0dXJucmF0ZSA9IDM3ODAsDQoJCQkJd2VhcG9uYWNjZWxlcmF0aW9uID0gMzMwLA0KCQkJCXdlYXBvbnRpbWVyID0gMC4xLA0KCQkJCXdlYXBvbnR5cGUgPSAiQ2Fubm9uIiwNCgkJCQl3ZWFwb252ZWxvY2l0eSA9IDk1NSwNCgkJCQlkYW1hZ2UgPSB7DQoJCQkJCWRlZmF1bHQgPSAwLA0KCQkJCX0sDQoJCQl9LA0KCQkJbnVrZV9jbHVzdGVyID0gew0KCQkJCWFyZWFvZmVmZmVjdCA9IDEyODAsDQoJCQkJYXZvaWRmZWF0dXJlID0gZmFsc2UsDQoJCQkJY2VndGFnID0gIm1pbmlzdGFyZmlyZSIsDQoJCQkJY3JhdGVyYXJlYW9mZWZmZWN0ID0gMTE4MCwNCgkJCQljcmF0ZXJib29zdCA9IDQ1LjQsDQoJCQkJY3JhdGVybXVsdCA9IDYuMiwNCgkJCQllZGdlZWZmZWN0aXZlbmVzcyA9IDAuMTI1LA0KCQkJCWV4cGxvc2lvbmdlbmVyYXRvciA9ICJjdXN0b206bmV3bnVrZWNvciIsDQoJCQkJZ3Jhdml0eWFmZmVjdGVkID0gInRydWUiLA0KCQkgICAgICAgIG15Z3Jhdml0eSA9IDIwMDAsDQoJCQkJaW1wdWxzZWZhY3RvciA9IDIyLjM1LA0KCQkJCW5hbWUgPSAiQ2x1c3RlciBOdWtlIiwNCgkJCQlub3NlbGZkYW1hZ2UgPSB0cnVlLA0KCQkJCXJhbmdlID0gNTAsDQoJCQkJcmdiY29sb3IgPSAiMC43IDAuNyAxLjAgMS4wIDEuMCAxLjAgMS4wIDEuMCIsDQoJCQkJc291bmRoaXQgPSAieHBsb21lZDQiLA0KCQkJCXNvdW5kaGl0d2V0ID0gInNwbHNtZWQiLA0KCQkJCXNvdW5kc3RhcnQgPSAiY2Fubmh2eTIiLA0KCQkJCXdlYXBvbnR5cGUgPSAiQ2Fubm9uIiwNCgkJCQl3ZWFwb252ZWxvY2l0eSA9IDQ1LA0KCQkJCWRhbWFnZSA9IHsNCgkJCQkJY29tbWFuZGVycyA9IDI1MDAsDQoJCQkJCWRlZmF1bHQgPSA1NTI1MCwNCgkJCQl9LA0KCQkJfSwNCg0KCQl9LA0KCQl3ZWFwb25zID0gew0KCQkJWzFdID0gew0KCQkJCWRlZiA9ICJOVUNMRUFSX01JU1NJTEUiLA0KCQkJCW9ubHl0YXJnZXRjYXRlZ29yeSA9ICJOT1RTVUIiLA0KCQkJfSwNCgkJCVsyXSA9IHsNCgkJCQlkZWYgPSAiTlVDTEVBUl9MQVVOQ0giLA0KCQkJCW9ubHl0YXJnZXRjYXRlZ29yeSA9ICJOT1RTVUIiLA0KCQkJfSwNCgkJCVszXSA9IHsNCgkJCQlkZWYgPSAiTlVLRV9DTFVTVEVSIiwNCgkJCQlvbmx5dGFyZ2V0Y2F0ZWdvcnkgPSAiTk9UU1VCIiwNCgkJCX0sDQoJCX0sDQoJfSwNCmxlZ3NpbG8gPSB7DQoJCWN1c3RvbXBhcmFtcyA9IHsNCiAgICAJCQlpMThuX2VuX3Rvb2x0aXAgPSAnUmFkaW9hY3RpdmUgTmFwYWxtIElDQk0gTGF1bmNoZXInLA0KCQl9LA0KCQl3ZWFwb25kZWZzID0gew0KCQkJbGVnaWNibSA9IHsNCgkJCQlhcmVhb2ZlZmZlY3QgPSAxMDgwLA0KCQkJCWNyYXRlcmFyZWFvZmVmZmVjdCA9IDEwODAsDQoJCQkJY3JhdGVyYm9vc3QgPSAyLjQsDQoJCQkJY3JhdGVybXVsdCA9IDEuMiwNCgkJCQllZGdlZWZmZWN0aXZlbmVzcyA9IDAuMzk5LA0KCQkJCWZsaWdodHRpbWUgPSA2MDAsDQoJCQkJaW1wdWxzZWZhY3RvciA9IDIyLjk1LA0KCQkgICAgICAgIG15Z3Jhdml0eSA9IDIsDQoJCQkJc3RvY2twaWxldGltZSA9IDYwLA0KCQkJCXRvbGVyYW5jZSA9IDQwMDAsDQoJCQkJdHVybnJhdGUgPSAzNTgwLA0KCQkJCXdlYXBvbmFjY2VsZXJhdGlvbiA9IDEwNSwNCgkJCQl3ZWFwb250aW1lciA9IDUuNSwNCgkJCQl3ZWFwb252ZWxvY2l0eSA9IDE2MDAsDQoJCQkJY3VzdG9tcGFyYW1zID0gew0KCQkJCQljbHVzdGVyX2RlZiA9ICdudWtlX25hcGFsbScsDQoJCQkJCWNsdXN0ZXJfbnVtYmVyID0gMzYsDQoJCQkJfSwNCgkJCQlkYW1hZ2UgPSB7DQoJCQkJCWNvbW1hbmRlcnMgPSAyNTAwLA0KCQkJCQlkZWZhdWx0ID0gNTU1MDAsDQoJCQkJfSwNCgkJCX0sDQoJCQludWNsZWFyX2xhdW5jaCA9IHsNCgkJCQlhcmVhb2ZlZmZlY3QgPSAwLA0KCQkJCWF2b2lkZmVhdHVyZSA9IGZhbHNlLA0KCQkJCWF2b2lkZnJpZW5kbHkgPSBmYWxzZSwNCgkJCQljcmF0ZXJhcmVhb2ZlZmZlY3QgPSAwLA0KCQkJCWNyYXRlcmJvb3N0ID0gMCwNCgkJCQljcmF0ZXJtdWx0ID0gMCwNCgkJCQllZGdlZWZmZWN0aXZlbmVzcyA9IDAsDQoJCQkJaW1wdWxzZWZhY3RvciA9IDAsDQoJCQkJbWV0YWxwZXJzaG90ID0gMCwNCgkJCQluYW1lID0gIk51Y2xlYXIgTGF1bmNoIiwNCgkJCQlyYW5nZSA9IDAsDQoJCQkJcmVsb2FkdGltZSA9IDMwLA0KCQkJCXNvdW5kaGl0ID0gIm51a2VsYXVuY2hhbGFybSIsDQoJCQkJc291bmRoaXR2b2x1bWUgPSA1MCwNCgkJCQl0b2xlcmFuY2UgPSA0MDAwLA0KCQkJCXR1cm5yYXRlID0gMTU1MCwNCgkJICAgICAgICBteWdyYXZpdHkgPSAwLjA1LA0KCQkJCXdlYXBvbmFjY2VsZXJhdGlvbiA9IDEyMzAsDQoJCQkJd2VhcG9udGltZXIgPSAwLjEsDQoJCQkJd2VhcG9udHlwZSA9ICJDYW5ub24iLA0KCQkJCXdlYXBvbnZlbG9jaXR5ID0gMjAwMCwNCgkJCQlkYW1hZ2UgPSB7DQoJCQkJCWRlZmF1bHQgPSAwLA0KCQkJCX0sDQoJCQl9LA0KCQkJbnVrZV9uYXBhbG0gPSB7DQoJCQkJYXJlYW9mZWZmZWN0ID0gNDI1LA0KCQkJCWF2b2lkZmVhdHVyZSA9IGZhbHNlLA0KCQkJCWNlZ3RhZyA9ICJidXJuZmxhbWUiLA0KCQkJCWNvbG9ybWFwID0gIjAuNzUgMC43MyAwLjY3IDAuMDI0ICAgMC4zNyAwLjQgMC4zMCAwLjAyMSAgIDAuMjIgMC4yMSAwLjE0IDAuMDE4ICAwLjAyNCAwLjAxNCAwLjAwOSAwLjAzICAgMC4wIDAuMCAwLjAgMC4wMDgiLA0KCQkJCWNyYXRlcmFyZWFvZmVmZmVjdCA9IDM2MCwNCgkJCQljcmF0ZXJib29zdCA9IDAsDQoJCQkJY3JhdGVybXVsdCA9IDAsDQoJCQkJZWRnZWVmZmVjdGl2ZW5lc3MgPSAwLjc1LA0KCQkJCWV4cGxvc2lvbmdlbmVyYXRvciA9ICJjdXN0b206ZmlyZS1leHBsb3Npb24tbGFyZ2UiLA0KCQkJCWZsYW1lZ2Z4dGltZSA9IDEsDQoJCQkJZ3Jhdml0eWFmZmVjdGVkID0gInRydWUiLA0KCQkgICAgICAgIG15Z3Jhdml0eSA9IDEuMjUsDQoJCQkJaW1wdWxzZWZhY3RvciA9IDAuMTIzLA0KCQkJCW5hbWUgPSAiTmFwYWxtIiwNCgkJCQlub3NlbGZkYW1hZ2UgPSB0cnVlLA0KCQkJCXByb2plY3RpbGVzID0gMSwNCgkJCQlyYW5nZSA9IDc1MCwNCgkJCQlyZ2Jjb2xvciA9ICIuMTcgMC45OCAwLjExIiwNCgkJCQlzb3VuZGhpdGRyeSA9ICJmbGFtaGl0MSIsDQoJCQkJc291bmRoaXR3ZXQgPSAic2l6emxlIiwNCgkJCQlzb3VuZHN0YXJ0ID0gImNhbm5odnkyIiwNCgkJCQlzcHJheWFuZ2xlID0gNjAwLA0KCQkJCXR1cnJldCA9IHRydWUsDQoJCQkJd2VhcG9udHlwZSA9ICJDYW5ub24iLA0KCQkJCXdlYXBvbnZlbG9jaXR5ID0gMTgwLA0KCQkJCWN1c3RvbXBhcmFtcyA9IHsNCgkJCQkJYXJlYV9vbmhpdF9jZWcgPSAiZmlyZS1hcmVhLTE1MC1yZXBlYXQiLA0KCQkJCQlhcmVhX29uaGl0X2RhbWFnZUNlZyA9ICJidXJuZmxhbWV4bC1nZW4iLA0KCQkJCQlhcmVhX29uaGl0X3Jlc2lzdGFuY2UgPSAiZmlyZSIsDQoJCQkJCWFyZWFfb25oaXRfZGFtYWdlID0gMzE3NSwNCgkJCQkJYXJlYV9vbmhpdF9yYW5nZSA9IDMwMCwNCgkJCQkJYXJlYV9vbmhpdF90aW1lID0gNDAsDQoJCQkJfSwNCgkJCQlkYW1hZ2UgPSB7DQoJCQkJCWNvbW1hbmRlcnMgPSAyNzAwLA0KCQkJCQlkZWZhdWx0ID0gNDIwMDAsDQoJCQkJfSwNCgkJCX0sDQoJCX0sDQoJCXdlYXBvbnMgPSB7DQoJCQlbMV0gPSB7DQoJCQkJZGVmID0gIkxFR0lDQk0iLA0KCQkJCW9ubHl0YXJnZXRjYXRlZ29yeSA9ICJOT1RTVUIiLA0KCQkJfSwNCgkJCVsyXSA9IHsNCgkJCQlkZWYgPSAiTlVDTEVBUl9MQVVOQ0giLA0KCQkJCW9ubHl0YXJnZXRjYXRlZ29yeSA9ICJOT1RTVUIiLA0KCQkJfSwNCgkJCVszXSA9IHsNCgkJCQlkZWYgPSAiTlVLRV9OQVBBTE0iLA0KCQkJCW9ubHl0YXJnZXRjYXRlZ29yeSA9ICJTVVJGQUNFIiwNCgkJCX0sDQoJCX0sDQoJfSwNCn0