function widget:GetInfo()
	return {
		name = "Factionpicker",
		desc = "",
		author = "Floris",
		date = "May 2020",
		license = "GNU GPL, v2 or later",
		layer = -1,
		enabled = true
	}
end

----------------------------
-- Playable Factions list --
----------------------------
local factions = {
	{ startUnit = UnitDefNames.corcom.id, faction = 'cor', enabled = true },
	{ startUnit = UnitDefNames.armcom.id, faction = 'arm', enabled = true },
}
if Spring.GetModOptions().experimentallegionfaction then
	factions[#factions+1] = { startUnit = UnitDefNames.legcom.id, faction = 'leg', enabled = true }
end

-------------------------------
-- custom faction extraction
--	-- allows for custom factions/start units via custom parameters
--	--customparams = {
--		--	-- Required:
--		-- customfaction = "cationName"		Should be at least 3 letters long,
--
--		--	-- Optional:
--		-- customfactionscav = not nil, 	Allow units ending with _scav to also be a valid start option, typically autogenerated copying the orginal unit
--
--		--	-- Extra:
--		-- iscommander = true,				Consider giving this to units turned into start units to prevent premature game ends
-------------------------------
for name, def in pairs(UnitDefs) do
	if def.customParams and def.customParams.customfaction then
		-- exclude scavanger units unless exempt
		if string.find(def.name, "_scav") == nil or def.customParams.customfactionscav == true then
			if type(def.customParams.customfaction) == "string" then
				factions[#factions+1] = {
					startUnit = name,
					faction = string.lower(def.customParams.customfaction),
					--faction = string.sub(def.customParams.customfaction, 1, 3),
					enabled = true
				}
			end
		end
	end
end

-- faction restrictions
	-- Rules Param list generated by gadget/game_initial_spawn.lua
	-- Acquires the relevant list of allowed units, disable the others cosmetically only in case of issues
do
	local lim = Spring.GetGameRulesParam("faction_list_count")
	if lim then
		local list = Spring.GetGameRulesParam("faction_list_"..(Spring.GetLocalAllyTeamID() % lim + 1))
		-- need to split the list, as to not find units that aren't in the list, e.g. 10 in 110
		local listSplit = string.split(list,",")
		local tmp
		-- cross check the lists
		for i = 1, #factions do
			tmp = factions[i]
			tmp.enabled = false
			for j = 1, #listSplit do
				if tmp.startUnit == tonumber(listSplit[j]) then
					tmp.enabled = true
					break
				end
			end
		end
	end
end

-- clean up faction names for language file use
-- e.g. anything starting with "cor" will apear with the cortex faction title and description
for i = 1, #factions do
	factions[i].faction = string.sub(factions[i].faction, 1, 3)
end

----------------------------------------------------------------
-- faction picker grid sizeing
----------------------------------------------------------------
local doUpdate
local playSounds = true
local posY = 0.75
local posX = 0
local width = 0
local height = 0
local bgBorderOrg = 0.003
local bgBorder = bgBorderOrg

local myTeamID = Spring.GetMyTeamID()
local stickToBottom = true

local startDefID = Spring.GetTeamRulesParam(myTeamID, 'startUnit')

local factionRect = {}
for i, faction in pairs(factions) do
	factionRect[i] = {}
end

local vsx, vsy = Spring.GetViewGeometry()
local fontfile2 = "fonts/" .. Spring.GetConfigString("bar_font2", "Exo2-SemiBold.otf")

local sound_button = 'LuaUI/Sounds/buildbar_waypoint.wav'

local ui_scale = tonumber(Spring.GetConfigFloat("ui_scale", 1) or 1)

local isSpec = Spring.GetSpectatingState()
local backgroundRect = {}

local math_isInRect = math.isInRect

local glColor = gl.Color
local glBlending = gl.Blending
local GL_SRC_ALPHA = GL.SRC_ALPHA
local GL_ONE_MINUS_SRC_ALPHA = GL.ONE_MINUS_SRC_ALPHA
local GL_ONE = GL.ONE

local font, font2, bgpadding, dlistGuishader, dlistFactionpicker, bpWidth, bpHeight, rectMargin, fontSize

local RectRound, UiElement, UiUnit
local cellSize, contentPadding

local function drawFactionpicker()
	
	font2:Begin()
	font2:SetTextColor(1, 1, 1, 1)
	font2:SetOutlineColor(0, 0, 0, 0.66)
	font2:Print(Spring.I18N('ui.factionPicker.pick'), backgroundRect[1] + contentPadding, backgroundRect[4] - contentPadding - (fontSize * 0.7), fontSize, "o")
	UiElement(backgroundRect[1], backgroundRect[2], backgroundRect[3], backgroundRect[4], 1, 1, ((posY - height > 0 or posX <= 0) and 1 or 0), 0)

	local padding = bgpadding
	local faction

	for i = 1, #factions do
	--for i, faction in pairs(factions) do
	faction = factions[i]
		factionRect[i] = {
			math.floor(backgroundRect[3] - padding - (cellSize * ((i-1) % 4+1))),
			math.floor(backgroundRect[2] + (cellSize * math.floor((i-1)*0.25))),
			math.floor(backgroundRect[3] - padding - (cellSize * (((i-1) % 4+1) - 1))),
			math.floor(backgroundRect[2] + (cellSize * math.floor((i-1)*0.25)) + cellSize)
		}
		if factions[i].enabled then
			local disabled = Spring.GetTeamRulesParam(myTeamID, 'startUnit') ~= factions[i].startUnit
			if disabled then
				glColor(0.55, 0.55, 0.55, 1)
			else
				glColor(1, 1, 1, 1)
			end
		else
			glColor(0.25, 0.25, 0.25, 1)
		end
		UiUnit(factionRect[i][1] + bgpadding, factionRect[i][2] + bgpadding, factionRect[i][3], factionRect[i][4],
			nil,
			1, 1, 1, 1,
			0,
			nil, disabled and 0.033 or nil,
			'#' .. factions[i].startUnit
		)
		-- faction name
		font2:Print((disabled and "\255\170\170\170" or "\255\255\255\255") .. Spring.I18N('units.factions.' .. factions[i].faction), factionRect[i][1] + ((factionRect[i][3] - factionRect[i][1]) * 0.5), factionRect[i][2] + ((factionRect[i][4] - factionRect[i][2]) * 0.22) - (fontSize * 0.5), fontSize * 0.96, "co")

		if WG['tooltip'] ~= nil then
			local text = Spring.I18N('ui.factionPicker.factions.'..factions[i].faction)
			local tooltip = ''
			local maxWidth = WG['tooltip'].getFontsize() * 80
			local textLines, numLines = font:WrapText(text, maxWidth)
			tooltip = tooltip..string.gsub(textLines, '[\n]', '\n')..'\n'
			WG['tooltip'].AddTooltip('factionpicker_'..i, { factionRect[i][1] + bgpadding, factionRect[i][2] + bgpadding, factionRect[i][3], factionRect[i][4] }, tooltip, nil, Spring.I18N('units.factions.' .. factions[i].faction))
		end
	end
	font2:End()
end

local function checkGuishader(force)
	if WG['guishader'] then
		if force and dlistGuishader then
			dlistGuishader = gl.DeleteList(dlistGuishader)
		end
		if not dlistGuishader then
			dlistGuishader = gl.CreateList(function()
				RectRound(backgroundRect[1], backgroundRect[2], backgroundRect[3], backgroundRect[4], (bgBorder * vsy) * 2)
			end)
			WG['guishader'].InsertDlist(dlistGuishader, 'factionpicker')
		end
	elseif dlistGuishader then
		dlistGuishader = gl.DeleteList(dlistGuishader)
	end
end

function widget:PlayerChanged(playerID)
	isSpec = Spring.GetSpectatingState()
end

function widget:ViewResize()
	vsx, vsy = Spring.GetViewGeometry()

	width = 0.2125
	height = 0.14 * ui_scale

	width = width / (vsx / vsy) * 1.78        -- make smaller for ultrawide screens
	width = width * ui_scale

	-- make pixel aligned
	width = math.floor(width * vsx) / vsx
	height = math.floor(height * vsy) / vsy

	local buildmenuBottomPos
	if WG['buildmenu'] then
		buildmenuBottomPos = WG['buildmenu'].getBottomPosition()
	end

	font = WG['fonts'].getFont()
	font2 = WG['fonts'].getFont(fontfile2)

	local widgetSpaceMargin = WG.FlowUI.elementMargin
	bgpadding = WG.FlowUI.elementPadding

	RectRound = WG.FlowUI.Draw.RectRound
	UiElement = WG.FlowUI.Draw.Element
	UiUnit = WG.FlowUI.Draw.Unit

	if WG['minimap'] then
		minimapHeight = WG['minimap'].getHeight()
	end

	if stickToBottom then
		posY = height
		posX = width + (widgetSpaceMargin / vsx)
	else
		if buildmenuBottomPos then
			posX = 0
			posY = height + height + (widgetSpaceMargin / vsy)
		elseif WG['buildmenu'] then
			local posY2, _ = WG['buildmenu'].getSize()
			posY2 = posY2 + (widgetSpaceMargin / vsy)
			posY = posY2 + height
			if WG['minimap'] then
				posY = 1 - (minimapHeight / vsy) - (widgetSpaceMargin / vsy)
			end
			posX = 0
		end
	end

	backgroundRect = { posX * vsx, (posY - height) * vsy, (posX + width) * vsx, posY * vsy }

	dlistFactionpicker = gl.DeleteList(dlistFactionpicker)

	checkGuishader(true)

	doUpdate = true

	fontSize = (height * vsy * 0.125) * (1 - ((1 - ui_scale) * 0.5))
	
	-- code used to be formally under drawFactionpicker, migrated here to resize background rect where more approprate
	contentPadding = math.floor((height * vsy * 0.09) * (1 - ((1 - ui_scale) * 0.5)))
	local contentWidth = math.floor(backgroundRect[3] - backgroundRect[1] - contentPadding)
	local contentHeight = math.floor(backgroundRect[4] - backgroundRect[2] - (contentPadding * 1.33))
	local maxCellHeight = math.floor((contentHeight - (fontSize * 1.1)) + 0.5)
	local maxCellWidth = math.floor((contentWidth / math.min(#factions,4)) + 0.5)
	cellSize = math.min(maxCellHeight, maxCellWidth)
	-- expand the background rectangle by number of factions if needed
	backgroundRect[4] = backgroundRect[4] + cellSize * math.floor( (#factions-1) * 0.25 )
	-- end of great southern migration

end

function widget:Initialize()
	if isSpec or Spring.GetGameFrame() > 0 then
		widgetHandler:RemoveWidget()
		return
	end

	if Spring.GetModOptions().scenariooptions then
		local scenarioopts = string.base64Decode(Spring.GetModOptions().scenariooptions)
		scenarioopts = Json.decode(scenarioopts)
		if scenarioopts and scenarioopts.disablefactionpicker == true then
			widgetHandler:RemoveWidget()
			return
		end
	end

	if WG['ordermenu'] then
		stickToBottom = WG['ordermenu'].getBottomPosition()
	end

	widget:ViewResize()
end

function widget:Shutdown()
	if WG['guishader'] and dlistGuishader then
		WG['guishader'].DeleteDlist('factionpicker')
		dlistGuishader = nil
	end
	dlistFactionpicker = gl.DeleteList(dlistFactionpicker)

	if WG['tooltip'] ~= nil then
		for i, faction in pairs(factions) do
			WG['tooltip'].RemoveTooltip('factionpicker_'..i)
		end
	end
end

function widget:GameFrame(n)
	widgetHandler:RemoveWidget()
end

local sec = 0
function widget:Update(dt)
	sec = sec + dt
	if sec > 0.5 then
		doUpdate = true
		sec = 0
		checkGuishader()

		if WG['minimap'] and minimapHeight ~= WG['minimap'].getHeight() then
			widget:ViewResize()
			doUpdate = true
		end

		if WG['ordermenu'] and stickToBottom ~= WG['ordermenu'].getBottomPosition() then
			stickToBottom = WG['ordermenu'].getBottomPosition()
			widget:ViewResize()
			doUpdate = true
		end
	end
end

function widget:DrawScreen()
	local x, y, b = Spring.GetMouseState()
	if not WG['topbar'] or not WG['topbar'].showingQuit() then
		if math_isInRect(x, y, backgroundRect[1], backgroundRect[2], backgroundRect[3], backgroundRect[4]) then
			Spring.SetMouseCursor('cursornormal')
		end
	end

	if startDefID ~= Spring.GetTeamRulesParam(myTeamID, 'startUnit') then
		startDefID = Spring.GetTeamRulesParam(myTeamID, 'startUnit')
		doUpdate = true
	end

	if dlistGuishader and WG['guishader'] then
		WG['guishader'].InsertDlist(dlistGuishader, 'factionpicker')
	end
	if doUpdate then
		dlistFactionpicker = gl.DeleteList(dlistFactionpicker)
	end
	if not dlistFactionpicker then
		dlistFactionpicker = gl.CreateList(function()
			drawFactionpicker()
		end)
	end
	gl.CallList(dlistFactionpicker)

	font2:Begin()
	font2:SetOutlineColor(0, 0, 0, 0.66)
	font2:SetTextColor(1, 1, 1, 1)
	font2:SetOutlineColor(0, 0, 0, 0.66)
	-- highlight
	if math_isInRect(x, y, backgroundRect[1], backgroundRect[2], backgroundRect[3], backgroundRect[4]) then
		for i, faction in pairs(factions) do
			if math_isInRect(x, y, factionRect[i][1], factionRect[i][2], factionRect[i][3], factionRect[i][4]) then
				glBlending(GL_SRC_ALPHA, GL_ONE)
				RectRound(factionRect[i][1] + bgpadding, factionRect[i][2] + bgpadding, factionRect[i][3], factionRect[i][4], bgpadding, 1, 1, 1, 1, { 0.3, 0.3, 0.3, (b and 0.5 or 0.25) }, { 1, 1, 1, (b and 0.3 or 0.15) })
				glBlending(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)

				font2:Print(Spring.I18N('units.factions.' .. factions[i].faction), factionRect[i][1] + ((factionRect[i][3] - factionRect[i][1]) * 0.5), factionRect[i][2] + ((factionRect[i][4] - factionRect[i][2]) * 0.22) - (fontSize * 0.5), fontSize * 0.96, "co")
				break
			end
		end
	end
	font2:End()

	doUpdate = nil
end

function widget:MousePress(x, y, button)
	if math_isInRect(x, y, backgroundRect[1], backgroundRect[2], backgroundRect[3], backgroundRect[4]) then

		for i, faction in pairs(factions) do
			if math_isInRect(x, y, factionRect[i][1], factionRect[i][2], factionRect[i][3], factionRect[i][4]) then
				if playSounds then
					Spring.PlaySoundFile(sound_button, 0.6, 'ui')
				end
				-- tell initial spawn
				Spring.SendLuaRulesMsg('\138' .. tostring(factions[i].startUnit))
				break
			end
		end
		return true
	end
end

