return {
	legcv = {
		maxacc = 0.03049,
		maxdec = 0.06099,
		energycost = 2100,
		metalcost = 145,
		builddistance = 130,
		builder = true,
		buildpic = "LEGCV.DDS",
		buildtime = 4160,
		canmove = true,
		category = "ALL TANK MOBILE NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "35 22 49",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energymake = 10,
		energystorage = 50,
		explodeas = "mediumexplosiongeneric-builder",
		footprintx = 3,
		footprintz = 3,
		idleautoheal = 5,
		idletime = 1800,
		leavetracks = true,
		health = 1430,
		maxslope = 16,
		speed = 51.0,
		maxwaterdepth = 19,
		movementclass = "TANK3",
		objectname = "Units/LEGCV.s3o",
		radardistance = 50,
		script = "Units/LEGCV.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd-builder",
		sightdistance = 260,
		terraformspeed = 450,
		trackoffset = 3,
		trackstrength = 6,
		tracktype = "corwidetracks",
		trackwidth = 32,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.1979,
		turnrate = 421,
		workertime = 90,
		buildoptions = {
			"legsolar",
			"legadvsol",
			"legwin",
			"corgeo",
			"cormstor",
			"corestor",
			"legmex",
			"legmext15",
			"cormakr",
			"legavp",
			"leglab",
			"legvp",
			"legap",
			"leghp",
			"cornanotc",
			"coreyes",
			"legrad",
			"legdrag",
			"legdtr",
			"leglht",
			"legmg",
			"legcluster",
			"legrl",
			"legrhapsis",
			"leglupara",
			"cordl",
			"legjam",
			"corjuno",
			"corsy",
			"legdefcarryt1",
		},
		customparams = {
			unitgroup = 'builder',
			area_mexT15_def = "legmext15",
			model_author = "Tharsis",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "corvehicles",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0.31364440918 1.09863281317e-06 0.657264709473",
				collisionvolumescales = "32.9147644043 17.5585021973 49.4168548584",
				collisionvolumetype = "Box",
				damage = 874,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				metal = 87,
				object = "Units/legcv_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 487,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 35,
				object = "Units/cor3X3D.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2-builder",
				[2] = "deathceg3-builder",
				[3] = "deathceg4-builder",
			},
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			capture = "capture1",
			repair = "repair2",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vcormove",
			},
			select = {
				[1] = "vcorsel",
			},
		},
	},
}
