return {
	legch = {
		maxacc = 0.049,
		maxdec = 0.11,
		energycost = 2600,
		metalcost = 185,
		builddistance = 150,
		builder = true,
		buildpic = "LEGCH.DDS",
		buildtime = 4360,
		canmove = true,
		collisionvolumeoffsets = "0 1 0",
		collisionvolumescales = "27 18 38",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energymake = 11,
		energystorage = 75,
		explodeas = "smallexplosiongeneric-builder",
		footprintx = 3,
		footprintz = 3,
		health = 1390,
		maxslope = 16,
		speed = 72.9,
		maxwaterdepth = 0,
		movementclass = "HOVER3",
		objectname = "Units/LEGCH.s3o",
		radardistance = 50,
		script = "Units/LEGCH_CLEAN.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd-builder",
		sightdistance = 338,
		terraformspeed = 550,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.518,
		turnrate = 410,
		workertime = 105,
		buildoptions = {
			[1] = "legsolar",
			[2] = "legadvsol",
			[3] = "legwin",
			[4] = "leggeo",
			[5] = "legmstor",
			[6] = "legestor",
			[7] = "legmex",
			[8] = "legeconv",
			[9] = "leglab",
			[10] = "legvp",
			[11] = "legap",
			[12] = "leghp",
			[13] = "legavp",
			[14] = "legnanotc",
			[15] = "legnanotcplat",
			[16] = "legeyes",
			[17] = "legrad",
			[18] = "legdrag",
			[19] = "legdtr",
			[20] = "leglht",
			[21] = "legmg",
			[22] = "legcluster",
			[23] = "legrl",
			[24] = "legrhapsis",
			[25] = "leglupara",
			[26] = "legjuno",
			[27] = "legctl",
			[28] = "legjam",
			[29] = "legfhp",
			[30] = "legamphlab",
			[31] = "legsplab",
			[32] = "legsy",
			[33] = "legtide",
			[34] = "legfeconv",
			[35] = "leguwmstore",
			[36] = "leguwestore",
			[37] = "legfdrag",
			[38] = "legfrad",
			[39] = "legfmg",
			[40] = "legfrl",
			[41] = "legtl",
			[42] = "leguwgeo",
			[43] = "legadvshipyard",
			[44] = "leghive",
			[45] = "legfhive",
		},
		customparams = {
			unitgroup = "builder",
			model_author = "EnderRobo",
			normaltex = "unittextures/leg_normal.dds",
			subfolder = "CorHovercraft",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "27 18 38",
				collisionvolumetype = "Box",
				damage = 805,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				metal = 100,
				object = "Units/legch_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 403,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				metal = 40,
				object = "Units/cor3X3D.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:waterwake-small-hover",
				[2] = "custom:bowsplash-small-hover",
				[3] = "custom:hover-wake-tiny",
			},
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "hovmdok2",
			},
			select = {
				[1] = "hovmdsl2",
			},
		},
	},
}
