return {
	corsok = {
		activatewhenbuilt = true,
		builder = false,
		buildpic = "CORSOK.DDS",
		buildtime = 27000,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		cantbetransported = true,
		collisionvolumeoffsets = "0 3 0",
		collisionvolumescales = "52 40 58",
		collisionvolumetype = "CylY",
		corpse = "dead",
		energycost = 19000,
		explodeas = "hugeexplosiongeneric",
		footprintx = 4,
		footprintz = 4,
		health = 4200,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.01731,
		maxdec = 0.01731,
		maxslope = 16,
		maxwaterdepth = 0,
		metalcost = 950,
		movementclass = "HHOVER4",
		nochasecategory = "VTOL",
		objectname = "Units/CORSOK.s3o",
		radardistance = 0,
		script = "Units/corsok.cob",
		selfdestructas = "hugeExplosionGenericSelfd",
		sightdistance = 650,
		sonardistance = 550,
		speed = 45.3,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.056,
		turnrate = 290,
		waterline = 7,
		customparams = {
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "CorGantry",
			techlevel = 3,
			unitgroup = "weapon",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				damage = 7000,
				featuredead = "heap",
				footprintx = 4,
				footprintz = 4,
				height = 15,
				metal = 588,
				object = "Units/corsok_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "85.0 14.0 6.0",
				collisionvolumetype = "cylY",
				damage = 3500,
				footprintx = 4,
				footprintz = 4,
				height = 4,
				metal = 221,
				object = "Units/cor4x4d.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:waterwake-small-hover",
				[2] = "custom:bowsplash-small-hover",
				[3] = "custom:hover-wake-large",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "hovlgok2",
			},
			select = {
				[1] = "hovlgsl2",
			},
		},
		weapondefs = {
			corsok_laser = {
				areaofeffect = 20,
				avoidfeature = false,
				burnblow = true,
				collideenemy = true,
				corethickness = 1.5,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.05,
				edgeeffectiveness = 0.85,
				energypershot = 500,
				explosiongenerator = "custom:laserhit-large-aqua",
				impulsefactor = 0,
				intensity = 2.2,
				name = "Disruptor Bolt",
				range = 725,
				reloadtime = 4.5,
				rgbcolor = "0.0 0.5 0.8",
				rgbcolor2 = "0.2 0.8 1.0",
				soundhitdry = "xplosml5",
				soundhitwet = "sizzle",
				soundstart = "lasrfir5",
				soundtrigger = 1,
				thickness = 2.5,
				tolerance = 525,
				tracks = true,
				turnrate = 20000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 1673,
				damage = {
					default = 750,
					subs = 500,
					vtol = 250,
				},
			},
			depthcharge = {
				areaofeffect = 24,
				avoidfeature = false,
				avoidfriendly = false,
				burnblow = true,
				collidefriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.9,
				explosiongenerator = "custom:genericshellexplosion-medium-uw",
				flighttime = 3,
				impulsefactor = 0.123,
				model = "cordepthcharge.s3o",
				name = "Depthcharge launcher",
				noselfdamage = true,
				predictboost = 0,
				range = 400,
				reloadtime = 2,
				soundhit = "xplodep2",
				soundstart = "torpedo1",
				startvelocity = 120,
				tolerance = 1000,
				tracks = true,
				turnrate = 6000,
				turret = true,
				waterweapon = true,
				weaponacceleration = 20,
				weapontimer = 3,
				weapontype = "TorpedoLauncher",
				weaponvelocity = 140,
				damage = {
					default = 225,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "CORSOK_LASER",
				onlytargetcategory = "NOTSUB",
			},
			[2] = {
				badtargetcategory = "NOTSUB",
				def = "DEPTHCHARGE",
				maindir = "0 -1 0",
				maxangledif = 179,
				onlytargetcategory = "CANBEUW UNDERWATER",
			},
		},
	},
}
