-- Writes modules/engine_handles.lua from the recoil-lua-library listings. Run from the repo root after a
-- submodule bump:   luajit tools/engine_handles/generate.lua
-- spec/modules/engine_handles_spec.lua fails until the generated file matches the listings again.
package.path = "./?.lua;" .. package.path
local Derive = require("tools/engine_handles/derive")

local syncedOnly, unsyncedOnly = Derive.Sides()
assert(syncedOnly and unsyncedOnly, "recoil-lua-library listings not checked out")

---@param names string[]
---@return string
local function block(names)
	local lines = {}
	for _, name in ipairs(names) do
		lines[#lines + 1] = string.format('\t\t"%s",', name)
	end
	return table.concat(lines, "\n")
end

local out = assert(io.open("modules/engine_handles.lua", "w"))
out:write(
	"-- GENERATED by tools/engine_handles/generate.lua from recoil-lua-library/library/generated/rts/Lua/; do not edit.\n"
		.. "-- The Spring functions the engine offers in one Lua handle only. modules/module_env.lua refuses them from a file\n"
		.. "-- declared for the other handle, or for any; spec/modules/engine_handles_spec.lua fails when this drifts.\n"
		.. "---@class EngineHandles\n"
		.. "---@field syncedOnly string[]\n"
		.. "---@field unsyncedOnly string[]\n"
		.. "return {\n\tsyncedOnly = {\n"
		.. block(Derive.Sorted(syncedOnly))
		.. "\n\t},\n\tunsyncedOnly = {\n"
		.. block(Derive.Sorted(unsyncedOnly))
		.. "\n\t},\n}\n"
)
out:close()
print(
	string.format(
		"modules/engine_handles.lua: %d synced-only, %d unsynced-only",
		#Derive.Sorted(syncedOnly),
		#Derive.Sorted(unsyncedOnly)
	)
)
