return {
	legnavaldefturret = {
		maxacc = 0,
		airsightdistance = 650,
		maxdec = 0,
		buildangle = 32768,
		energycost = 7500,
		metalcost = 600,
		buildpic = "legnavaldefturret.DDS",
		buildtime = 12000,
		canrepeat = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "70 50 70",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		explodeas = "mediumBuildingexplosiongeneric",
		footprintx = 5,
		footprintz = 5,
		idleautoheal = 5,
		idletime = 1800,
		mass = 9500,
		health = 5190,
		minwaterdepth = 12,
		objectname = "Units/legnavaldefturret.s3o",
		script = "Units/legnavaldefturret.cob",
		seismicsignature = 0,
		selfdestructas = "mediumBuildingExplosionGenericSelfd",
		sightdistance = 650,
		waterline = 0,
		yardmap = "ooooooooooooooooooooooooo",
		customparams = {
			unitgroup = 'weapon',
			model_author = "ZephyrSkies",
			normaltex = "unittextures/leg_normal.dds",
			removewait = true,
			subfolder = "Legion/SeaDefenses",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 0 0",
				collisionvolumescales = "70 50 70",
				collisionvolumetype = "Box",
				damage = 2500,
				featuredead = "HEAP",
				footprintx = 5,
				footprintz = 5,
				height = 50,
				metal = 350,
				object = "Units/legnavydefturret_dead.s3o",
				reclaimable = true,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-medium",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			cloak = "kloak1",
			uncloak = "kloak1un",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servmed2",
			},
			select = {
				[1] = "servmed2",
			},
		},
		weapondefs = {
			leg_med_anti_naval_salvo_rocket = {
				areaofeffect = 100,
				avoidfeature = false,
				burst = 4,
				burstrate = 0.185,
				cegtag = "missiletrailsmall-simple",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
                dance = 10,
                flighttime = 5,
				edgeeffectiveness = 0.2,
				explosiongenerator = "custom:genericshellexplosion-medium",
				firestarter = 70,
				impulsefactor = 0.185,
				intensity = 2.25,
				metalpershot = 0,
				model = "legmediumrocket.s3o",
				name = "Dual-Salvo Medium Rocket Launcher",
				noselfdamage = true,
				range = 720,
				reloadtime = 2.5,
				smoketrail = true,
				smokePeriod = 11,
				smoketime = 28,
				smokesize = 3.3,
				smokecolor = 1.0,
				smokeTrailCastShadow = false,
				castshadow = true, --projectile
				soundhit = "xplosml2",
				soundhitwet = "splshbig",
				soundstart = "SabotFire",
				startvelocity = 300,
				texture1 = "null",
				texture2 = "smoketraildark",
				turret = true,
				tracks = true,
				turnrate = 3000,
				firetolerance = 7000,
				tolerance = 7000,
				weaponacceleration = 150,
				weapontimer = 10,
				weapontype = "MissileLauncher",
				weaponvelocity = 600,
				damage = {
					default = 95,
				},
				customparams = {
					projectile_destruction_method = "descend",
					overrange_distance = 850,
				},
			},
		},
		weapons = {
			[1] = {
				def = "leg_med_anti_naval_salvo_rocket",
				fastautoretargeting = true,
				onlytargetcategory = "SURFACE",
				burstControlWhenOutOfArc = 2,
			},
		},
	},
}
