name: Flag Deprecated Animation Scripts

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for comparing with base branch

      - name: Get modified .bos and .cob files in scripts/Units
        id: changed_files
        run: |
          MODIFIED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep '^scripts/Units/.*\.\(bos\|cob\)$' || true)
          echo "filtered_files<<EOF" >> $GITHUB_OUTPUT
          echo "$MODIFIED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check for forbidden modifications
        run: |
          BLOCKED=0
          echo "${{ steps.changed_files.outputs.filtered_files }}" | while read file; do
            [ -z "$file" ] && continue
            
              base_name="${file%.*}"      # remove extension
              ext="${file##*.}"           # get extension
              clean_file="${base_name}_clean.${ext}"

              if [[ ! -f "$clean_file" ]]; then
                echo "✅ File '$file' is not a deprecated animation."
              else
                echo "❌ File '$file' is a deprecated animation. Please only base changes on the clean counterpart: '$clean_file'."
                BLOCKED=1
              fi
          done

          if [[ "$BLOCKED" -eq 1 ]]; then
            echo "Blocking PR due to unclean modifications. Please switch the unit.lua over to its _clean animation counterpart, e.g. script = Units/CORINT_CLEAN.cob, test the new animation and base your changes on that."
            exit 1
          else
            echo "All modified files are clean or allowed."
          fi
