name: Run Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Upload Event File
        uses: actions/upload-artifact@v4
        with:
          name: Event File
          path: ${{ github.event_path }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Tests
        run: docker compose -f tools/headless_testing/docker-compose.yml up
        timeout-minutes: 30

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: |
            tools/headless_testing/testlog/results.json
