name: Update Recoil Lua library
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update:
    name: Update recoil-lua-library
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: recoil-lua-library
          submodules: 'true'
          # https://stackoverflow.com/a/77212392/317135
          fetch-depth: 0
          ssh-key: ${{ secrets.ACTION_RUNNER_PRIVATE }}
      - name: Pull latest submodule
        run: |
          git submodule update --remote --merge recoil-lua-library
      - name: Push updated submodule
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: recoil-lua-library
          commit_message: |
            Update Lua libary submodule